package irvine.oeis.a344;
// Generated by gen_seq4.pl 2023-09-20/lambda at 2023-09-21 01:53

import irvine.math.Mobius;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A344429 a(n) = Sum_{k=1..n} mu(k) * k^n.
 * @author Georg Fischer
 */
public class A344429 extends LambdaSequence {

  /** Construct the sequence. */
  public A344429() {
    super(1, n -> Integers.SINGLETON.sum(1, n, k -> Z.valueOf(Mobius.mobius(k)).multiply(Z.valueOf(k).pow(n))));
  }
}
