package irvine.oeis.a344;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.math.z.Z;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A344066 Expansion of Product_{k&gt;=1} (1 + 7^(k-1)*x^k).
 * @author Georg Fischer
 */
public class A344066 extends RationalProductTransform {

  /** Construct the sequence. */
  public A344066() {
    super(0, new Builder().f(-1).g(k -> Z.SEVEN.pow(k - 1).negate()));
  }
}
