package irvine.oeis.a333;
// Generated by gen_seq4.pl 2025-04-08.ack/multrar at 2025-04-08 00:02

import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.a160.A160384;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A333773 Replace 2&apos;s with (-1)&apos;s in ternary representation of n and sum nonzero terms with alternating signs.
 * @author Georg Fischer
 */
public class A333773 extends MultiTransformSequence {

  private static final DirectSequence A160384 = new A160384();

  /** Construct the sequence. */
  public A333773() {
    super(0, (self, n) -> n % 3 == 0 ? self.a(n / 3).multiply(3) : (n % 3 == 1 ? self.a(n / 3).multiply(3).add(A160384.a(n / 3).testBit(0) ? Z.NEG_ONE : Z.ONE) : self.a(n / 3).multiply(3).subtract(A160384.a(n / 3).testBit(0) ? Z.NEG_ONE : Z.ONE)), "0, 1,-1");
  }
}
