package irvine.oeis.a046;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A046698 a(0) = 0, a(1) = 1, a(n) = a(a(n-1)) + a(a(n-2)) if n &gt; 1.
 * @author Georg Fischer
 */
public class A046698 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A046698() {
    super(0, new long[] {0, 1, 0, 1},
      new long[] {1, -1});
  }
}
