package irvine.oeis.a261;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.recur.PeriodicSequence;
import irvine.oeis.transform.EulerTransform;


/**
 * A261115 Expansion of f(x, x) * f(x^4, x^8) in powers of x where f(,) is Ramanujan's general theta function.
 * @author Georg Fischer
 */
public class A261115 extends EulerTransform {

  /** Construct the sequence. */
  public A261115() {
    super(new PeriodicSequence(2, -3, 2, 0, 2, -3, 2, -1, 2, -3, 2, -2, 2, -3, 2, -1, 2, -3, 2, 0, 2, -3, 2, -2), 1);
  }
}
