package irvine.oeis.a261;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A261178 Expansion of exp(gamma) in base 2.
 * @author Georg Fischer
 */
public class A261178 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A261178() {
    super(1, CR.GAMMA.exp(), 2);
  }
}
