package irvine.oeis.a359;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-22 13:29

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A359665 a(n) = Sum_{k=0..n} binomial(k^3, k).
 * a(n) = sum(k=0,n,binom(k^3,k));
 * @author Georg Fischer
 */
public class A359665 extends LambdaSequence {

  /** Construct the sequence. */
  public A359665() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(Z.valueOf(k).pow(3), k)));
  }
}
