package irvine.oeis.a359;
// Generated by gen_seq4.pl hologfm/hologf at 2023-05-08 16:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A359175 a(n) = binomial(2*n-2,n) - 2*(n-1).
 * @author Georg Fischer
 */
public class A359175 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A359175() {
    // o.g.f. (x^4-2*x^3-2*x^2+2*x-1)/(1-x)^2+4*x^2/(1-4*x)^(1/2)/(-1+(1-4*x)^(1/2))^2
    // recurrence 2*(n-1)*(11*n-45)*u(n-1)+2*(2*n-11)*(n-7)*u(n-5)-(21*n-92)*(n-6)*u(n-4)+(49*(n-1)^2-301*n+731)*u(n-3)+(-51*(n-1)^2+232*n-437)*u(n-2)-3*n*(n-4)*u(n) = 0
    super(3, "[[0],[154,-50,4],[-552,218,-21],[780,-399,49],[-488,334,-51],[90,-112,22],[0,12,-3]]", "[0,9,48,200,780,2989,11424]", 0);
  }
}
