package irvine.oeis.a359;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-24 21:51

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A359730 a(n) = Sum_{d|n} 2^(d-1) * d^(n/d).
 * a(n) = sumdiv(n,d,2^(d-1)*d^(n/d));
 * @author Georg Fischer
 */
public class A359730 extends LambdaSequence {

  /** Construct the sequence. */
  public A359730() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> Z.ONE.shiftLeft(d - 1).multiply(Z.valueOf(d).pow(n / d))));
  }
}
