package irvine.oeis.a360;
// Generated by gen_seq4.pl 2026-09-07.ack/lambdan at 2026-09-07 17: 57

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a090.A090885;

/**
 * A360108 Sum of squares of digits of primorial base expansion of n.
 * @author Georg Fischer
 */
public class A360108 extends LambdaSequence {

  private static final DirectSequence A090885 = new A090885();

  /** Construct the sequence. */
  public A360108() {
    super(0, n -> A090885.a(Functions.PRIMORIAL_BASE_EXP.z(n)));
  }
}
