package irvine.oeis.a360;
// Generated by gen_seq4.pl holgrep/holos at 2023-05-08 18:43

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A360314 a(n) = Sum_{k=0..floor(n/3)} (-1)^k * binomial(n-1-2*k,n-3*k) * binomial(2*k,k).
 * @author Georg Fischer
 */
public class A360314 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A360314() {
    super(0, "[[0],[-12,4],[6,-4],[2,-1],[-2,2],[0,-1]]", "1,0,0,-2,-2,-2,4,10,16,2", 0);
  }
}
