package irvine.oeis.a360;
// Generated by gen_seq4.pl multm/mult at 2023-03-28 18:24

import irvine.math.z.Z;
import irvine.oeis.MultiplicativeSequence;

/**
 * A360970 Multiplicative with a(p^e) = e^3, p prime and e &gt; 0.
 * @author Georg Fischer
 */
public class A360970 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A360970() {
    super(1, (p, e) -> Z.valueOf(e).pow(3));
  }
}
