package irvine.oeis.a328;
// Generated by gen_seq4.pl 2025-01-01.ack/rgs1 at 2025-01-01 23:25

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a007.A007814;
import irvine.oeis.a046.A046523;
import irvine.oeis.a276.A276156;
import irvine.oeis.transform.RestrictedGrowthTransformSequence;

/**
 * A328472 Lexicographically earliest infinite sequence such that a(i) = a(j) =&gt; A278226(A328461(i)) = A278226(A328461(j)) for all i, j.
 * @author Georg Fischer
 */
public class A328472 extends RestrictedGrowthTransformSequence {

  private static final DirectSequence A007814 = new A007814();
  private static final DirectSequence A046523 = new A046523();
  private static final DirectSequence A276156 = new A276156();

  /** Construct the sequence. */
  public A328472() {
    super(1, new LambdaSequence(1, n -> A046523.a(Functions.PRIMORIAL_BASE_EXP.z(A276156.a(n).divide(Functions.PRIMORIAL_COUNT.z(A007814.a(n)))))));
  }
}
