package irvine.oeis.a178;
// Generated by gen_seq4.pl anopan 

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a000.A000027;
import irvine.oeis.a056.A056239;

/**
 * A178503 n minus totally additive with a(p)=PrimePi(p), where PrimePi(n)=A000720(n).
 * @author Georg Fischer
 */
public class A178503 extends AbstractSequence {

  private A000027 mSeq1 = new A000027();
  private A056239 mSeq2 = new A056239();

  /** Construct the sequence. */
  public A178503() {
    super(1);
  }

  @Override
  public Z next() {
    return mSeq1.next().subtract(mSeq2.next());
  }
}
