package irvine.oeis.a178;
// Generated by gen_seq4.pl 2024-01-04/lambdan at 2024-01-05 23:45

import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.oeis.LambdaSequence;

/**
 * A178191 Numerators of sum (1/7)^((k^2+3k)/2) from k=1 to n.
 * @author Georg Fischer
 */
public class A178191 extends LambdaSequence {

  /** Construct the sequence. */
  public A178191() {
    super(1, n -> Rationals.SINGLETON.sum(1, n, k -> new Q(1, 7).pow((long) k * (k + 3) / 2)).num());
  }
}
