package irvine.oeis.a238;
// Generated by gen_seq4.pl holos [[0],[1],[-4],[6],[-4],[1]] [3,8,15,25,39] 0 at 2019-12-08 00:24
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A238806 Number of <code>n X 2 0..2</code> arrays with no element equal to one plus the sum of elements to its left or one plus the sum of the sum of elements above it, modulo 3.
 * @author Georg Fischer
 */
public class A238806 extends HolonomicRecurrence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A238806() {
    super(1, "[[0],[1],[-4],[6],[-4],[1]]", "[3,8,15,25,39]", 0);
  }
}
