package irvine.oeis.a202;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-09-13 11:40

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A202617 E.g.f. satisfies: A(x) = exp( x*(1 + A(x)^2)/2 ).
 * a(n) = (1/2^n)*sum(k=0,n,binom(n,k)*(2*k+1)^(n-1))
 * @author Georg Fischer
 */
public class A202617 extends LambdaSequence {

  /** Construct the sequence. */
  public A202617() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(n, k).multiply(Z.valueOf(2L * k + 1).pow(n - 1))).divide(Z.ONE.shiftLeft(n)));
  }
}
