package irvine.oeis.a138;
// Generated by gen_seq4.pl n2 at 2022-04-08 22:12

import irvine.math.z.Z;
import irvine.oeis.a061.A061652;

/**
 * A138834 Bisection of even superperfect numbers A061652.
 * @author Georg Fischer
 */
public class A138834 extends A061652 {

  @Override
  public Z next() {
    final Z result = super.next();
    super.next();
    return result;
  }
}
