package irvine.oeis.a138;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A138587 The union of all entries of <code>A024495, A131708</code> and <code>A024493</code> sorted into natural order.
 * @author Georg Fischer
 */
public class A138587 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A138587() {
    super(0, new long[] {0, 1, 3, 4, 5, 4, 2},
      new long[] {1, 1, -1, -1, -2, -2});
  }
}
