package irvine.oeis.a138;
// Generated by gen_seq4.pl holos [0,-127,1] [1] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A138128 Powers of 127.
 * @author Georg Fischer
 */
public class A138128 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A138128() {
    super(1, "[0,-127,1]", "[1]", 0);
  }
}
