package irvine.oeis.a138;
// Generated by gen_seq4.pl 2024-03-30/filter at 2024-03-30 20:29

import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A138645 Primes p such that 7*p+2 is composite.
 * @author Georg Fischer
 */
public class A138645 extends FilterSequence {

  /** Construct the sequence. */
  public A138645() {
    super(1, new A000040(), v -> !v.multiply(7).add(2).isProbablePrime());
  }
}
