package irvine.oeis.a068;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A068931 Number of incongruent ways to tile a 6 X n room with 1x2 Tatami mats. At most 3 Tatami mats may meet at a point.
 * @author Georg Fischer
 */
public class A068931 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A068931() {
    super(1, new long[] {0, 1, 6, 2, 2, 1, 0, -5, -2, -7, -2, -2, -6, -2, -2, -2, -6, 
      3, 0, 6, 2, 5, 2, 6, 2, 0, 0, -1},
      new long[] {1, 0, 0, 0, 0, -1, 0, -1, 0, 0, -1, 0, 0, 0, -1, 1, 0, 1, 
      0, 1, 0, 1});
  }
}
