package irvine.oeis.a068;
// Generated by gen_seq4.pl holos [[0],[-720,360],[20,-40],[1,1]] [1,1,20] 0 at 2019-12-06 18:14
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A068772 Generalized Catalan numbers.
 * @author Georg Fischer
 */
public class A068772 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A068772() {
    super(0, "[[0],[-720,360],[20,-40],[1,1]]", "[1,1,20]", 0);
  }
}
