package irvine.oeis.a223;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A223332 Rolling cube footprints: number of <code>3 X n 0..7</code> arrays starting with 0 where 0..7 label vertices of a cube and every array movement to a horizontal or antidiagonal neighbor moves along a corresponding cube edge.
 * @author Georg Fischer
 */
public class A223332 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A223332() {
    super(1, new long[] {0, 64, -909, 1323, -54},
      new long[] {1, -18, 27});
  }
}
