package irvine.oeis.a223;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A223764 Number of <code>n X 2 0..1</code> arrays with rows, columns and antidiagonals unimodal and diagonals nondecreasing.
 * @author Georg Fischer
 */
public class A223764 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A223764() {
    super(1, new long[] {0, 4, -8, 8, -4, 1},
      new long[] {1, -5, 10, -10, 5, -1});
  }
}
