package irvine.oeis.a259;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.transform.EulerTransform;
import irvine.oeis.recur.PeriodicSequence;


/**
 * A259660 Expansion of f(-x, -x^11) * psi(-x^3)^2 / psi(-x) in powers of x where psi(), f() are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A259660 extends EulerTransform {

  /** Construct the sequence. */
  public A259660() {
    super(new PeriodicSequence(0, 0, -1, 1, 1, 0, 1, 1, -1, 0, 0, -2), 1);
  }
}
