package irvine.oeis.a259;
// Generated by gen_seq4.pl 2026-02-02.ack/rambdan at 2026-02-02 19:35

import irvine.math.q.Q;
import irvine.math.z.Binomial;
import irvine.math.z.Z;
import irvine.oeis.RationalLambdaSequence;

/**
 * A259852 Numerators of the terms of Lehmer&apos;s series S_2(2), where S_k(x) = Sum_{n&gt;=1} n^k*x^n/binomial(2*n, n).
 * @author Georg Fischer
 */
public class A259852 extends RationalLambdaSequence {

  /** Construct the sequence. */
  public A259852() {
    super(1, NUM, n -> new Q(Z.TWO.pow(n).multiply(n).multiply(n), Binomial.binomial(2 * n, n)));
  }
}
