package irvine.oeis.a259;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.transform.EulerTransform;
import irvine.oeis.recur.PeriodicSequence;


/**
 * A259662 Expansion of phi(-q^3) / phi(-q)^3 in powers of q where phi() is a Ramanujan theta function.
 * @author Georg Fischer
 */
public class A259662 extends EulerTransform {

  /** Construct the sequence. */
  public A259662() {
    super(new PeriodicSequence(6, 3, 4, 3, 6, 2), 1);
  }
}
