package irvine.oeis.a319;
// Generated by gen_seq4.pl A319394/tripnk

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;

/**
 * A319402 Number of partitions of n into exactly nine positive Fibonacci numbers.
 * @author Georg Fischer
 */
public class A319402 extends AbstractSequence {

  private int mN;
  private final A319394 mSeq = new A319394();

  /** Construct the sequence. */
  public A319402() {
    super(0);
    mN = -1;
  }

  @Override
  public Z next() {
    ++mN;
    return mSeq.compute(mN, 9);
  }
}

