package irvine.oeis.a121;
// Generated by gen_seq4.pl floor at 2021-08-30 23:16

import irvine.math.cr.CR;
import irvine.math.z.Z;
import irvine.oeis.FloorSequence;

/**
 * A121929 a(n) = ceiling(n*(e^Pi + Pi^e)).
 * @author Georg Fischer
 */
public class A121929 extends FloorSequence {
  /** Construct the sequence. */
  public A121929() {
    super(0);
  }

  protected Z evalCR(final long n) {
    return CR.valueOf(n).multiply(CR.E.pow(CR.PI).add(CR.PI.pow(CR.E))).ceil();
  }

}
