package irvine.oeis.a121;
// Generated by gen_seq4.pl 2025-06-08.ack/polya at 2025-06-08 23:06

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a001.A001006;

/**
 * A121398 Main diagonal of triangle A121400; also equals the partial sums of column 0 (A121399) of the same triangle.
 * new A001006()
 * @author Georg Fischer
 */
public class A121398 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A121398() {
    super(0, "[1],[1,-1]", "x,B,<2,sub,x,B,*,1,x,B,<2,-,*,p1,/", 0, 0, 1, 1, new A001006());
  }
}
