package irvine.oeis.a109;
// Generated by ./gen_seq4.pl /partsum at 2022-06-25 09:09

import irvine.oeis.PartialSumSequence;
import irvine.oeis.a011.A011757;

/**
 * A109770 Prime(1^2) + prime(2^2) + ... + prime(n^2).
 * @author Sean A. Irvine
 */
public class A109770 extends PartialSumSequence {

  /** Construct the sequence. */
  public A109770() {
    super(new A011757());
  }
}
