package irvine.oeis.a109;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-09-12 11:03

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A109995 Number of unlabeled ordered minimal T_0-covers of an n-set, cf. A094545.
 * a(n)=sum(m=0, n, binom(2^m-m-1, n-m))
 * @author Georg Fischer
 */
public class A109995 extends LambdaSequence {

  /** Construct the sequence. */
  public A109995() {
    super(0, n -> Integers.SINGLETON.sum(0, n, m -> Binomial.binomial(Z.TWO.pow(m).subtract(m + 1), n - m)));
  }
}
