package irvine.oeis.a109;
// Generated by gen_seq4.pl 2025-10-13.ack/lambdan at 2025-10-13 18:59

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A109963 Diagonal sums of number triangle A109962.
 * @author Georg Fischer
 */
public class A109963 extends LambdaSequence {

  /** Construct the sequence. */
  public A109963() {
    super(0, n -> Z.NEG_ONE.pow(n).multiply(Integers.SINGLETON.sum(0, n / 2, k -> Binomial.binomial(4 * n - 4 * k, n - 2 * k).multiply(4 * k + 1).divide(3 * n - 2 * k + 1))));
  }
}
