package irvine.oeis.a109;
// Generated by gen_seq4.pl suchprik at 2021-01-04 15:38
// DO NOT EDIT here!

import irvine.oeis.a103.A103603;

/**
 * A109371 Numbers k such that the string 11k is prime.
 * @author Georg Fischer
 */
public class A109371 extends A103603 {

  /** Construct the sequence. */
  public A109371() {
    super("11");
  }
}
