package irvine.oeis.a266;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A266721 Decimal representation of the middle column of the "Rule <code>59"</code> elementary cellular automaton starting with a single ON (black) cell.
 * @author Georg Fischer
 */
public class A266721 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A266721() {
    super(0, new long[] {1, 0, 0, 1, -1},
      new long[] {1, -2, -1, 2});
  }
}
