package irvine.oeis.a266;
// Generated by gen_seq4.pl 2026-09-07.ack/lambdan at 2026-09-07 17: 57

import irvine.oeis.LambdaSequence;
import irvine.oeis.a258.A258306;
import irvine.oeis.triangle.DirectArray;

/**
 * A266386 Sum over all Motzkin paths of length n of products over all peaks p of (x_p+n*y_p)/y_p, where x_p and y_p are the coordinates of peak p.
 * @author Georg Fischer
 */
public class A266386 extends LambdaSequence {

  private static final DirectArray A258306 = new A258306();

  /** Construct the sequence. */
  public A266386() {
    super(0, n -> A258306.a(n, n));
  }
}
