package irvine.oeis.a132;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A132969 Expansion of phi(q) * chi(q) in powers of q where phi(), chi() are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A132969 extends EulerTransform {

  /** Construct the sequence. */
  public A132969() {
    super(new PeriodicSequence(3, -4, 3, -1), 1);
  }
}
