package irvine.oeis.a224;
// Generated by gen_seq4.pl 2025-04-30.ack/filprof at 2025-04-30 23:37

import irvine.math.z.Z;
import irvine.oeis.FilterSequence;
import irvine.oeis.LambdaSequence;

/**
 * A224468 Primes of the form 7^n - n.
 * @author Georg Fischer
 */
public class A224468 extends FilterSequence {

  /** Construct the sequence. */
  public A224468() {
    super(1, new LambdaSequence(0, k -> Z.SEVEN.pow(k).subtract(k)), PRIME);
  }
}
