package irvine.oeis.a224;
// Generated by gen_seq4.pl holos [[0],[0,-1,-2,-1],[1]] [1,4,72] 0 at 2020-03-14 22:45
// Recurrence: a[n+0]-n*(n+1)^2*a[n-1]=0
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A224900 n!*((n+1)!)^2.
 * @author Georg Fischer
 */
public class A224900 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A224900() {
    super(0, "[[0],[0,-1,-2,-1],[1]]", "[1,4,72]", 0);
  }
}
