package irvine.oeis.a077;
// Generated by gen_seq4.pl mult at 2022-08-01 11:56

import irvine.oeis.MultiplicativeSequence;

/**
 * A077456 a(n) = sigma_5(n^5)/sigma(n^5).
 * @author Georg Fischer
 */
public class A077456 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A077456() {
    super(1, (p, e) -> p.pow(20L * e + 4).add(p.pow(15L * e + 3)).add(p.pow(10L * e + 2)).add(p.pow(5L * e + 1)).add(1).divide(p.pow(4).add(p.pow(3)).add(p.square()).add(p).add(1)));
  }
}
