package irvine.oeis.a077;
// Generated by gen_seq4.pl dead at 2023-06-20 13:48

import irvine.oeis.DeadSequence;

/**
 * A077109 Duplicate of A070923.
 * @author Georg Fischer
 */
public class A077109 extends DeadSequence {

  /** Construct the sequence. */
  public A077109() {
    super(0);
  }
}
