package irvine.oeis.a110;
// Generated by gen_seq4.pl 2025-11-19.ack/filnum at 2025-11-19 18:53

import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A110912 Numbers n such that 23*n^2 - 36 is prime.
 * @author Georg Fischer
 */
public class A110912 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A110912() {
    super(1, 0, k -> Predicates.PRIME.is(Z.valueOf(23).multiply(Z.valueOf(k).square()).subtract(Z.valueOf(36)).abs()));
  }
}
