package irvine.oeis.a110;
// Generated by gen_seq4.pl seqop a002 A002275 add(mN) 0 at 2020-01-25 22:40

import irvine.math.z.Z;
import irvine.oeis.a002.A002275;

/**
 * A110369 (Digit 1 repeated n times) + n.
 * @author Georg Fischer
 */
public class A110369 extends A002275 {
  private int mN = 0;

  /** Construct the sequence. */
  public A110369() {
    super(1);
    int bOffset = -1;
    while (bOffset < mN) {
      ++bOffset;
      super.next();
    }
  }

  @Override
  public Z next() {
    ++mN;
    return super.next().add(mN);
  }
}
