package irvine.oeis.a133;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-27 21:29

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A133298 a(n) = 1 + Sum_{i=1..n} Sum_{j=1..n} Sum_{k=1..n} i^(j+k).
 * a(n)=1 + n^2 + sum(j=2,n,(j*(j^n - 1)/(j-1))^2)
 * @author Georg Fischer
 */
public class A133298 extends LambdaSequence {

  /** Construct the sequence. */
  public A133298() {
    super(1, n -> Z.ONE.add(Z.valueOf(n).multiply(n)).add(Integers.SINGLETON.sum(2, n, j -> Z.valueOf(j).multiply(Z.valueOf(j).pow(n).subtract(Z.ONE)).divide(Z.valueOf(j - 1)).square())));
  }
}
