package irvine.oeis.a347;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-24 21:51

import irvine.math.function.Functions;
import irvine.oeis.LambdaSequence;

/**
 * A347304 a(n) = n!/(floor(n/2)!*floor(n/3)!*floor(n/6)!).
 * a(n) = n!/((n\2)!*(n\3)!*(n\6)!);
 * @author Georg Fischer
 */
public class A347304 extends LambdaSequence {

  /** Construct the sequence. */
  public A347304() {
    super(0, n -> Functions.FACTORIAL.z(n).divide(Functions.FACTORIAL.z(n / 2).multiply(Functions.FACTORIAL.z(n / 3)).multiply(Functions.FACTORIAL.z(n / 6))));
  }
}
