package irvine.oeis.a059;
// Generated by gen_seq4.pl engelex at 2020-11-22 22:05
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.EngelExpansionSequence;


/**
 * A059191 Engel expansion of 1/gamma, (gamma is the Euler-Mascheroni constant A001620) = 1.73245.
 * @author Georg Fischer
 */
public class A059191 extends EngelExpansionSequence {

  /** Construct the sequence. */
  public A059191() {
    super();
  }

  @Override
  protected CR getN() {
    return CR.GAMMA.inverse();
  }
}
