package irvine.oeis.a059;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A059727 a(n) = Fibonacci(n)*(Fibonacci(n) + 1).
 * @author Georg Fischer
 */
public class A059727 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A059727() {
    super(0, new long[] {0, 2, -4, -2, 2},
      new long[] {1, -3, -1, 5, 1, -1});
  }
}
