package irvine.oeis.a189;
// Generated by gen_seq4.pl posins at 2021-09-21 20:57

import irvine.oeis.PositionSequence;

/**
 * A189291 Positions of 1 in A189289; complement of A189290.
 * @author Georg Fischer
 */
public class A189291 extends PositionSequence {

  /** Construct the sequence. */
  public A189291() {
    super(1, new A189289(), 1);
  }
}
