package irvine.oeis.a189;
// Generated by gen_seq4.pl posins at 2021-09-20 11:24

import irvine.oeis.PositionSequence;
import irvine.oeis.a064.A064990;

/**
 * A189659 Positions of 1 in A064990; complement of A189658.
 * @author Georg Fischer
 */
public class A189659 extends PositionSequence {

  /** Construct the sequence. */
  public A189659() {
    super(1, new A064990(), 1);
  }
}
