package irvine.oeis.a189;
// Generated by gen_seq4.pl 2024-07-05/lambdan at 2024-07-05 23:59

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a068.A068311;

/**
 * A189100 a(n) = lcm(n!,n!')/gcd(n!,n!'), where n!' is the arithmetic derivative of n! (A068311).
 * @author Georg Fischer
 */
public class A189100 extends LambdaSequence {

  private static final DirectSequence A068311 = new A068311();

  /** Construct the sequence. */
  public A189100() {
    super(1, n -> Functions.LCM.z(Functions.FACTORIAL.z(n), A068311.a(n)).divide(Functions.GCD.z(Functions.FACTORIAL.z(n), A068311.a(n))));
  }
}
