package irvine.oeis.a189;
// Generated by gen_seq4.pl insect/insect2 at 2022-02-24 19:57

import irvine.oeis.IntersectionSequence;
import irvine.oeis.a087.A087679;
import irvine.oeis.a108.A108701;

/**
 * A189051 Numbers n such that n+/-2 and n^2+/-2 are all primes.
 * @author Georg Fischer
 */
public class A189051 extends IntersectionSequence {

  /** Construct the sequence. */
  public A189051() {
    super(new A087679(), new A108701());
  }
}
