package irvine.oeis.a053;
// Generated by gen_seq4.pl squaredig4 10 at 2022-01-11 22:24
// DO NOT EDIT here!

import irvine.oeis.SquareDigitsSequence;

/**
 * A053949 Squares composed of digits {3, 6, 9}.
 * @author Georg Fischer
 */
public class A053949 extends SquareDigitsSequence {

  /** Construct the sequence. */
  public A053949() {
    super(1, 10, 5, "3, 6, 9");
  }
}
