package irvine.oeis.a053;
// Generated by gen_seq4.pl eulerper 0 20 1, -1, 1, 0, 0, -1, 1, 0, 1, -2, 1, 0, 1, -1, 0, 0, 1, -1, 1, -2 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A053694 Number of <code>self-conjugate 5-core</code> partitions of <code>n</code>.
 * @author Georg Fischer
 */
public class A053694 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A053694() {
    super(new PeriodicSequence(1, -1, 1, 0, 0, -1, 1, 0, 1, -2, 1, 0, 1, -1, 0, 0, 1, -1, 1, -2), 0);
  }
}
