package irvine.oeis.a240;
// Generated by gen_seq4.pl 2026-08-16.ack/lambdan at 2026-08-16 21: 46

import irvine.oeis.LambdaSequence;
import irvine.oeis.a238.A238349;
import irvine.oeis.triangle.DirectArray;

/**
 * A240744 Number of compositions of n having exactly nine fixed points.
 * @author Georg Fischer
 */
public class A240744 extends LambdaSequence {

  private static final DirectArray A238349 = new A238349();

  /** Construct the sequence. */
  public A240744() {
    super(45, n -> A238349.a(n, 9));
  }
}
