package irvine.oeis.a240;
// Generated by gen_seq4.pl 2024-04-09/lpf at 2024-04-09 23:00

import irvine.factor.factor.Jaguar;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A240552 Greatest prime factor of n^9+1.
 * @author Georg Fischer
 */
public class A240552 extends LambdaSequence {

  /** Construct the sequence. */
  public A240552() {
    super(1, n -> Jaguar.factor(Z.valueOf(n).pow(9).add(1)).largestPrimeFactor());
  }
}
