package irvine.oeis.a355;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-09-12 11:03

import irvine.factor.prime.Puma;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A355198 Sum of the smallest parts of the partitions of n into exactly 3 prime parts.
 * a(n)=sum(j=1, floor(n/3), sum(i=j, floor((n-j)/2), j*(primepi(i)-primepi(i-1))*(primepi(j)-primepi(j-1))*(primepi(n-i-j)-primepi(n-i-j-1))))
 * @author Georg Fischer
 */
public class A355198 extends LambdaSequence {

  /** Construct the sequence. */
  public A355198() {
    super(0, n -> Integers.SINGLETON.sum(1, n / 3, j -> Integers.SINGLETON.sum(j, (n - j) / 2, i -> Z.valueOf(j).multiply(Puma.primePiZ(i).subtract(Puma.primePiZ(i - 1))).multiply(Puma.primePiZ(j).subtract(Puma.primePiZ(j - 1))).multiply(Puma.primePiZ(n - i - j).subtract(Puma.primePiZ(n - i - j - 1))))));
  }
}
