package irvine.oeis.a355;
// Generated by gen_seq4.pl 2024-06-16/lambdan at 2024-06-16 23:57

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a003.A003961;

/**
 * A355442 a(n) = gcd(A003961(n), A276086(n)), where A003961 is fully multiplicative with a(p) = nextprime(p), and A276086 is primorial base exp-function.
 * @author Georg Fischer
 */
public class A355442 extends LambdaSequence {

  private static final DirectSequence A003961 = new A003961();

  /** Construct the sequence. */
  public A355442() {
    super(1, n -> Functions.GCD.z(A003961.a(n), Functions.PRIMORIAL_BASE_EXP.z(n)));
  }
}
