package irvine.oeis.a355;
// Generated by gen_seq4.pl 2024-11-19.ack/lambdan at 2024-11-19 23:27

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.LambdaSequence;

/**
 * A355502 Inequivalent simultaneous colorings of the faces, vertices and edges of the cube under rotational symmetry using exactly n colors.
 * @author Georg Fischer
 */
public class A355502 extends LambdaSequence {

  /** Construct the sequence. */
  public A355502() {
    super(1, n -> (new Q(Functions.FACTORIAL.z(n)).divide(24)).multiply(new Q(Functions.STIRLING2.z(26, n)).add(new Q(9).multiply(Functions.STIRLING2.z(14, n))).add(new Q(8).multiply(Functions.STIRLING2.z(10, n))).add(new Q(6).multiply(Functions.STIRLING2.z(8, n)))).num());
  }
}
