package irvine.oeis.a355;
// Generated by gen_seq4.pl dfinite/holos at 2022-07-29 23:34

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A355414 Expansion of the e.g.f. log((1 - x) / (1 - 2*x)) / (1 - x)^5.
 * @author Georg Fischer
 */
public class A355414 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A355414() {
    super(0, "[[0],[24, 8,-6,-2],[-9, 12, 5],[-5,-4],[1]]", "0, 1, 13, 149", 0);
  }
}
