package irvine.oeis.a158;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A158450 Number of spanning forests in 3 X n grid.
 * @author Georg Fischer
 */
public class A158450 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A158450() {
    super(0, new long[] {1, -29, 134, -154, 28},
      new long[] {1, -33, 154, -176, 32});
  }
}
