package irvine.oeis.a373;
// Generated by gen_seq4.pl 2024-07-02/lambdan at 2024-07-03 22:28

import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a079.A079978;
import irvine.oeis.a276.A276150;

/**
 * A373840 a(n) = 1 if A276150(n) is a multiple of 3, otherwise 0, where A276150 is the digit sum in the primorial base.
 * @author Georg Fischer
 */
public class A373840 extends LambdaSequence {

  private static final DirectSequence A079978 = new A079978();
  private static final DirectSequence A276150 = new A276150();

  /** Construct the sequence. */
  public A373840() {
    super(0, n -> A079978.a(A276150.a(n)));
  }
}
