package irvine.oeis.a373;
// Generated by gen_seq4.pl 2024-07-11/lingf at 2024-07-11 18:00

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A373952 Number of integer compositions of n whose run-compression sums to 3.
 * @author Georg Fischer
 */
public class A373952 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A373952() {
    super(0, "[0, 0, 0, 3, -1, -1, -1]", "[1, -1, -1, 0, 1, 1, -1]");
  }
}
