package irvine.oeis.a373;
// Generated by gen_seq4.pl 2024-06-24/lambdan at 2024-06-24 23:40

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A373904 a(n) = Sum_{k=0..floor(n/2)} binomial(n+4*k,n-2*k).
 * @author Georg Fischer
 */
public class A373904 extends LambdaSequence {

  /** Construct the sequence. */
  public A373904() {
    super(0, n -> Integers.SINGLETON.sum(0, n / 2, k -> Binomial.binomial(n + 4 * k, n - 2 * k)));
  }
}
