package irvine.oeis.a373;
// Generated by gen_seq4.pl 2026-09-23.ack/rowsums at 2026-09-23 22: 26

import irvine.oeis.a372.A372208;
import irvine.oeis.triangle.RowSumSequence;

/**
 * A373762 Row sums of A372208.
 * @author Georg Fischer
 */
public class A373762 extends RowSumSequence {

  /** Construct the sequence. */
  public A373762() {
    super(1, new A372208());
  }
}
