package irvine.oeis.a373;
// Generated by gen_seq4.pl 2024-07-11/lingf at 2024-07-11 18:00

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A373358 a(n) = 4*a(n-1) -5*a(n-2) +2*a(n-3) +2*a(n-4) for a(0) = a(1) = 0, a(2) = 1, a(3) = 4 for n &gt;= 4.
 * @author Georg Fischer
 */
public class A373358 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A373358() {
    super(0, "[0, 0, 1]", "[1, -4, 5, -2, -2]");
  }
}
