package irvine.oeis.a373;
// Generated by gen_seq4.pl 2024-07-11/lingf at 2024-07-11 18:00

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A373554 Number of ternary length-2 squarefree words of length n not containing the subwords 021 or 10.
 * @author Georg Fischer
 */
public class A373554 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A373554() {
    super(0, "[1, 3, 3, 0, -1]", "[1, 0, -2, -1, 1]");
  }
}
