package irvine.oeis.a308;
// Generated by gen_seq4.pl holos [[-3,-6],[1]] [24] 0 at 2020-03-14 22:45
// Recurrence: a[n+0]=6*n+3
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A308603 Number of (not necessarily maximal) cliques in the n-dipyramidal graph.
 * @author Georg Fischer
 */
public class A308603 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A308603() {
    super(3, "[[-3,-6],[1]]", "[24]", 0);
  }
}
