package irvine.oeis.a308;
// Generated by gen_seq4.pl 2024-01-23/filnum at 2024-01-25 00:21

import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A308449 Numbers k such that 25*10^(2*k) + 5*10^k + 1 are prime.
 * @author Georg Fischer
 */
public class A308449 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A308449() {
    super(1, 0, k -> Z.valueOf(25).multiply(Z.TEN.pow(2 * k)).add(Z.FIVE.multiply(Z.TEN.pow(k))).add(1).isProbablePrime());
  }
}
