package irvine.oeis.a200;
// Generated by gen_seq4.pl decsolvr at 2021-07-31 13:37

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A200356 Decimal expansion of least x>0 satisfying x^2+4x+3=tan(x).
 * Equation; x^2+4x+3-(tan(x))
 * @author Georg Fischer
 */
public class A200356 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence */
  public A200356() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return x.pow(2).add(CR.FOUR.multiply(x)).add(CR.THREE).subtract(REALS.tan(x));
      }
    }.inverseMonotone(CR.valueOf(1.451), CR.valueOf(1.511)).execute(CR.ZERO));
  }
}
