package irvine.oeis.a200;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A200431 Number of -n..n arrays x(0..3) of 4 elements with zero sum and no two or three adjacent elements summing to zero.
 * @author Georg Fischer
 */
public class A200431 extends GeneratingFunctionSequence implements Conjectural {


  /** Construct the sequence. */
  public A200431() {
    super(1, new long[] {0, 0, 20, 12},
      new long[] {1, -4, 6, -4, 1});
  }
}
