package irvine.oeis.a168;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A168099 <code>a(n) =</code> number of natural numbers m such that <code>n - 9 &lt;= m &lt;= n + 9</code>.
 * @author Georg Fischer
 */
public class A168099 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A168099() {
    super(0, new long[] {9, -8, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1},
      new long[] {1, -2, 1});
  }
}
