package irvine.oeis.a128;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A128766 Number of inequivalent n-colorings of the vertices of the 3D cube under full orthogonal group of the cube (of order 48).
 * @author Georg Fischer
 */
public class A128766 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A128766() {
    super(1, new long[] {0, 1, 13, 105, 301, 301, 105, 13, 1},
      new long[] {1, -9, 36, -84, 126, -126, 84, -36, 9, -1});
  }
}
