package irvine.oeis.a128;
// Generated by gen_seq4.pl holos [0,-1,1] [1,3,4,5] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A128999 Start with an integer (in this case 1). First, add 5 or 6 if the integer is odd or even, respectively. Then divide by 2. Notice any a(1)&lt;=5 converges to 5 and any a(1)&gt;=6 converges to 6.
 * @author Georg Fischer
 */
public class A128999 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A128999() {
    super(1, "[0,-1,1]", "[1,3,4,5]", 0);
  }
}
