package irvine.oeis.a128;
// Generated by gen_seq4.pl amoda

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a006.A006125;
import irvine.oeis.a095.A095340;

/**
 * A128406 a(n) = (n+1)*2^(n*(n+1)).
 * @author Georg Fischer
 */
public class A128406 extends AbstractSequence {

  private final A095340 mSeq1 = new A095340();
  private final A006125 mSeq2 = new A006125();

  /** Construct the sequence. */
  public A128406() {
    super(0);
    mSeq2.next();
  }

  @Override
  public Z next() {
    return mSeq1.next().multiply(mSeq2.next());
  }
}
