package irvine.oeis.a128;
// Generated by gen_seq4.pl prisubd at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.PrimePositionSubsequence;


/**
 * A128070 Numbers k such that (3^k + 11^k)/14 is prime.
 * @author Georg Fischer
 */
public class A128070 extends PrimePositionSubsequence {

  private static final Z DIV = Z.valueOf(14);
  
  /** Construct the sequence */
  public A128070() {
    super("[[0],[-33],[14],[-1]]", "[2, 14]", 0);
  }

  @Override
  public boolean isOk(final Z term) {
    final Z[] quotRem = term.divideAndRemainder(DIV);
    return quotRem[1].equals(Z.ZERO) && quotRem[0].isProbablePrime();
  }

}
