package irvine.oeis.a093;
// Generated by gen_seq4.pl 2026-10-04.ack/lambdan at 2026-10-04 

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;

/**
 * A093897 a(n) = A093896(n)! / n^n.
 * @author Georg Fischer
 */
public class A093897 extends LambdaSequence {

  private static final DirectSequence A093896 = new A093896();

  /** Construct the sequence. */
  public A093897() {
    super(1, n -> Functions.FACTORIAL.z(A093896.a(n)).divide(Z.valueOf(n).pow(n)));
  }
}
