package irvine.oeis.a248;
// Generated by gen_seq4.pl 2026-04-29.ack/filtpos at 2026-04-29 22:34

import irvine.math.z.Z;
import irvine.oeis.DifferenceSequence;
import irvine.oeis.FilterPositionSequence;

/**
 * A248564 Numbers k such that A248562(k+1) = A248562(k) + 2.
 * @author Georg Fischer
 */
public class A248564 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A248564() {
    super(1, 1, new DifferenceSequence(1, new A248562()), v -> v.equals(Z.TWO));
  }
}
