package irvine.oeis.a248;
// Generated by gen_seq4.pl egypfr at 2020-11-19 22:49
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.EgyptianFractionSequence;


/**
 * A248279 Egyptian fraction representation of sqrt(54) (A010507) using a greedy function.
 * @author Georg Fischer
 */
public class A248279 extends EgyptianFractionSequence {

  /** Construct the sequence. */
  public A248279() {
    super(CR.valueOf(54).sqrt());
  }
}
