package irvine.oeis.a248;
// Generated by gen_seq4.pl dead at 2023-06-20 13:48

import irvine.oeis.DeadSequence;

/**
 * A248689 Not appropriate for the OEIS.
 * @author Georg Fischer
 */
public class A248689 extends DeadSequence {

  /** Construct the sequence. */
  public A248689() {
    super(1);
  }
}
