package irvine.oeis.a248;
// Generated by gen_seq4.pl 2026-04-29.ack/filtpos at 2026-04-29 22:34

import irvine.oeis.DifferenceSequence;
import irvine.oeis.FilterPositionSequence;

/**
 * A248419 Numbers k such that A248418(k+1) = A248418(k).
 * @author Georg Fischer
 */
public class A248419 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A248419() {
    super(1, 1, new DifferenceSequence(1, new A248418()), ZERO);
  }
}
