package irvine.oeis.a241;
// Generated by gen_seq4.pl 2026-09-02.ack/partpre1 at 2026-09-02 15: 37

import irvine.math.partition.IntegerPartition;
import irvine.math.partition.PartitionUtils;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A241335 Number of partitions p of n not including floor(mean(p)) as a part.
 * @author Georg Fischer
 */
public class A241335 extends LambdaSequence {

  /** Construct the sequence. */
  public A241335() {
    super(0, n -> (n == 0) ? Z.ONE : IntegerPartition.count(Math.toIntExact(n), p -> !PartitionUtils.isPart(p, PartitionUtils.mean(p).floor().intValueExact())));
  }
}
