package irvine.oeis.a083;
// Generated by gen_seq4.pl parm3 at 2021-05-31 21:57
// DO NOT EDIT here!

import irvine.oeis.a050.A050201;

/**
 * A083642 Starting positions of strings of three 9's in the decimal expansion of Pi.
 * @author Georg Fischer
 */
public class A083642 extends A050201 {

  /** Construct the sequence. */
  public A083642() {
    super(3, 9);
  }
}
