package irvine.oeis.a151;
// Generated by gen_seq4.pl lingf at 2020-04-15 21:52
// ogf: (1+x)/(1+x-2*x^2)
// DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A151575 G.f.: (1+x)/(1+x-2*x^2).
 * @author Georg Fischer
 */
public class A151575 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A151575() {
    super(0, "[1,1]", "[1,1,-2]");
  }
}
