package irvine.oeis.a151;
// Generated by gen_seq4.pl 2023-10-12/lambdan at 2023-10-12 23:13

import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A151904 a(n) = (3^(wt(k)+f(j))-1)/2 if n = 6k+j, 0 &lt;= j &lt; 6, where wt = A000120, f = A151899.
 * @author Georg Fischer
 */
public class A151904 extends LambdaSequence {

  /** Construct the sequence. */
  public A151904() {
    super(0, n -> Z.THREE.pow(Integer.bitCount(n / 6) + (new int[]{0, 0, 1, 1, 1, 2})[n % 6]).subtract(1).divide2());
  }
}
