package irvine.oeis.a151;
// Generated by gen_seq4.pl build/parm2 at 2022-05-28 00:05

/**
 * A151848 If A151847 is regarded as a triangle then the rows converge to this sequence.
 * @author Georg Fischer
 */
public class A151848 extends A151844 {

  /** Construct the sequence. */
  public A151848() {
    super(new A151847());
  }
}
