package irvine.oeis.a086;
// Generated by gen_seq4.pl holos [[0],[-3,3],[1,2],[-2,-1]] [0,1,1] 2 at 2020-02-15 22:07
// Recurrence: (3*n-3)*a[n+0]+(1+2*n)*a[n+1]+(-n-2)*a[n+2]=0
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A086246 Expansion of (1 + x - sqrt(1 - 2*x - 3*x^2)) / 2 in powers of x.
 * @author Georg Fischer
 */
public class A086246 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A086246() {
    super(0, "[[0],[-3,3],[1,2],[-2,-1]]", "[0,1,1]", 2);
  }
}
