package irvine.oeis.a035;
// Generated by gen_seq4.pl partcond at 2020-09-06 11:05
// DO NOT EDIT here!

/**
 * A035535 Number of partitions of n with equal number of parts congruent to each of 0 and 2 (mod 3).
 * @author Georg Fischer
 */
public class A035535 extends A035536 {

  /** Construct the sequence. */
  public A035535() {
    super(0, 3, 1, 0, -1);
  }
}
