package irvine.oeis.a035;
// Generated by gen_seq4.pl latcoors at 2020-07-22 14:21

import irvine.oeis.LatticeCoordinationSequence;


/**
 * A035775 Coordination sequence for <code>C_38</code> lattice.
 * @author Georg Fischer
 */
public class A035775 extends LatticeCoordinationSequence {

  /** Construct the sequence. */
  public A035775() {
    super("C", 38);
  }
}
