package irvine.oeis.a035;
// Generated by gen_seq4.pl latcoors at 2020-07-28 21:27

import irvine.oeis.recur.LatticeCoordinationSequence;


/**
 * A035925 Coordination sequence for diamond structure D^+_98. (Edges defined by l_1 norm = 1.).
 * @author Georg Fischer
 */
public class A035925 extends LatticeCoordinationSequence {

  /** Construct the sequence. */
  public A035925() {
    super("D^+", 98);
  }
}
