package irvine.oeis.a309;
// Generated by gen_seq4.pl 2025-10-08.ack/rpt at 2025-10-08 22:27

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A309840 If n = Sum (2^e_k) then a(n) = Product (Fibonacci(e_k + 3)).
 * @author Georg Fischer
 */
public class A309840 extends RationalProductTransform {

  /** Construct the sequence. */
  public A309840() {
    super(0, new Builder().g(k -> (Long.bitCount(k) == 1) ? Functions.FIBONACCI.z(Long.numberOfTrailingZeros(k) + 3).negate() : Z.ZERO).f(-1));
  }
}
