package irvine.oeis.a309;
// Generated by gen_seq4.pl wparts/wpartsum at 2025-03-11 22:45

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A309519 Sum of the even parts in the partitions of n into 4 parts.
 * @author Georg Fischer
 */
public class A309519 extends LambdaSequence {

  /** Construct the sequence. */
  public A309519() {
    super(0, n -> Integers.SINGLETON.sum(1, n / 4, k -> Integers.SINGLETON.sum(k, (n - k) / 3, j -> Integers.SINGLETON.sum(j, (n - j - k) / 2, i -> Z.valueOf((i * ((i - 1) & 1) + j * ((j - 1) & 1) + k * ((k - 1) & 1) + (n - i - j - k) * ((n - i - j - k - 1) & 1)))))));
  }
}
