package irvine.oeis.a309;
// Generated by gen_seq4.pl holos [0,1,-2,3,-4,3,-2,-1,4,-6,8,-6,4,-1,-2,3,-4,3,-2,1] [0,0,0,0,0,2,4,4,4,8,12,16,20,26,32,38,44,58] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A309690 Sum of the even parts appearing among the second largest parts of the partitions of n into 3 parts.
 * @author Georg Fischer
 */
public class A309690 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A309690() {
    super(1, "[0,1,-2,3,-4,3,-2,-1,4,-6,8,-6,4,-1,-2,3,-4,3,-2,1]", "[0,0,0,0,0,2,4,4,4,8,12,16,20,26,32,38,44,58]", 0);
  }
}
