package irvine.oeis.a237;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A237011 Number of (n+1)X(4+1) 0..3 arrays with the sum of all four elements of every 2X2 subblock equal.
 * @author Georg Fischer
 */
public class A237011 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A237011() {
    super(1, "[0,165888,-262656,-131328,369216,-24192,-196896,52752,49756,-20048,-5824,3388,189,-268,16,8,-1]", "5984,10776,20776,46416,108824,282048,755752,2169408,6387224,19785696,62577256,205965696,689940824,2386495968,8375807272", 0, 0);
  }
}
