package irvine.oeis.a237;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A237958 Number of (n+1)X(1+1) 0..2 arrays with the maximum plus the lower median minus the minimum of every 2X2 subblock differing from its horizontal and vertical neighbors by exactly one.
 * @author Georg Fischer
 */
public class A237958 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A237958() {
    super(1, "[0,1024,0,3968,0,4288,0,1692,0,216,0,0,0,-1]", "81,340,1422,6042,25777,109200,462852,1962464,8337456,35340888,150013756,635934272", 0, 0);
  }
}
