package irvine.oeis.a208;
// Generated by gen_seq4.pl eulerxfm 1 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A208385 Expansion of <code>b(q) * c(q) * c(q^2) / 9</code> in powers of q where <code>b(), c()</code> are cubic AGM theta functions.
 * @author Georg Fischer
 */
public class A208385 extends EulerTransform {

  /** Construct the sequence. */
  public A208385() {
    super(new PeriodicSequence(-2, -1, -4, -1, -2, -6), 1);
  }
}
