package irvine.oeis.a208;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A208197 Number of nX4 0..3 arrays with new values 0..3 introduced in row major order and no element equal to more than two of its immediate leftward or upward or left-upward diagonal neighbors.
 * @author Georg Fischer
 */
public class A208197 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A208197() {
    super(1, "[0,0,-373248,2138400,-1895184,-2516274,1791667,811712,-310734,-37526,2368,236,-1]", "15,2653,639701,156617480,38372808893,9402035642924,2303673397508915,564442821781056268,138298988287411669755,33885824084409470445384,8302657077306720410135797", 0, 0);
  }
}
