package irvine.oeis.a208;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A208080 Number of 5 X n 0..1 arrays avoiding 0 0 0 and 0 0 1 horizontally and 0 0 0 and 0 1 0 vertically.
 * @author Georg Fischer
 */
public class A208080 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A208080() {
    super(1, "[0,15,165,285,-435,-405,405,-15,-15]", "[1,-4,-40,-24,70,28,-36,0,1]");
  }
}
