package irvine.oeis.a208;
// Generated by gen_seq4.pl eulerper 0 8 2, 3, 2, -2, 2, 3, 2, 0 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A208850 Expansion of <code>phi(q^2) / phi(-q)</code> in powers of q where <code>phi()</code> is a Ramanujan theta function.
 * @author Georg Fischer
 */
public class A208850 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A208850() {
    super(new PeriodicSequence(2, 3, 2, -2, 2, 3, 2, 0), 0);
  }
}
