package irvine.oeis.a208;
// Generated by gen_seq4.pl etaprod/etaproq at 2023-01-26 23:27

import irvine.oeis.transform.EtaProductSequence;

/**
 * A208589 Expansion of phi(x) / psi(x^4) in powers of x where phi(), psi() are Ramanujan theta functions.
 * Eta product <code>eta(q^2)^5/eta(q)^2/eta(q^4)/eta(q^8)^2</code>
 * @author Georg Fischer
 */
public class A208589 extends EtaProductSequence {

  /** Construct the sequence. */
  public A208589() {
    super(0, "[2,5;8,-2;4,-1;1,-2]", "1/2");
  }
}
