package irvine.oeis.a208;
// Generated by gen_seq4.pl joinlr 0 0 new long[] {51L, -55L, 15L} new long[] {4L, 34L, 322L} new long[] {1L} at 2019-07-26 00:04

import irvine.oeis.LinearRecurrence;

/**
 * A208215 Number of ways of dividing a 3 X n rectangle into rectangles of integer side lengths.
 * @author Georg Fischer
 */
public class A208215 extends LinearRecurrence {

  /** Construct the sequence. */
  public A208215() {
    super(new long[] {51L, -55L, 15L}, new long[] {4L, 34L, 322L}, 1L);
  }
}
