package irvine.oeis.a208;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A208867 Number of n X 3 0..3 arrays with new values 0..3 introduced in row major order and no element equal to more than one of its immediate leftward or upward or right-upward antidiagonal neighbors.
 * @author Georg Fischer
 */
public class A208867 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A208867() {
    super(1, "[0,5,-139,345,-267,54]", "[1,-55,261,-369,162]");
  }
}
