package irvine.oeis.a275;
// Generated by gen_seq4.pl dfinite/holos at 2022-07-29 23:34

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A275448 The number of weakly alternating bargraphs of semiperimeter n. A bargraph is said to be weakly alternating if its ascents and descents alternate. An ascent (descent) is a maximal sequence of consecutive U (D) steps.
 * @author Georg Fischer
 */
public class A275448 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A275448() {
    super(2, "[[0],[-26, 4],[111,-21],[-162, 39],[107,-37],[-33, 21],[2,-7],[1, 1]]", "1, 2, 3, 4, 6, 12, 28", 0);
  }
}
