package irvine.oeis.a275;
// Generated by gen_seq4.pl 2025-07-17.ack/polya at 2025-07-18 00:03

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a001.A001349;

/**
 * A275165 Number of n-node graphs with two connected components.
 * new A001349()
 * @author Georg Fischer
 */
public class A275165 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A275165() {
    super(0, "[0,0,1],[0,0,1]", "x,B,^2,p1,B,+,2,/", 0, 0, 1, 1, new A001349());
  }
}
