package irvine.oeis.a275;
// Generated by gen_seq4.pl eulerper 0 8 -1, -7, -1, -2, -1, -7, -1, -4 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A275372 Expansion of <code>f(-x) * f(-x^2)^4 / phi(x^2)</code> in powers of x where <code>phi(), f()</code> are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A275372 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A275372() {
    super(new PeriodicSequence(-1, -7, -1, -2, -1, -7, -1, -4), 0);
  }
}
