package irvine.oeis.a252;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A252817 Number of n X 5 nonnegative integer arrays with upper left 0 and every value within 2 of its city block distance from the upper left and every value increasing by 0 or 1 with every step right or down.
 * @author Georg Fischer
 */
public class A252817 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A252817() {
    super(1, new long[] {0, 11, -40, 182, -430, 711, -822, 657, -360, 131, -29, 3},
      new long[] {1, -11, 55, -165, 330, -462, 462, -330, 165, -55, 11, -1});
  }
}
