package irvine.oeis.a252;
// Generated by gen_seq4.pl 2025-11-19.ack/filnum at 2025-11-19 18:53

import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A252661 Numbers m such that 8^m - m is a semiprime.
 * @author Georg Fischer
 */
public class A252661 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A252661() {
    super(1, 0, k -> Predicates.SEMIPRIME.is(Z.EIGHT.pow(k).subtract(Z.valueOf(k))));
  }
}
