package irvine.oeis.a252;
// Generated by gen_seq4.pl 2026-03-09.ack/lambdan at 2026-03-09 19:30

import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a003.A003961;
import irvine.oeis.a005.A005940;

/**
 * A252750 a(n) = A003961(A005940(n+1)) - 2 * A005940(n+1).
 * @author Georg Fischer
 */
public class A252750 extends LambdaSequence {

  private static final DirectSequence A003961 = new A003961();
  private static final DirectSequence A005940 = new A005940();

  /** Construct the sequence. */
  public A252750() {
    super(0, n -> {
      final Z dn = A005940.a(n + 1);
      return A003961.a(dn).subtract(dn.multiply(2));
    });
  }
}
