package irvine.oeis.a335;
// Generated by gen_seq4.pl holos at 2020-10-26 23:20
// 8: 8
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;


/**
 * A335639 Sum of the positive differences of the cubed parts in each partition of n into two parts.
 * @author Georg Fischer
 */
public class A335639 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A335639() {
    super(1, "[[0],[1],[-2],[-2],[6],[0],[-6],[2],[2],[-1]]", "[0, 0, 7, 26, 82, 180, 369, 648]", 0);
  }
}
