package irvine.oeis.a330;
// Generated by gen_seq4.pl finifull at 2020-01-25 12:34

import irvine.oeis.FiniteSequence;

/**
 * A330565 The thirteen entries from A005848 for which the integers of the cyclotomic field form a Euclidean ring with respect to the norm.
 * @author Georg Fischer
 */
public class A330565 extends FiniteSequence {

  /** Construct the sequence. */
  public A330565() {
    super(1, FINITE, 1, 3, 4, 5, 7, 8, 9, 11, 12, 15);
  }
}
