package irvine.oeis.a348;
// Generated by gen_seq4.pl 2023-09-29/gcd3an at 2023-10-03 20:19

import irvine.math.q.Q;
import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a000.A000203;
import irvine.oeis.a003.A003959;

/**
 * A348049 a(n) = A003959(n) / gcd(sigma(n), A003959(n)), where A003959 is multiplicative with a(p^e) = (p+1)^e and sigma is the sum of divisors function.
 * @author Georg Fischer
 */
public class A348049 extends AbstractSequence {

  private final AbstractSequence mSeq1 = new A003959();
  private final AbstractSequence mSeq2 = new A000203();

  /** Construct the sequence. */
  public A348049() {
    super(1);
  }

  @Override
  public Z next() {
    return new Q(mSeq1.next(), mSeq2.next()).num();
  }
}

