package irvine.oeis.a348;
// Generated by gen_seq4.pl 2023-09-29/gcd2an at 2023-10-03 20:19

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a003.A003415;
import irvine.oeis.a347.A347130;

/**
 * A348497 a(n) = gcd(A003415(n), A347130(n)), where A003415 is the arithmetic derivative and A347130 is its Dirichlet convolution with the identity function.
 * @author Georg Fischer
 */
public class A348497 extends AbstractSequence {

  private final AbstractSequence mSeq1 = new A003415().skip(1);
  private final AbstractSequence mSeq2 = new A347130();

  /** Construct the sequence. */
  public A348497() {
    super(1);
  }

  @Override
  public Z next() {
    return mSeq1.next().gcd(mSeq2.next());
  }
}

