package irvine.oeis.a399;
// Generated by gen_seq4.pl 2026-09-06.ack/period at 2026-09-06 21: 22

import irvine.oeis.recur.PeriodicSequence;

/**
 * A399180 Period 7: repeat 0,1,2,1,2,1,0.
 * @author Georg Fischer
 */
public class A399180 extends PeriodicSequence {

  /** Construct the sequence. */
  public A399180() {
    super(0, "0,1,2,1,2,1,0");
  }
}
