package irvine.oeis.a155;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A155195 a(n)=6*a(n-1)+a(n-2), n&gt;2 ; a(0)=1, a(1)=5, a(2)=30 .
 * @author Georg Fischer
 */
public class A155195 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A155195() {
    super(0, new long[] {1, -1, -1},
      new long[] {1, -6, -1});
  }
}
