package irvine.oeis.a155;
// Generated by gen_seq4.pl 2026-06-02.ack/filter at 2026-06-02 22:17

import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A155006 Primes p such that (p-2)*(p+2)-+2*p are primes.
 * @author Georg Fischer
 */
public class A155006 extends FilterSequence {

  /** Construct the sequence. */
  public A155006() {
    super(1, new A000040(), p -> {
      final long d = 2;
      final Z q = p.multiply(d);
      return Predicates.PRIME.is(p.subtract(d).multiply(p.add(d)).subtract(q)) && Predicates.PRIME.is(p.subtract(d).multiply(p.add(d)).add(q));
    });
  }
}
