package irvine.oeis.a201;
// Generated by gen_seq4.pl simgcd at 2023-08-12 22:14

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a349.A349562;

/**
 * A201595 E.g.f. satisfies A(x) = exp(x*A(x)) * cosh(x*A(x)).
 * @author Georg Fischer
 */
public class A201595 extends AbstractSequence {

  private final AbstractSequence mSeq = new A349562();

  /** Construct the sequence. */
  public A201595() {
    super(0);
  }

  @Override
  public Z next() {
    return mSeq.next().add(1).divide2();
  }
}
