package irvine.oeis.a201;
// Generated by gen_seq4.pl decsolvn at 2021-08-03 20:49

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A201897 Decimal expansion of the least x satisfying x^2+3x+1=e^x.
 * Equation; x^2+3*x+2-exp(x)
 * @author Georg Fischer
 */
public class A201897 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A201897() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return x.pow(2).add(CR.THREE.multiply(x)).add(CR.TWO).subtract(x.exp());
      }
    }.inverseMonotone(CR.valueOf(-2.151), CR.valueOf(-2.067)).execute(CR.ZERO).negate());
  }
}
