package irvine.oeis.a179;
// Generated by gen_seq4.pl nest at 2020-12-29 12:34
// DO NOT EDIT here!

import irvine.oeis.NestedSequence;
import irvine.oeis.a000.A000120;
import irvine.oeis.a010.A010873;


/**
 * A179868 (Number of 1's in the binary expansion of n) mod 4.
 * Formula: <code>a(n) = A010873(A000120(n)).</code>
 * @author Georg Fischer
 */
public class A179868 extends NestedSequence {

  /** Construct the sequence. */
  public A179868() {
    super(0, new A010873(), new A000120(), 0, 0); 
  }

}
