package irvine.oeis.a182;
// Generated by gen_seq4.pl decexp at 2021-07-13 19:05

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A182545 Decimal expansion of | log_phi(gamma) |, where phi is the golden ratio and gamma is the Euler-Mascheroni constant.
 * @author Georg Fischer
 */
public class A182545 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A182545() {
    super(1, CR.GAMMA.log().divide(CR.PHI.log()).abs());
  }
}
