package irvine.oeis.a182;
// Generated by gen_seq4.pl mult at 2022-07-21 21:19

import irvine.math.z.Z;
import irvine.oeis.MultiplicativeSequence;

/**
 * A182039 Order of the group O(2,Z_n); number of orthogonal 2 X 2 matrices over the ring Z/nZ.
 * @author Georg Fischer
 */
public class A182039 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A182039() {
    super(1, (p, e) -> p.equals(Z.TWO) ? (e == 1 ? Z.TWO : (e == 2 ? Z.valueOf(16) : Z.ONE.shiftLeft(e + 3))) : (p.mod(Z.FOUR).equals(Z.ONE) ? p.subtract(1).multiply2().multiply(p.pow(e - 1)) : p.add(1).multiply2().multiply(p.pow(e - 1))));
  }
}
