package irvine.oeis.a182;
// Generated by gen_seq4.pl trimirr/trimirror at 2023-07-30 08:27

import irvine.oeis.a077.A077264;
import irvine.oeis.triangle.Transpose;

/**
 * A182630 T(n,k) = A002024(k+1)*n + A002262(k), n &gt;= 0, k &gt;= 0, read by antidiagonals.
 * @author Georg Fischer
 */
public class A182630 extends Transpose {

  /** Construct the sequence. */
  public A182630() {
    super(new A077264());
  }
}
