package irvine.oeis.a383;
// Generated by gen_seq4.pl 2025-06-01.ack/sintrif at 2025-06-01 21:15

import irvine.oeis.DirectSequence;
import irvine.oeis.a209.A209229;
import irvine.oeis.a306.A306156;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A383034 Inverse Weigh transform of 2^(n-1).
 * @author Georg Fischer
 */
public class A383034 extends SingleTransformSequence {

  private static final DirectSequence A209229 = new A209229();

  /** Construct the sequence. */
  public A383034() {
    super(1, (term, n) -> term.subtract(A209229.a(n)), "", new A306156());
  }
}
