package irvine.oeis.a383;
// Generated by gen_seq4.pl 2025-04-20.ack/lambdan at 2025-04-20 22:06

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A383136 a(n) = Sum_{k=0..n} k^2 * 2^(n-k) * binomial(n,k).
 * @author Georg Fischer
 */
public class A383136 extends LambdaSequence {

  /** Construct the sequence. */
  public A383136() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Z.valueOf(k).square().multiply(Z.TWO.pow(n - k)).multiply(Binomial.binomial(n, k))));
  }
}
