package irvine.oeis.a383;
// Generated by gen_seq4.pl 2025-04-30.ack/holos at 2025-04-30 23:37

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A383382 Expansion of e.g.f. exp(-3*x) / (1-x)^5.
 * a(0) = 1, a(1) = 2; a(n) = (n+1)*a(n-1) + 3*(n-1)*a(n-2).
 * @author Georg Fischer
 */
public class A383382 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A383382() {
    super(0, "[[0],[-3, 3],[1, 1],[-1]]", "1, 2", 0, 0);
  }
}
