package irvine.oeis.a206;
// generated by patch_offset.pl at 2022-08-16 19:10

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A206839 Number of 1 X n 0..3 arrays avoiding the pattern z-2 z-1 z in any row, column, nw-to-se diagonal or ne-to-sw antidiagonal.
 * @author Georg Fischer
 */
public class A206839 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A206839() {
    super(0, "[[0],[-1],[2],[0],[-4],[1]]", "[1, 4, 16, 62, 241]", 0);
  }
}
