package irvine.oeis.a323;
// Generated by gen_seq4.pl dirichinv at 2021-04-20 22:30
// DO NOT EDIT here!

import irvine.oeis.DirichletInverseSequence;
import irvine.oeis.a001.A001615;

/**
 * A323363 Dirichlet inverse of Dedekind's psi, A001615.
 * @author Georg Fischer
 */
public class A323363 extends DirichletInverseSequence {

  /** Construct the sequence. */
  public A323363() {
    super(new A001615());
  }
}
