package irvine.oeis.a078;

import java.util.ArrayList;

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.Sequence1;
import irvine.oeis.transform.BellMatrixTransformSequence;

/**
 * A078521 Signed triangle of D'Arcais numbers (A008298) : coefficients of r in the polynomials generated by the series coefficients of z^n in Product[(1-z^k)^r, {k,1,Inf}]*(n!).
 * @author Sean A. Irvine
 */
public class A078521 extends Sequence1 {

  private BellMatrixTransformSequence mT = null;
  private final ArrayList<Z> mA = new ArrayList<>();
  private int mN = -1;
  private int mM = 0;

  @Override
  public Z next() {
    if (++mM > mN) {
      ++mN;
      mM = 0;
      mA.add(Functions.FACTORIAL.z(mN).multiply(Functions.SIGMA1.z(mN + 1)).negate());
      mT = new BellMatrixTransformSequence(mA);
    }
    return mT.get(mN, mM);
  }
}

