package irvine.oeis.a269;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A269202 Number of <code>2 X n 0..3</code> arrays with some element plus some horizontally, diagonally or antidiagonally adjacent neighbor totalling three no more than once.
 * @author Georg Fischer
 */
public class A269202 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A269202() {
    super(1, new long[] {0, 16, 20, -308, 72},
      new long[] {1, -10, 13, 60, 36});
  }
}
