package irvine.oeis.a269;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A269105 Number of nX4 0..3 arrays with some element plus some horizontally or vertically adjacent neighbor totalling three no more than once.
 * @author Georg Fischer
 */
public class A269105 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A269105() {
    super(1, "[0,0,-69169,140442,-94959,24556,-2559,90,-1]", "216,15540,872460,43964700,2085484068,95166487524,4227147007836", 0, 0);
  }
}
