package irvine.oeis.a269;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A269536 Number of length-n 0..7 arrays with no repeated value differing from the previous repeated value by other than one.
 * @author Georg Fischer
 */
public class A269536 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A269536() {
    super(1, "[0,18088,59366,59449,7883,-13188,-870,1651,-355,31,-1]", "8,64,504,3934,30464,234358,1792788,13648124,103462888", 0, 0);
  }
}
