package irvine.oeis.a213;
// Generated by gen_seq4.pl A213500/parm3 at 2022-05-01 00:29

import irvine.oeis.PrependSequence;
import irvine.oeis.a004.A004767;
import irvine.oeis.a005.A005408;

/**
 * A213844 Rectangular array:  (row n) = b**c, where b(h) = 2*h-1, c(h) = 4*n-5+4*h, n&gt;=1, h&gt;=1, and ** = convolution.
 * @author Georg Fischer
 */
public class A213844 extends A213500 {

  /** Construct the sequence. */
  public A213844() {
    super(new PrependSequence(new A005408(), 0), new PrependSequence(new A004767(), 0));
  }
}
