package irvine.oeis.a213;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A213222 Minimum number of distinct slopes formed by n noncollinear points in the plane.
 * @author Georg Fischer
 */
public class A213222 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A213222() {
    super(3, new long[] {0, 0, 0, 3, 1, -3, 1},
      new long[] {1, -1, -1, 1});
  }
}
