package irvine.oeis.a213;
// Generated by gen_seq4.pl A212846/parm3 at 2022-01-21 22:12

import irvine.oeis.a212.A212846;

/**
 * A213130 Polylogarithm li(-n,-1/7) multiplied by (8^(n+1))/7.
 * @author Georg Fischer
 */
public class A213130 extends A212846 {

  /** Construct the sequence. */
  public A213130() {
    super(1, 7);
  }
}
