package irvine.oeis.a314;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a310.A310352;

/**
 * A314870 Coordination sequence Gal.6.358.2 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A314870 extends A310352 {

  /** Construct the sequence. */
  public A314870() {
    super();
    defineBaseSet(1);
  }
}
