package irvine.oeis.a314;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a310.A310296;

/**
 * A314338 Coordination sequence Gal.6.52.4 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A314338 extends A310296 {

  /** Construct the sequence. */
  public A314338() {
    super();
    defineBaseSet(3);
  }
}
