package irvine.oeis.a180;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A180310 Decimal expansion of Pi/2 - 4/Pi.
 * @author Georg Fischer
 */
public class A180310 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A180310() {
    super(0, CR.FOUR.divide(CR.PI).negate().add(CR.PI.divide(CR.TWO)));
  }
}
