package irvine.oeis.a180;
// Generated by gen_seq4.pl 2026-02-01.ack/polya at 2026-02-01 21:48

import irvine.oeis.PolynomialFieldSequence;

/**
 * A180606 G.f.: A(x) = exp( Sum_{n&gt;=1} (2^n-1)^(n-1)*x^n/n ).
 * new A180602()
 * @author Georg Fischer
 */
public class A180606 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A180606() {
    super(0, "[1]", "x,B,<1,/n,exp", 0, 0, 1, 1, new A180602());
  }
}
