package irvine.oeis.a180;
// Generated by gen_seq4.pl 2026-05-21.ack/polyxa at 2026-05-21 21:44

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a152.A152917;

/**
 * A180749 G.f.: A(x) = x/Series_Reversion(x*G(x)) where G(x) = Sum_{n&gt;=0} (n+1)^n*x^n.
 * new A152917()
 * @author Georg Fischer
 */
public class A180749 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A180749() {
    super(0, "[1]", "x,x,B,rev,/", 1, 0, 1, 1, new A152917());
  }
}
