package irvine.oeis.a325;
// Generated by gen_seq4.pl holos at 2021-08-16 19:34

import irvine.oeis.recur.HolonomicRecurrence;
/**
 * A325260 Number of integer partitions of n whose omega-sequence covers an initial interval of positive integers.
 * radtorec((-x^9-x^8-x^7+x^6-x^5-x^2-x-1)/(x-1)^3/(1+x)^2/(x^2+1)/(x^2+x+1))
 * @author Georg Fischer
 */
public class A325260 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A325260() {
    super(0, "[[0],[-15, 1],[-27, 2],[-34, 3],[-5, 1],[21],[43,-2],[45,-2],[19],[16, 1],[7, 3],[24, 1],[20],[16,-2],[11,-3],[3,-2],[0,-1]]", "[1, 1, 2, 2, 4, 5, 5, 8, 10, 12, 13, 18, 19, 24, 25, 31, 33, 40]", 0);
  }
}
