package irvine.oeis.a088;
// Generated by gen_seq4.pl 2024-07-27.ack/lambdin at 2024-07-27 22:17

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a000.A000699;
import irvine.oeis.memory.MemorySequence;

/**
 * A088221 Coefficient of x^n in g.f.^n is A000698(n+1).
 * @author Georg Fischer
 */
public class A088221 extends LambdaSequence {

  private static final MemorySequence A000699 = new A000699();

  /** Construct the sequence. */
  public A088221() {
    super(0, n -> Integers.SINGLETON.sum(1, n - 1, j -> Z.valueOf(4 * j - 1).multiply(A000699.a(j)).multiply(A000699.a(n - j))), "1, 2");
  }
}
