package irvine.oeis.a229;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A229582 Number of defective 3-colorings of an <code>n X 4 0..2</code> array connected horizontally and antidiagonally with exactly one mistake, and colors introduced in <code>row-major 0..2</code> order.
 * @author Georg Fischer
 */
public class A229582 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A229582() {
    super(1, new long[] {0, 6, 8, 18},
      new long[] {1, -18, 81});
  }
}
