package irvine.oeis.a371;
// Generated by gen_seq4.pl 2024-04-05/lambdan at 2024-04-05 23:22

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A371658 G.f. satisfies A(x) = 1 + x * A(x)^2 * (1 + A(x))^2.
 * @author Georg Fischer
 */
public class A371658 extends LambdaSequence {

  /** Construct the sequence. */
  public A371658() {
    super(0, n -> n == 0 ? Z.ONE : Integers.SINGLETON.sum(0, (n - 1) / 2, k -> Z.FOUR.pow(n - k).multiply(Binomial.binomial(n, k)).multiply(Binomial.binomial(3L * n - k, n - 1 - 2L * k))).divide(n));
  }
}
