package irvine.oeis.a371;
// Generated by gen_seq4.pl 2025-09-04.ack/polyxa at 2025-09-04 22:46

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a005.A005651;

/**
 * A371485 Expansion of e.g.f. Product_{k&gt;=2} 1 / (1 - x^k/k!).
 * egf(new A005651())
 * @author Georg Fischer
 */
public class A371485 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A371485() {
    super(0, "[1],[1,-1]", "x,B,p1,*", 0, 1, 1, 1, egf(new A005651()));
  }
}
