package irvine.oeis.a198;
// Generated by gen_seq4.pl 2026-07-12.ack/deldel at 2026-07-12 23:53

import irvine.oeis.a079.A079978;
import irvine.oeis.a102.A102283;
import irvine.oeis.transform.DelehamDeltaSequence;

/**
 * A198379 Triangle T(n,k), read by rows, given by (0,1,-1,0,1,-1,0,1,-1,0,1,-1,...) DELTA (1,0,0,1,0,0,1,0,0,1,0,0,1,...) where DELTA is the operator defined in A084938.
 * where DELTA is the operator defined in J084938.
 * @author Georg Fischer
 */
public class A198379 extends DelehamDeltaSequence {


  /** Construct the sequence. */
  public A198379() {
    super(0, new A102283(), new A079978());
  }

}
