package irvine.oeis.a198;
// Generated by gen_seq4.pl trigf 1, -1, -1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 1, -1, -2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 at 2020-02-18 21:32
// 0
// 
// DO NOT EDIT here!

import irvine.oeis.triangle.GeneratingFunctionTriangle;

/**
 * A198321 Triangle read by rows: T(n, k) = binomial(n, k-1) for 1 &lt;= k &lt;= n, and T(n, 0) = 0^n.
 * @author Georg Fischer
 */
public class A198321 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A198321() {
    super(0, new long[] {1, -1, -1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0}, new long[] {1, -1, -2, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0});
  }
}
