package irvine.oeis.a198;
// Generated by gen_seq4.pl decsolv at 2021-07-31 13:37

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A198354 Decimal expansion of greatest x having 4*x^2+x=3*cos(x).
 * Equation; 4*x^2+x-(3*cos(x))
 * @author Georg Fischer
 */
public class A198354 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A198354() {
    super(0, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return CR.FOUR.multiply(x.square()).add(x).subtract(CR.THREE.multiply(x.cos()));
      }
    }.inverseMonotone(CR.valueOf(0.643), CR.valueOf(0.669)).execute(CR.ZERO));
  }
}
