package irvine.oeis.a198;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A198508 Number of 2n X 2 0..4 arrays with values 0..4 introduced in row major order and each element unequal to exactly two horizontal and vertical neighbors.
 * @author Georg Fischer
 */
public class A198508 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A198508() {
    super(1, "[0,4,-145,1381,-4496,4096]", "[1,-51,691,-3601,7056,-4096]");
  }
}
