package irvine.oeis.a198;
// Generated by gen_seq4.pl decsolv at 2021-07-31 13:37

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A198223 Decimal expansion of greatest x having 3*x^2+2x=cos(x).
 * Equation; 3*x^2+2x-(cos(x))
 * @author Georg Fischer
 */
public class A198223 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A198223() {
    super(0, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return CR.THREE.multiply(x.pow(2)).add(CR.TWO.multiply(x)).subtract(x.cos());
      }
    }.inverseMonotone(CR.valueOf(0.314), CR.valueOf(0.327)).execute(CR.ZERO));
  }
}
