package irvine.oeis.a198;
// Generated by gen_seq4.pl decsolv at 2021-08-09 22:50

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A198364 Decimal expansion of greatest x having 4*x^2+3x=2*cos(x).
 * Equation; 4*x^2+3*x-(2*cos(x))
 * @author Georg Fischer
 */
public class A198364 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A198364() {
    super(0, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return CR.FOUR.multiply(x.pow(2)).add(CR.THREE.multiply(x)).subtract(CR.TWO.multiply(x.cos()));
      }
    }.inverseMonotone(CR.valueOf(0.392), CR.valueOf(0.408)).execute(CR.ZERO));
  }
}
