package irvine.oeis.a153;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A153805 Decimal expansion of 3-e.
 * @author Georg Fischer
 */
public class A153805 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A153805() {
    super(0, CR.THREE.subtract(CR.E));
  }
}
