package irvine.oeis.a153;
// Generated by gen_seq4.pl 2026-10-08.ack/lambdan at 2026-10-08 

import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a139.A139250;

/**
 * A153003 Toothpick sequence in the first three quadrants.
 * @author Georg Fischer
 */
public class A153003 extends LambdaSequence {

  private static final DirectSequence A139250 = new A139250();

  /** Construct the sequence. */
  public A153003() {
    super(0, n -> n == 0 ? Z.ZERO : A139250.a(n + 1).subtract(3).multiply(3).divide(4).add(1));
  }
}
