package irvine.oeis.a153;
// Generated by gen_seq4.pl 2026-06-06.ack/prepend at 2026-06-06 23:53

import irvine.oeis.PrependSequence;
import irvine.oeis.a006.A006752;
import irvine.oeis.cons.ContinuedFractionNumeratorSequence;

/**
 * A153069 Numerators of the convergents of the continued fraction for Catalan&apos;s constant L(2, chi4), where L(s, chi4) is the Dirichlet L-function for the non-principal character modulo 4.
 * @author Georg Fischer
 */
public class A153069 extends PrependSequence {

  /** Construct the sequence. */
  public A153069() {
    super(-2, new ContinuedFractionNumeratorSequence(0, new A006752()), 0, 1);
  }
}
