package irvine.oeis.a153;
// Generated by gen_seq4.pl 2023-12-03/tuptraf at 2023-12-03 21:34

import irvine.oeis.transform.TupleTransformSequence;

/**
 * A153062 a(0)=1, a(n)=a(n-1)^2-n^2.
 * @author Georg Fischer
 */
public class A153062 extends TupleTransformSequence {

  /** Construct the sequence. */
  public A153062() {
    super(0, (n, s) -> s[0].square().subtract((long) n * n), "1", PREVIOUS);
  }
}
