package irvine.oeis.a095;
// Generated by gen_seq4.pl primof at 2021-01-16 00:20
// DO NOT EDIT here!

import irvine.oeis.PrimeSubsequence;


/**
 * A095995 Primes of the form 100n - 1.
 * @author Georg Fischer
 */
public class A095995 extends PrimeSubsequence {

  /** Construct the sequence */
  public A095995() {
    super("[[100],[1],[-1]]", "[-1]", 0);
  }
}
