package irvine.oeis.a095;
// Generated by gen_seq4.pl padding 1 at 2020-08-22 18:36
// DO NOT EDIT here!

import irvine.oeis.recur.PaddingSequence;


/**
 * A095049 Number of distinct digits needed to write in decimal representation all positive non-divisors of n that are less than n.
 * @author Georg Fischer
 */
public class A095049 extends PaddingSequence {

  /** Construct the sequence. */
  public A095049() {
    super(new long[] {0, 0, 1, 1, 3, 2, 5, 4, 6, 6, 10, 6, 10, 9, 9, 9, 10, 9, 10, 9}, new long[] {10});
  }
}
