package irvine.oeis.a095;
// Generated by gen_seq4.pl finifull at 2020-01-25 12:34
// DO NOT EDIT here!

import irvine.oeis.FiniteSequence;
import irvine.math.z.Z;

/**
 * A095443 a(n) = 25 written in base 12 - n.
 * @author Georg Fischer
 */
public class A095443 extends FiniteSequence {

  /** Construct the sequence. */
  public A095443() {
    super(new Z("21"), new Z("23"), new Z("25"), new Z("27"), new Z("31"), new Z("34"), new Z("41"), new Z("100"), new Z("121"), new Z("221"), new Z("11001"), new Z("1111111111111111111111111"));
  }
}
