package irvine.oeis.a095;
// Generated by gen_seq4.pl finifull at 2020-01-25 12:34
// DO NOT EDIT here!

import irvine.oeis.FiniteSequence;
import irvine.math.z.Z;

/**
 * A095569 a(n) = 88 written in base 12 - n.
 * @author Georg Fischer
 */
public class A095569 extends FiniteSequence {

  /** Construct the sequence. */
  public A095569() {
    super(new Z("74"), new Z("80"), new Z("88"), new Z("107"), new Z("130"), new Z("154"), new Z("224"), new Z("323"), new Z("1120"), new Z("10021"), new Z("1011000"), new Z("1111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"));
  }
}
