package irvine.oeis.a095;
// Generated by gen_seq4.pl finifull at 2020-01-25 12:34
// DO NOT EDIT here!

import irvine.oeis.FiniteSequence;
import irvine.math.z.Z;

/**
 * A095541 <code>a(n) = 74</code> written in base <code>14 - n</code>.
 * @author Georg Fischer
 */
public class A095541 extends FiniteSequence {

  /** Construct the sequence. */
  public A095541() {
    super(new Z("54"), new Z("59"), new Z("62"), new Z("68"), new Z("74"), new Z("82"), new Z("112"), new Z("134"), new Z("202"), new Z("244"), new Z("1022"), new Z("2202"), new Z("1001010"), new Z("11111111111111111111111111111111111111111111111111111111111111111111111111"));
  }
}
