package irvine.oeis.a400;
// Generated by gen_seq4.pl 2026-09-25.ack/poly at 2026-09-25 21: 54

import irvine.oeis.PolynomialFieldSequence;

/**
 * A400273 G.f. A(x) satisfies A(x) = (1 + x) * A(x^4 * (1 + x)^3), with A(0) = 1.
 * @author Georg Fischer
 */
public class A400273 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A400273() {
    super(0, "[1],[1,1]", "p1,p1,^3,<4,sub,*");
  }
}
