package irvine.oeis.a329;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a007.A007953;

/**
 * A329562 a(n) = 2^(sum of digits of n).
 * @author Georg Fischer
 */
public class A329562 implements Sequence {

  final Sequence mA007953 = new A007953();
  /** Construct the sequence. */
  public A329562() {
  }
  
  @Override
  public Z next() {
    return Z.TWO.pow(mA007953.next());
  }

}
