package irvine.oeis.a329;
// Generated by gen_seq4.pl genet/genetfg at 2022-02-20 20:24

import irvine.math.z.Z;
import irvine.oeis.a069.A069735;
import irvine.oeis.transform.GeneralizedEulerTransform;

/**
 * A329467 Expansion of Product_{i&gt;=1, j&gt;=1} (1 + x^(i*j)) * (1 + x^(2*i*j)).
 * G.f.: <code>Product_{k&gt;=1} ((1+x^k)^A069735(k))</code>
 * @author Georg Fischer
 */
public class A329467 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A329467() {
    super(0, 1);
    mSeqF = new A069735();
  }

  @Override
  protected Z[] advanceF(final long k) {
    return new Z[] {mSeqF.next().negate()};
  }

  @Override
  protected Z advanceG(final long k) {
    return Z.NEG_ONE;
  }

}
