package irvine.oeis.a215;
// Generated by gen_seq4.pl 2026-01-03.ack/trilambn at 2026-01-03 22:13

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.triangle.LambdaTriangle;

/**
 * A215080 T(n,k) = Sum_{j=0..k} (k-j)^n * binomial(n,j).
 * @author Georg Fischer
 */
public class A215080 extends LambdaTriangle {

  /** Construct the sequence. */
  public A215080() {
    super(0, 0, 0, (n, k) -> Integers.SINGLETON.sum(0, k, j -> Z.valueOf(k - j).pow(n).multiply(Binomial.binomial(n, j))));
  }
}
