package irvine.oeis.a215;
// Generated by gen_seq4.pl 2026-01-06.ack/filter at 2026-01-06 22:45

import irvine.oeis.FilterSequence;
import irvine.oeis.a015.A015937;

/**
 * A215613 Odd integers n such that 2^n == 2^12 (mod n).
 * @author Georg Fischer
 */
public class A215613 extends FilterSequence {

  /** Construct the sequence. */
  public A215613() {
    super(1, new A015937(), ODD);
  }
}
