package irvine.oeis.a215;
// Generated by gen_seq4.pl eulerxfm 1 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A215348 Expansion of q <code>* phi(q) * psi(q^8) / (phi(-q) * phi(q^4))</code> in powers of q where <code>phi(), psi()</code> are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A215348 extends EulerTransform {

  /** Construct the sequence. */
  public A215348() {
    super(new PeriodicSequence(4, -2, 4, -2, 4, -2, 4, 4, 4, -2, 4, -2, 4, -2, 4, 0), 1);
  }
}
