package irvine.oeis.a062;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.Sequence1;
import irvine.oeis.a051.A051953;

/**
 * A062830 a(n) = #{ 0 &lt;= k &lt;= n : K(n, k) = 0 } where K(n, k) is the Kronecker symbol. This is the number of integers 0 &lt;= k &lt;= n that are not coprime to n.
 * @author Georg Fischer
 */
public class A062830 extends Sequence1 {

  final Sequence mA051953 = new A051953();
  @Override
  public Z next() {
    return mA051953.next().add(Z.ONE);
  }

}
