package irvine.oeis.a062;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.prime.PrimePositionSubsequence;


/**
 * A062595 Numbers k such that 29^k - 28^k is prime.
 * @author Georg Fischer
 */
public class A062595 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A062595() {
    super("[[0],[-812],[57],[-1]]", "[0, 1]", 0);
  }
}
