package irvine.oeis.a062;
// Generated by gen_seq4.pl eulerps 0 at 2020-11-16 21:39
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A062246 McKay-Thompson series of class 27c for the Monster group.
 * Somos formula: e27c=ecalc([1, 1;9,-1}],[3, 1]);
 * @author Georg Fischer
 */
public class A062246 extends EulerTransform {

  /** Construct the sequence. */
  public A062246() {
    super(new PeriodicSequence(-1, -1, -1, -1, -1, -1, -1, -1, 0), 1);
  }
}
