package irvine.oeis.a062;
// Generated by gen_seq4.pl A062034/parm2 at 2022-03-20 22:49

/**
 * A062043 Positive numbers whose product of digits is 10 times their sum.
 * @author Georg Fischer
 */
public class A062043 extends A062034 {

  /** Construct the sequence. */
  public A062043() {
    super(10);
  }
}
