package irvine.oeis.a062;
// Generated by gen_seq4.pl A062845/parm3 at 2023-02-28 12:28

/**
 * A062920 Name?
 * @author Georg Fischer
 */
public class A062920 extends A062845 {

  /** Construct the sequence. */
  public A062920() {
    super(4, 5);
  }
}
