package irvine.oeis.a062;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A062126 Sixth column of A046741.
 * @author Georg Fischer
 */
public class A062126 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A062126() {
    super(0, new long[] {8, 66, 103, 52, 12, 2},
      new long[] {1, -6, 15, -20, 15, -6, 1});
  }
}
