package irvine.oeis.a183;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A183627 Number of (n+1) X 5 0..2 arrays with every 2 x 2 subblock summing to 4.
 * @author Georg Fischer
 */
public class A183627 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A183627() {
    super(1, new long[] {0, 309, -1407, 1458},
      new long[] {1, -6, 11, -6});
  }
}
