package irvine.oeis.a183;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A183666 Number of (n+1) X 4 0..6 arrays with every 2 X 2 subblock summing to 12.
 * @author Georg Fischer
 */
public class A183666 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A183666() {
    super(1, "[0,6951,-169883,1646297,-8030449,20565592,-25807068,12101040]", "[1,-28,322,-1960,6769,-13132,13068,-5040]");
  }
}
