package irvine.oeis.a199;
// Generated by gen_seq4.pl primeval at 2021-05-28 22:45
// DO NOT EDIT here!

import irvine.oeis.PrimeSubsequence;
import irvine.oeis.a198.A198410;

/**
 * A199192 Primes of the form 3^(2n-3)+3^(n-1)+1.
 *
 * @author Georg Fischer
 */
public class A199192 extends PrimeSubsequence {

  /** Construct the sequence. */
  public A199192() {
    super(new A198410());
  }
}
