package irvine.oeis.a199;
// Generated by gen_seq4.pl 2025-07-08.ack/polyx at 2025-07-08 21:48

import irvine.oeis.PolynomialFieldSequence;

/**
 * A199749 Numerators of Bernoulli(x)^x.
 * @author Georg Fischer
 */
public class A199749 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A199749() {
    super(0, "[1]", "x,x,exp, 1,-,/,x,pow", 1, 0);
  }
}
