package irvine.oeis.a199;
// Generated by gen_seq4.pl decsolv at 2021-08-09 22:50

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCrFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A199509 Decimal expansion of x&gt;0 satisfying 3*x^2-2*x*sin(x)=2*cos(x).
 * Equation; 3*x^2-2*x*sin(x)-(2*cos(x))
 * @author Georg Fischer
 */
public class A199509 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A199509() {
    super(0, new UnaryCrFunction() {
      @Override 
      public CR execute(final CR x) {
        return CR.THREE.multiply(x.square()).subtract(CR.TWO.multiply(x).multiply(x.sin())).subtract(CR.TWO.multiply(x.cos()));
      }
    }.inverseMonotone(CR.valueOf(0.931), CR.valueOf(0.969)).execute(CR.ZERO));
  }
}
