package irvine.oeis.a199;
// Generated by gen_seq4.pl decsolvn at 2021-08-01 19:50

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A199082 Decimal expansion of x &lt; 0 satisfying x^2 + 2*sin(x) = 2.
 * Equation; x^2+2*sin(x)-2
 * @author Georg Fischer
 */
public class A199082 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A199082() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return x.pow(2).add(CR.TWO.multiply(x.sin())).subtract(CR.TWO);
      }
    }.inverseMonotone(CR.valueOf(-2), CR.valueOf(-1.922)).execute(CR.ZERO).negate());
  }
}
