package irvine.oeis.a367;
// Generated by gen_seq4.pl 2024-03-06/lambdan at 2024-03-06 21:44

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A367137 E.g.f. satisfies A(x) = 1/(1 - log(1 + x*A(x)^3)).
 * @author Georg Fischer
 */
public class A367137 extends LambdaSequence {

  /** Construct the sequence. */
  public A367137() {
    super(0, n -> {
      return Integers.SINGLETON.sum(0, n, k -> {
        return Functions.STIRLING1.z((long) n, (long) k).multiply(Functions.FACTORIAL.z(3 * n + k));
      }).divide(Functions.FACTORIAL.z(3 * n + 1));
    });
  }
}
