package irvine.oeis.a367;
// Generated by gen_seq4.pl 2024-03-06/lambdan at 2024-03-06 21:44

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A367273 a(n) = Sum_{k=0..n} binomial(n, k)^2 * (k - n)^k.
 * @author Georg Fischer
 */
public class A367273 extends LambdaSequence {

  /** Construct the sequence. */
  public A367273() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(n, k).square().multiply(Z.valueOf(k - n).pow(k))));
  }
}
