package irvine.oeis.a367;
// Generated by gen_seq4.pl 2025-11-18.ack/holos at 2025-11-19 18:47

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A367117 Place n points in general position on each side of an equilateral triangle, and join every pair of the 3*n+3 boundary points by a chord; sequence gives number of vertices in the resulting planar graph.
 * @author Georg Fischer
 */
public class A367117 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A367117() {
    super(0, "[0,1,-5,10,-10,5,-1]", "3,12,72,282,795", 0, 0);
  }
}
