package irvine.oeis.a368;
// Generated by gen_seq4.pl 2026-08-06.ack/holos at 2026-08-06 22:25

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A368567 Number of Young tableaux of shape [n, floor(n/2)].
 * @author Georg Fischer
 */
public class A368567 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A368567() {
    super(0, "[[0],[-320376,-251091,357156,-81729],[-29526,55062,-37206,4374],[0,16536,-40804,12108],[0,5512,4864,-648]]", "1,1,2", 0, 0);
  }
}
