package irvine.oeis.a368;
// Generated by gen_seq4.pl 2026-09-07.ack/lambdan at 2026-09-07 17: 57

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a035.A035316;

/**
 * A368820 Sum of the squares less than n that do not divide n.
 * @author Georg Fischer
 */
public class A368820 extends LambdaSequence {

  private static final DirectSequence A035316 = new A035316();

  /** Construct the sequence. */
  public A368820() {
    super(1, n -> Functions.PYRAMIDAL.z(Functions.SQRT.z(n)).subtract(A035316.a(n)));
  }
}
