package irvine.oeis.a368;
// Generated by gen_seq4.pl 2024-08-09.ack/hygeo at 2024-08-10 19:00

import irvine.oeis.HypergeometricSequence;

/**
 * A368709 a(n) = hypergeom([-1 - n, -n, 1 - n], [2, 3], +2).
 * @author Georg Fischer
 */
public class A368709 extends HypergeometricSequence {

  /** Construct the sequence. */
  public A368709() {
    super(0, 3, 2, "[[-1, -1], [0, -1], [1, -1], [2], [3], [2]]");
  }
}
