package irvine.oeis.a368;
// Generated by gen_seq4.pl 2024-03-30/holos at 2024-03-30 20:29

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A368205 a(n) = 3*a(n-1) - 2*a(n-2) - a(n-3), with a(0)=1, a(1)=3 and a(2)=7.
 * @author Georg Fischer
 */
public class A368205 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A368205() {
    super(0, "[0, -1, -2, 3, -1]", "1", 0, 0);
  }
}
