package irvine.oeis.a087;
// Generated by gen_seq4.pl 2025-11-18.ack/lambdan at 2025-11-19 18:47

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A087812 Sum of MoebiusMu for numbers between n and 2n inclusive.
 * @author Georg Fischer
 */
public class A087812 extends LambdaSequence {

  /** Construct the sequence. */
  public A087812() {
    super(1, n -> Integers.SINGLETON.sum(n, 2 * n, k -> Functions.MOEBIUS.z(k)));
  }
}
