package irvine.oeis.a087;
// Generated by gen_seq4.pl 2026-07-15.ack/hofstadt at 2026-07-15 19:20

import irvine.oeis.recur.HofstadterSequence;

/**
 * A087831 a(n) = a(abs(n-a(n-1))) + a(a(abs(n-a(n-4)))) if n&gt;4, a(n) = 1 otherwise.
 * @author Georg Fischer
 */
public class A087831 extends HofstadterSequence {

  /** Construct the sequence. */
  public A087831() {
    super(0, 1, 1, 1, 1, 1);
  }

  protected int compute(final int n) {
    return a(Math.abs(n - a(n - 1))) + a(a(Math.abs(n - a(n - 4))));
  }
}
