package irvine.oeis.a087;
// Generated by gen_seq4.pl nthprimf 2020-06-14 20:25
// DO NOT EDIT here!

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.a000.A000040;

/**
 * A087486 Numbers n such that digital sum of n divides digital sum of n-th prime, p(n).
 * @author Georg Fischer
 */
public class A087486 extends A000040 {
  protected long mK = 0;
  protected Z mNP = null;

  protected boolean isOk() {
    return Functions.DIGIT_SUM.z(mNP).mod(Z.valueOf(Functions.DIGIT_SUM.l(Z.valueOf(mK)))).isZero();
  }

  @Override
  public Z next() {
    ++mK;
    mNP = super.next();
    while (!isOk()) {
      ++mK;
      mNP = super.next();
    }
    return Z.valueOf(mK);
  }
}
