package irvine.oeis.a042;
// Generated by gen_seq4.pl cfsqnum 953 at 2019-07-01 15:13
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;
import irvine.math.z.Z;

/**
 * A042844 Numerators of continued fraction convergents to <code>sqrt(953)</code>.
 * @author Georg Fischer
 */
public class A042844 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A042844() {
    super(0, 953);
  }

  @Override
  public Z next() {
    Z result = getNumerator();
    iterate();
    iterateConvergents();
    return result;
  } // next
}
