package irvine.oeis.a042;
// Generated by gen_seq4.pl cfsqnum 826 at 2019-07-01 15:13
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;
import irvine.math.z.Z;

/**
 * A042594 Numerators of continued fraction convergents to <code>sqrt(826)</code>.
 * @author Georg Fischer
 */
public class A042594 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A042594() {
    super(0, 826);
  }

  @Override
  public Z next() {
    Z result = getNumerator();
    iterate();
    iterateConvergents();
    return result;
  } // next
}
