package irvine.oeis.a305;
// Generated by gen_seq4.pl 2025-02-03.ack/lambdan at 2025-02-03 18:14

import irvine.math.function.Functions;
import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A305051 a(n) = n! * [x^n] exp(exp(x) - 1)/(1 - x)^n.
 * @author Georg Fischer
 */
public class A305051 extends LambdaSequence {

  /** Construct the sequence. */
  public A305051() {
    super(0, n -> (n <= 0) ? Z.ONE : Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(n, k).multiply(Functions.FACTORIAL.z(n + k - 1)).multiply(Functions.BELL.z(n - k))).divide(Functions.FACTORIAL.z(n - 1)));
  }
}
