package irvine.oeis.a305;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A305038 Number of n X 6 0..1 arrays with every element unequal to 0, 1, 2, 6 or 7 king-move adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A305038 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A305038() {
    super(1, "[0,0,0,0,0,0,0,3,1,3,5,1,2,-16,-29,-4,6,14,1,1,-1]", "32,13,23,61,109,362,1359,3503,9721,31745,92958,264320,801379,2396646,6995135,20759698,61886282,182695112,540411495", 0, 0);
  }
}
