package irvine.oeis.a305;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.math.z.Z;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A305204 Expansion of Product_{k&gt;=1} 1/(1 - (k*(k + 1)/2)*x^k).
 * @author Georg Fischer
 */
public class A305204 extends RationalProductTransform {

  /** Construct the sequence. */
  public A305204() {
    super(0, new Builder().g(k -> Z.valueOf(k * (k + 1) / 2)));
  }
}
