package irvine.oeis.a039;
// Generated by gen_seq4.pl basdig2 9 count1 != 0 && 3 4 at 2019-06-28 18:08
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.RunsBaseSequence;

/**
 * A039378 Numbers n such that representation in base 9 has same nonzero number of <code>3</code>'s and <code>4</code>'s.
 * @author Georg Fischer
 */
public class A039378 extends RunsBaseSequence {

  /** Construct the sequence. */
  public A039378() {
    super(1, -1);
  }

  @Override
  protected boolean isOk() {
    final int count1 =  getDigitCount(mK, 9, 3);
    return count1 != 0 && count1 == getDigitCount(mK, 9, 4);
  }

  @Override
  public Z next() {
    return getNextWithProperty();
  }
}
