package irvine.oeis.a039;
// Generated by gen_seq4.pl nest at 2020-12-29 12:34
// DO NOT EDIT here!

import irvine.oeis.NestedSequence;
import irvine.oeis.a000.A000040;
import irvine.oeis.a000.A000142;


/**
 * A039716 a(n) = prime(n)!.
 * Formula: <code>a(n) = A000142(A000040(n)).</code>
 * @author Georg Fischer
 */
public class A039716 extends NestedSequence {

  /** Construct the sequence. */
  public A039716() {
    super(1, new A000142(), new A000040(), 0, 1); 
  }

}
