package irvine.oeis.a340;
// Generated by gen_seq4.pl build/trionk

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a337.A337165;

/**
 * A340947 Number of ways to write n as an ordered sum of 10 squares of positive integers.
 * @author Georg Fischer
 */
public class A340947 extends AbstractSequence {

  private final A337165 mSeq = new A337165();

  /** Construct the sequence. */
  public A340947() {
    super(10);
  }

  private int mN = 9;

  @Override
  public Z next() {
    ++mN;
    return mSeq.compute(mN, 10);
  }
}

