package irvine.oeis.a340;
// Generated by gen_seq4.pl holos at 2021-06-07 19:33
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A340567 Total number of ascents in all faro permutations of length n.
 * radtorec(2*x*(4*x^2+x+(-4*x^2+1)^(1/2)-1)/(1-2*x)/(-4*x^2+1)^(1/2)/((-4*x^2+1)^(1/2)+1))
 * @author Georg Fischer
 */
public class A340567 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A340567() {
    super(0, "[[0],[7680,-2816, 256],[-2880, 896,-64],[-1968, 1176,-152],[576,-300, 20],[78,-136, 34],[-9, 22,-1],[6, 3,-3]]", "0, 0, 1, 4, 11, 26, 62, 134, 303, 634, 1394, 2872", 0);
  }
}
