package irvine.oeis.a340;
// Generated by gen_seq4.pl 2024-04-17/multraf at 2024-04-17 19:29

import irvine.oeis.a018.A018900;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A340161 a(n) is the smallest number k for which the set {k + 1, k + 2, ..., k + k} contains exactly n elements with exactly three 1-bits (A014311).
 * @author Georg Fischer
 */
public class A340161 extends MultiTransformSequence {

  /** Construct the sequence. */
  public A340161() {
    super(0, (self, n) -> self.s(0).add(1), "1", new A018900());
  }
}
