package irvine.oeis.a398;
// Generated by gen_seq4.pl 2026-09-10.ack/arrlamb at 2026-09-10 15: 43

import irvine.math.z.Binomial;
import irvine.oeis.triangle.LambdaArray;

/**
 * A398983 Array read by ascending antidiagonals: A(n,k) = k*binomial((k+1)*n, n)/((k + 1)*n - 1), with k &gt; 0.
 * @author Georg Fischer
 */
public class A398983 extends LambdaArray {

  /** Construct the sequence. */
  public A398983() {
    super(1, 1, 1, 1, (n, k) -> Binomial.binomial((k + 1) * n, n).multiply(k).divide((k + 1) * n - 1));
  }
}
