package irvine.oeis.a398;
// Generated by gen_seq4.pl 2026-08-18.ack/holos at 2026-08-18 21: 46

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A398790 allocated for Sajid Khan Hussain.
 * @author Georg Fischer
 */
public class A398790 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A398790() {
    super(0, "[0,1,2,2,1,-1]", "1,2,5,11", 0, 0);
  }
}
