package irvine.oeis.a081;
// Generated by gen_seq4.pl holos [[0],[-6,4],[-24,15],[6,-8],[0,1]] [1,1,3,9] 0 at 2019-12-06 18:14
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.HolonomicRecurrence;

/**
 * A081696 Expansion of 1/(x + sqrt(1-4x)).
 * @author Georg Fischer
 */
public class A081696 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A081696() {
    super(0, "[[0],[-6,4],[-24,15],[6,-8],[0,1]]", "[1,1,3,9]", 0);
  }
}
