package irvine.oeis.a081;
// Generated by gen_seq4.pl noncomp additional at 2020-06-27 16:22
// DO NOT EDIT here!

import irvine.oeis.NoncomputableSequence;


/**
 * A081098 Atomic numbers of the chemical elements sorted with respect to melting point.
 * @author Georg Fischer
 */

public class A081098 extends NoncomputableSequence {

  /** Construct the sequence. */
  public A081098() {
    super(2, 1, 10, 9, 8, 7, 18, 36, 54, 17, 86, 80, 35, 87, 55, 31, 37, 15, 19, 11, 53, 16, 49, 34, 3, 50, 84, 83, 85, 81, 48, 82, 30, 52, 51, 94, 93, 12, 13, 88, 56, 38, 58, 33, 70, 63, 101, 102, 20, 100, 99, 98, 57, 59, 32, 47, 97, 60, 61, 89, 79, 62, 29, 92, 95, 25, 4, 64, 96, 65, 66, 14, 28, 67, 27, 39, 68, 26, 21, 69, 46, 91, 103, 71, 22, 78, 90, 40, 24, 23, 45, 5, 104, 43, 72, 44, 77, 41, 42, 73, 76, 75, 74, 6);
  }
}
