package irvine.oeis.a081;
// Generated by gen_seq4.pl holos at 2021-05-10 22:28
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A081496 Start with Pascal's triangle; a(n) is the sum of the numbers on the periphery of the n-th central rhombus containing exactly 4 numbers.
 * @author Georg Fischer
 */
public class A081496 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A081496() {
    super(1, "[[0],[-24, 70,-36],[0,-13, 9]]", "[5, 14]", 0);
  }
}
