package irvine.oeis.a281;
// Generated by gen_seq4.pl pfprime 1 5 10 +21 0 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A281839 Numbers k such that <code>5*10^k + 21</code> is prime.
 * @author Georg Fischer
 */
public class A281839 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A281839() {
    super(1, 1, 5, 10, +21);
  }
}
