package irvine.oeis.a281;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A281206 Number of 2 X n 0..1 arrays with no element equal to more than one of its horizontal and antidiagonal neighbors, with the exception of exactly one element, and with new values introduced in order 0 sequentially upwards.
 * @author Georg Fischer
 */
public class A281206 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A281206() {
    super(1, "[0,0,2,8,-12,-12,6,4]", "[1,-3,1,3,-1,-1]");
  }
}
