package irvine.oeis.a291;
// Generated by gen_seq4.pl parmof3 at 2021-10-04 17:07

/**
 * A291500 The arithmetic function uhat(n,1,6).
 * @author Georg Fischer
 */
public class A291500 extends A291041 {

  /** Construct the sequence. */
  public A291500() {
    super(1, 1, 6);
  }
}
