package irvine.oeis.a291;
// Generated by gen_seq4.pl parmof3 at 2021-10-04 17:07

/**
 * A291467 The arithmetic function u(n,6,2).
 * @author Georg Fischer
 */
public class A291467 extends A291040 {

  /** Construct the sequence. */
  public A291467() {
    super(1, 6, 2);
  }
}
