package irvine.oeis.a291;
// Generated by gen_seq4.pl 2023-09-12/holos at 2023-09-12 22:40

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A291506 a(n) = (n!)^8 * Sum_{i=1..n} 1/i^8.
 * @author Georg Fischer
 */
public class A291506 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A291506() {
    super(0, "[[0],[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1],[1,8,28,56,70,56,28,8,2],[-1]", "0,1", 1);
  }
}
