package irvine.oeis.a291;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A291050 Decimal expansion of Pi^2 / 27.
 * @author Georg Fischer
 */
public class A291050 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence. */
  public A291050() {
    super(0, REALS.pow(CR.PI, CR.TWO).divide(CR.valueOf(27)));
  }
}
