package irvine.oeis.a291;
// Generated by gen_seq4.pl 2023-09-05/filter at 2023-09-05 16:05

import irvine.oeis.FilterSequence;
import irvine.oeis.a020.A020509;

/**
 * A291990 Primes of the form Phi(k, -10), where Phi is the cyclotomic polynomial.
 * @author Georg Fischer
 */
public class A291990 extends FilterSequence {

  /** Construct the sequence. */
  public A291990() {
    super(1, new A020509(), PRIME);
  }
}
