package irvine.oeis.a291;
// Generated by gen_seq4.pl parmof3 at 2021-10-04 17:07

/**
 * A291423 The arithmetic function u(n,4,2).
 * @author Georg Fischer
 */
public class A291423 extends A291040 {

  /** Construct the sequence. */
  public A291423() {
    super(1, 4, 2);
  }
}
