package irvine.oeis.a235;
// Generated by gen_seq4.pl holos at 2021-05-08 19:57
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A235535 a(n) = binomial(9*n, 3*n) / (6*n + 1).
 * @author Georg Fischer
 */
public class A235535 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A235535() {
    super(0, "[[0],[-6720, 134136,-960822, 3247695,-5609655, 4782969,-1594323],[0, 16,-104,-360, 3600,-7776, 5184]]", "[1, 12]", 0);
  }
}
