package irvine.oeis.a247;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A247729 Number of length 3+3 0..n arrays with no disjoint pairs in any consecutive four terms having the same sum.
 * @author Georg Fischer
 */
public class A247729 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A247729() {
    super(1, "[0,8,156,896,3144,7264,12944,17684,19772,17516,12784,7148,3180,940,244]", "[1,-2,-1,2,2,2,-5,-2,0,2,5,-2,-2,-2,1,2,-1]");
  }
}
