package irvine.oeis.a247;
// Generated by gen_seq4.pl 2024-01-20/diffs at 2024-01-21 23:32

import irvine.oeis.DifferenceSequence;

/**
 * A247902 First differences of A247683.
 * @author Georg Fischer
 */
public class A247902 extends DifferenceSequence {

  /** Construct the sequence. */
  public A247902() {
    super(1, new A247683());
  }
}
