package irvine.oeis.a225;
// Generated by gen_seq4.pl bref at 2020-11-27 17:17
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.BriefSequence;


/**
 * A225227 The n X n X n dots problem: minimal number of straight lines (connected at their endpoints) required to pass through n^3 dots arranged in an n X n X n grid, without exiting from the box [0, n] X [0, n] X [0, n].
 *
 * @author Georg Fischer
 */
public class A225227 extends BriefSequence {

  /** Construct the sequence. */
  public A225227() {
    super(Z.ONE, Z.SEVEN, new Z("13"));
  }
}
