package irvine.oeis.a228;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A228750 Number of n X 4 binary arrays with top left element equal to 1 and no two ones adjacent horizontally or antidiagonally.
 * @author Georg Fischer
 */
public class A228750 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A228750() {
    super(1, "[0,3,-4,2]", "[1,-8,12,-4]");
  }
}
