package irvine.oeis.a228;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A228256 Number of third differences of arrays of length <code>n+3</code> of numbers in 0..4.
 * @author Georg Fischer
 */
public class A228256 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A228256() {
    super(1, new long[] {0, 33, 268, 1994, 6844, -35854, -86008, -163840, -57600},
      new long[] {1, -9, 20});
  }
}
