package irvine.oeis.a274;
// Generated by gen_seq4.pl bref at 2020-11-27 17:17
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.BriefSequence;


/**
 * A274823 Total number of regions in all arrangements of n circles in the affine plane, excluding the regions that do not belong to the circles.
 *
 * @author Georg Fischer
 */
public class A274823 extends BriefSequence {

  /**
   * Construct the sequence.
   */
  public A274823() {
    super(new Z("1"), new Z("7"), new Z("65"));
  }
}
