package irvine.oeis.a274;
// Generated by gen_seq4.pl 2026-08-17.ack/lambdan at 2026-08-17 21: 41

import irvine.oeis.LambdaSequence;
import irvine.oeis.triangle.DirectArray;

/**
 * A274843 Number of set partitions of [n] such that the difference between each element and its block index is a multiple of ten.
 * @author Georg Fischer
 */
public class A274843 extends LambdaSequence {

  private static final DirectArray A274835 = new A274835();

  /** Construct the sequence. */
  public A274843() {
    super(0, n -> A274835.a(n, 10));
  }
}
