package irvine.oeis.a274;
// Generated by gen_seq4.pl 2024-06-23/lambdan at 2024-06-23 23:33

import irvine.math.function.Functions;
import irvine.oeis.LambdaSequence;

/**
 * A274771 Number of primes &lt;= n-th Carmichael lambda number.
 * @author Georg Fischer
 */
public class A274771 extends LambdaSequence {

  /** Construct the sequence. */
  public A274771() {
    super(1, n -> Functions.PRIME_PI.z(Functions.CARMICHAEL_LAMBDA.z(n)));
  }
}
