package irvine.oeis.a246;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A246715 <code>n * Lucas(n) - (n - 1) * Lucas(n - 1)</code>.
 * @author Georg Fischer
 */
public class A246715 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A246715() {
    super(1, new long[] {0, 1, 3, -5, 1},
      new long[] {1, -2, -1, 2, 1});
  }
}
