package irvine.oeis.a246;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A246476 Number of length n+3 0..5 arrays with no pair in any consecutive four terms totalling exactly 5.
 * @author Georg Fischer
 */
public class A246476 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A246476() {
    super(1, "[0,462,348,408,126]", "[1,-3,-2,-3,-1]");
  }
}
