package irvine.oeis.a264;
// Generated by gen_seq4.pl 2026-06-07.ack/polya at 2026-06-07 21:37

import irvine.oeis.PolynomialFieldSequence;

/**
 * A264998 Number of partitions of n into distinct parts of the form 3^a*5^b or 2.
 * new A264997()
 * @author Georg Fischer
 */
public class A264998 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A264998() {
    super(0, "[1],[1,0,1]", "x,B,p1,*", 0, 0, 1, 1, new A264997());
  }
}
