package irvine.oeis.a264;
// Generated by gen_seq4.pl knest/jaguar at 2023-03-01 20:54

import irvine.factor.factor.Jaguar;
import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a000.A000129;

/**
 * A264137 Largest prime factor of the n-th Pell number, A000129(n).
 * @author Georg Fischer
 */
public class A264137 extends AbstractSequence {

  private final A000129 mSeq1 = new A000129();

  /** Construct the sequence. */
  public A264137() {
    super(2);
  }

  {
    mSeq1.next();
    mSeq1.next();
  }

  @Override
  public Z next() {
    return Jaguar.factor(mSeq1.next()).largestPrimeFactor();
  }
}
