package irvine.oeis.a165;
// Generated by gen_seq4.pl dex CR.TWO.multiply(CR.THREE.sqrt()).divide(CR.THREE.multiply(CR.PI)) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A165952 Decimal expansion of 2*sqrt(3)/(3*Pi).
 * @author Georg Fischer
 */
public class A165952 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A165952() {
    super(CR.TWO.multiply(CR.THREE.sqrt()).divide(CR.THREE.multiply(CR.PI)));
  }
}
