package irvine.oeis.a231;
// Generated by gen_seq4.pl holos [0,1,-1,0,0,0,-1,1] [0,6,11,17,22,28] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A231001 Number of years after which an entire year can have the same calendar, in the Julian calendar.
 * @author Georg Fischer
 */
public class A231001 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A231001() {
    super(1, "[0,1,-1,0,0,0,-1,1]", "[0,6,11,17,22,28]", 0);
  }
}
