package irvine.oeis.a152;
// Generated by gen_seq4.pl 2026-09-06.ack/lambdan at 2026-09-06 21: 22

import irvine.oeis.LambdaSequence;
import irvine.oeis.a244.A244003;
import irvine.oeis.triangle.DirectArray;

/**
 * A152915 Exponacci (or exponential Fibonacci) numbers.
 * @author Georg Fischer
 */
public class A152915 extends LambdaSequence {

  private static final DirectArray A244003 = new A244003();

  /** Construct the sequence. */
  public A152915() {
    super(0, n -> A244003.a(n, n));
  }
}
