package irvine.oeis.a152;
// Generated by gen_seq4.pl holos [[0],[77],[-18],[1]] [1,9,85,837] 0 at 2020-03-14 22:45
// Recurrence: a[n+0]=18*a[n-1]-77*a[n-2]
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A152106 a(n) = (11^n + 7^n)/2.
 * @author Georg Fischer
 */
public class A152106 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A152106() {
    super(0, "[[0],[77],[-18],[1]]", "[1,9,85,837]", 0);
  }
}
