package irvine.oeis.a127;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A127786 Expansion of phi(q) * phi(q^2) * phi(-q^4) in powers of q where phi() is a Ramanujan theta function.
 * @author Georg Fischer
 */
public class A127786 extends EulerTransform {

  /** Construct the sequence. */
  public A127786() {
    super(new PeriodicSequence(2, -1, 2, -6, 2, -1, 2, -3), 1);
  }
}
