package irvine.oeis.a127;
// Generated by gen_seq4.pl 2024-05-25/filnum at 2024-05-25 23:20

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.FilterNumberSequence;
import irvine.oeis.a001.A001223;

/**
 * A127596 Numbers k such that 1 + Sum_{i=1..k-1} A001223(i)*(-1)^i = 0.
 * @author Georg Fischer
 */
public class A127596 extends FilterNumberSequence {

  private static final DirectSequence A001223 = new A001223();

  /** Construct the sequence. */
  public A127596() {
    super(1, 1, k -> Z.ONE.add(Integers.SINGLETON.sum(1, k - 1, i -> A001223.a(i).multiply(Z.NEG_ONE.pow(i)))).isZero());
  }
}
