package irvine.oeis.a052;
// Generated by gen_seq4.pl holos [[0],[1,2,1],[-1,-3,-1],[0,1]] [3,3,5] 2 at 2019-12-06 18:14
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.HolonomicRecurrence;

/**
 * A052898 2*n! + 1.
 * @author Georg Fischer
 */
public class A052898 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A052898() {
    super(0, "[[0],[1,2,1],[-1,-3,-1],[0,1]]", "[3,3,5]", 2);
  }
}
