package irvine.oeis.a196;
// Generated by gen_seq4.pl decsolv at 2021-07-31 13:37

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCrFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A196773 Decimal expansion of the least number x&gt;0 satisfying -1=(x^2)*cos(x).
 * Equation; -1-((x^2)*cos(x))
 * @author Georg Fischer
 */
public class A196773 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A196773() {
    super(1, new UnaryCrFunction() {
      @Override 
      public CR execute(final CR x) {
        return CR.ONE.negate().subtract(x.square().multiply(x.cos()));
      }
    }.inverseMonotone(CR.valueOf(1.826), CR.valueOf(1.900)).execute(CR.ZERO));
  }
}
