package irvine.oeis.a196;
// Generated by gen_seq4.pl 2025-03-28.ack/dead at 2025-03-28 22:47

import irvine.oeis.DeadSequence;

/**
 * A196840 Duplicate of A162298.
 * @author Georg Fischer
 */
public class A196840 extends DeadSequence {

  /** Construct the sequence. */
  public A196840() {
    super(0);
  }
}
