package irvine.oeis.a196;
// Generated by gen_seq4.pl trigf 1, 0, -1, 0, 1, 0, 0, 0, 0, 0 1, 0, -2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 at 2020-02-18 21:32
// 0
// 
// DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionTriangle;

/**
 * A196389 Triangle <code>T(n,k)</code>, read by rows, given by <code>(0,1,-1,0,0,0,0,0,0,0,...)</code> DELTA <code>(1,0,0,1,0,0,0,0,0,0,0,...)</code> where DELTA is the operator defined in <code>A084938</code>.
 * @author Georg Fischer
 */
public class A196389 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A196389() {
    super(0, new long[] {1, 0, -1, 0, 1, 0, 0, 0, 0, 0}, new long[] {1, 0, -2, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0});
  }
}
