package irvine.oeis.a196;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A196512 Expansion of (1-9x)/(1-28x).
 * @author Georg Fischer
 */
public class A196512 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A196512() {
    super(0, new long[] {1, -9},
      new long[] {1, -28});
  }
}
