package irvine.oeis.a196;
// Generated by gen_seq4.pl binomx at 2021-05-28 22:45
// DO NOT EDIT here!

import irvine.oeis.BinomialTransformSequence;
import irvine.oeis.a004.A004111;

/**
 * A196154 Binomial transform of A004111.
 *
 * @author Georg Fischer
 */
public class A196154 extends BinomialTransformSequence {

  /**
   * Construct the sequence.
   */
  public A196154() {
    super(new A004111(), 0);
  }
}
