package irvine.oeis.a196;
// Generated by gen_seq4.pl 2024-12-28.ack/lingfcj at 2024-12-28 22:36

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A196537 Number of nX1 0..4 arrays with each element equal to the number its horizontal and vertical neighbors less than or equal to itself.
 * @author Georg Fischer
 */
public class A196537 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A196537() {
    super(1, "[0,1,2,-2,-1]", "[1,-1,-1,-3,-1]");
  }
}
