package irvine.oeis.a074;
// Generated by gen_seq4.pl pastri at 2021-10-01 23:20

import irvine.oeis.BorderedTriangleRecurrence;
import irvine.oeis.a011.A011773;
/**
 * A074912 Triangle generated by Pascal&apos;s rule, except begin and end the n-th row with phi(n).
 * @author Georg Fischer
 */
public class A074912 extends BorderedTriangleRecurrence  {

  /** Construct the sequence. */
  public A074912() {
    super(new A011773(), new A011773());
  }
}
