package irvine.oeis.a074;
// Generated by gen_seq4.pl 2024-07-21/lambdan at 2024-07-22 00:06

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A074882 Number of integers in {1, 2, ..., sigma(n)} that are coprime to n.
 * @author Georg Fischer
 */
public class A074882 extends LambdaSequence {

  /** Construct the sequence. */
  public A074882() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> Functions.MOBIUS.z(d).multiply(Functions.SIGMA1.z(n).divide(d))));
  }
}
