package irvine.oeis.a254;
// Generated by gen_seq4.pl noncomp additional at 2020-06-27 16:22
// DO NOT EDIT here!

import irvine.oeis.NoncomputableSequence;


/**
 * A254246 Decimal expansion of atomic unit of electric dipole moment in C m.
 * @author Georg Fischer
 */
public class A254246 extends NoncomputableSequence {

  /** Construct the sequence. */
  public A254246() {
    super(8, 4, 7, 8, 3, 5, 3);
  }
}
