package irvine.oeis.a336;
// Generated by gen_seq4.pl decsolv at 2021-08-03 20:49

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A336053 Decimal expansion of the solution s of s/c = 5, where s = arclength and c = chord length on the unit circle.
 * Equation; x-5*sqrt(2-2*cos(x))
 * @author Georg Fischer
 */
public class A336053 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A336053() {
    super(1, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return x.subtract(CR.FIVE.multiply(CR.TWO.subtract(CR.TWO.multiply(x.cos())).sqrt()));
      }
    }.inverseMonotone(CR.valueOf(5.087), CR.valueOf(5.295)).execute(CR.ZERO));
  }
}
