package irvine.oeis.a336;
// Generated by gen_seq4.pl holos at 2020-10-26 23:20
// 6: 6
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;


/**
 * A336030 a(n) = Fibonacci(n-1) + Fibonacci(floor(n/2)).
 * @author Georg Fischer
 */
public class A336030 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A336030() {
    super(0, "[[0],[-1],[-1],[0],[-1],[2],[1],[-1]]", "[1, 0, 2, 2, 3, 4]", 0);
  }
}
