package irvine.oeis.a279;
// Generated by gen_seq4.pl 2025-09-28.ack/rapt at 2025-09-28 21:57

import irvine.oeis.transform.RationalProductTransform;

/**
 * A279759 Expansion of Product_{k&gt;=1} 1/(1 - x^(k*(3*k-1)*(3*k-2)/2)).
 * @author Georg Fischer
 */
public class A279759 extends RationalProductTransform {

  /** Construct the sequence. */
  public A279759() {
    super(0);
    hl(k -> k * (3 * k - 1) * (3 * k - 2) / 2);
  }
}
