package irvine.oeis.a146;
// Generated by gen_seq4.pl padding 0 at 2020-08-22 18:36
// DO NOT EDIT here!

import irvine.oeis.recur.PaddingSequence;


/**
 * A146106 Bell numbers (A000110) read mod 16.
 * @author Georg Fischer
 */
public class A146106 extends PaddingSequence {

  /** Construct the sequence. */
  public A146106() {
    super(new long[] {  }, new long[] {1, 1, 2, 5, 15, 4, 11, 13, 12, 11, 7, 10, 13, 5, 10, 1, 3, 12, 15, 1, 12, 15, 11, 10, 9, 9, 2, 13, 7, 4, 3, 5, 12, 3, 15, 10, 5, 13, 10, 9, 11, 12, 7, 9, 12, 7, 3, 10});
  }
}
