package irvine.oeis.a043;
// Generated by gen_seq4.pl basruneq 3 7 at 2019-06-29 10:25
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.RunsBaseSequence;

/**
 * A043587 Numbers n such that base 3 representation has exactly 7 runs.
 * @author Georg Fischer
 */
public class A043587 extends RunsBaseSequence {

  /** Construct the sequence. */
  public A043587() {
    super(1);
    mK = ensureWidth(7, 3);
  }

  @Override
  protected boolean isOk() {
    return hasRunCount(mK, 3, 7);
  }

  @Override
  public Z next() {
    return getNextWithProperty();
  }
}
