package irvine.oeis.a043;
// Generated by gen_seq4.pl a0330 at 2021-03-04 18:37
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.a033.A033002;


/**
 * A043308 a(n)=A033002(n)/5.
 * @author Georg Fischer
 */
public class A043308 extends A033002 {

  @Override
  public Z next() {
    return super.next().divide(5);
  }
}
