package irvine.oeis.a043;
// Generated by gen_seq4.pl palins at 2021-02-28 23:49
// DO NOT EDIT here!

/**
 * A043076 a(n)=(s(n)+4)/9, where s(n)=n-th base 9 palindrome that starts with 5.
 * @author Georg Fischer
 */
public class A043076 extends A043045 {

  /** Construct the sequence. */
  public A043076() {
    super(+4, 9, 9, 5);
  }
}
