package irvine.oeis.a043;
// Generated by gen_seq4.pl basdig1 1 8 2 3 at 2019-06-28 17:45
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.RunsBaseSequence;

/**
 * A043431 Numbers n such that number of <code>2</code>'s in base 8 is 3.
 * @author Georg Fischer
 */
public class A043431 extends RunsBaseSequence {

  /** Construct the sequence. */
  public A043431() {
    super(1, 0); //
  }

  @Override
  protected boolean isOk() {
    return getDigitCount(mK, 8, 2) == 3;
  }

  @Override
  public Z next() {
    return getNextWithProperty();
  }
}
