package irvine.oeis.a222;
// Generated by gen_seq4.pl 2026-07-25.ack/holos at 2026-07-25 22:01

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A222080 1 = Sum_{n&gt;=0} a(n) * x^n * (1 - (2*n+1)*x)^2.
 * @author Georg Fischer
 */
public class A222080 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A222080() {
    super(0, "[[0],[9,-12,4],[2,-4],[1]]", "1", 0, 0);
  }
}
