package irvine.oeis.a233;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A233225 Number of nX3 0..5 arrays with no element x(i,j) adjacent to value 5-x(i,j) horizontally, diagonally, antidiagonally or vertically, top left element zero, and 1 appearing before 2 3 and 4, and 2 appearing before 3 in row major order.
 * @author Georg Fischer
 */
public class A233225 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A233225() {
    super(1, "[0,-132,2228,-10189,8658,10288,-16598,5006,1422,-748,66,-1]", "6,174,8231,420948,21895530,1142726121,59679029456,3117164734533,162820623245643,8504746957840386", 0, 0);
  }
}
