package irvine.oeis.a233;
// Generated by gen_seq4.pl 2025-12-30.ack/filnum at 2025-12-30 21:43

import irvine.math.function.Functions;
import irvine.oeis.FilterNumberSequence;

/**
 * A233467 Numbers n such that sigma(n) = reversal(3n).
 * @author Georg Fischer
 */
public class A233467 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A233467() {
    super(1, 1, k -> Functions.SIGMA1.z(k).equals(Functions.REVERSE.z(3 * k)));
  }
}
