package irvine.oeis.a233;
// Generated by gen_seq4.pl 2025-03-16.ack/parmof3 at 2025-03-16 17:02

/**
 * A233194 Prime(k), where k is such that (1 + Sum_{i=1..k} prime(i)^11) / k is an integer.
 * @author Georg Fischer
 */
public class A233194 extends A233040 {

  /** Construct the sequence. */
  public A233194() {
    super(1, 1, 11);
  }
}
