package irvine.oeis.a310;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a311.A311788;

/**
 * A310636 Coordination sequence Gal.6.431.6 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A310636 extends A311788 {

  /** Construct the sequence. */
  public A310636() {
    super();
    defineBaseSet(5);
  }
}
