package irvine.oeis.a058;
// Generated by gen_seq4.pl mckay 45A A at 2020-10-07 19:31
// DO NOT EDIT here!

import irvine.oeis.McKayThompsonSequence;


/**
 * A058684 McKay-Thompson series of class 45A for Monster.
 * @author Georg Fischer
 */
public class A058684 extends McKayThompsonSequence {

  /**
   * Construct the sequence.
   */
  public A058684() {
    super("45A", new long[]{1, 0});
  }
}
