package irvine.oeis.a058;
// Generated by gen_seq4.pl mckay 22B B at 2020-10-07 19:31
// DO NOT EDIT here!

import irvine.oeis.McKayThompsonSequence;


/**
 * A058568 McKay-Thompson series of class 22B for Monster.
 * @author Georg Fischer
 */
public class A058568 extends McKayThompsonSequence {

  /**
   * Construct the sequence.
   */
  public A058568() {
    super("22B", new long[]{1, 0});
  }
}
