package irvine.oeis.a058;
// Generated by gen_seq4.pl squaredig4 10 at 2022-01-11 22:24
// DO NOT EDIT here!

import irvine.oeis.SquareDigitsSequence;

/**
 * A058465 Numbers k such that k^2 contains only digits {3,6,8}.
 * @author Georg Fischer
 */
public class A058465 extends SquareDigitsSequence {

  /** Construct the sequence. */
  public A058465() {
    super(1, 10, 4, "3, 6, 8");
  }
}
