package irvine.oeis.a058;
// Generated by gen_seq4.pl mckay 36C C at 2020-10-07 19:31
// DO NOT EDIT here!

import irvine.oeis.McKayThompsonSequence;


/**
 * A058646 McKay-Thompson series of class 36C for Monster.
 * @author Georg Fischer
 */
public class A058646 extends McKayThompsonSequence {

  /**
   * Construct the sequence.
   */
  public A058646() {
    super("36C", new long[]{1, 1});
  }
}
