package irvine.oeis.a159;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A159230 1/8 the number of n X n arrays of squares of integers with every 2X2 subblock summing to 31.
 * @author Georg Fischer
 */
public class A159230 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A159230() {
    super(2, "[0,4,-6,0,3,-1]", "2,5,10,20", 0, 0);
  }
}
