package irvine.oeis.a159;
// Generated by gen_seq4.pl finifull at 2020-01-25 12:34
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.FiniteSequence;

/**
 * A159863 a(3)(baseN) = least number m such that the quotient m/3 is obtained merely by shifting the leftmost digit (MSD) of m to the right end (LSD), and the multiple 3m by shifting the LSD of m to the MSD, in order of increasing number base, N.
 * @author Georg Fischer
 */
public class A159863 extends FiniteSequence {

  /** Construct the sequence. */
  public A159863() {
    super(new Z("10113"), new Z("101343"), new Z("1020412245351433"), new Z("1023"), new Z("10262054413"), new Z("103"), new Z("1034482758620689655172413793"), new Z("2076"));
  }
}
