package irvine.oeis.a159;
// Generated by gen_seq4.pl holose at 2020-04-12 21:28
// egf: exp(11*x-144*x^2)
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A159968 Numerator of <code>Hermite(n, 11/24)</code>.
 * @author Georg Fischer
 */
public class A159968 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A159968() {
    super(0, "[[0],[288],[-11],[2,1]]", "[1,11,-167,-8173]", 2);
    setGfType(1);
  }
}
