package irvine.oeis.a159;
// Generated by gen_seq4.pl joinlr 0 0 new long[] {1L, -2L, 3L} new long[] {56L, 129L, 300L} new long[] {1L, 1L, 1L, 4L, 11L, 24L} at 2019-07-26 00:04

import irvine.oeis.LinearRecurrence;

/**
 * A159349 Transform of the finite sequence <code>(1, 0, -1, 0, 1, 0, -1)</code> by the <code>T_{0,0}</code> transformation (see link).
 * @author Georg Fischer
 */
public class A159349 extends LinearRecurrence {

  /** Construct the sequence. */
  public A159349() {
    super(new long[] {1L, -2L, 3L}, new long[] {56L, 129L, 300L}, new long[] {1L, 1L, 1L, 4L, 11L, 24L});
  }
}
