package irvine.oeis.a244;
// Generated by gen_seq4.pl 2025-12-30.ack/filnum at 2025-12-30 21:43

import irvine.math.function.Functions;
import irvine.oeis.FilterNumberSequence;

/**
 * A244440 Numbers n such that n + phi(n) is a power of 10.
 * @author Georg Fischer
 */
public class A244440 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A244440() {
    super(1, 1, k -> Functions.PHI.z(k).add(k).toString().matches("10*"));
  }
}
