package irvine.oeis.a244;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.prime.PrimePositionSubsequence;


/**
 * A244384 Numbers k such that 1 + k + k^3 + k^5 + k^7 + k^9 + ... + k^33 is prime.
 * @author Georg Fischer
 */
public class A244384 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A244384() {
    super("[[1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1],[-1]]", "[1]", 0);
  }
}
