package irvine.oeis.a244;
// Generated by gen_seq4.pl 2025-09-14.ack/lambdan at 2025-09-14 22:26

import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A244042 In ternary representation of n, replace 2's with 0's.
 * @author Georg Fischer
 */
public class A244042 extends LambdaSequence {

  /** Construct the sequence. */
  public A244042() {
    super(0, n -> new Z(Integer.toString(n, 3).replace('2', '0'), 3));
  }
}
