package irvine.oeis.a302;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A302516 Number of 3 X n 0..1 arrays with every element equal to 0, 1, 4 or 5 horizontally, diagonally or antidiagonally adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A302516 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A302516() {
    super(1, "[0,0,0,0,4,2,0,1,-1]", "4,4,11,15,21,52,118", 0, 0);
  }
}
