package irvine.oeis.a302;
// Generated by gen_seq4.pl 2025-05-30.ack/lambdan at 2025-05-30 21:48

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a001.A001405;
import irvine.oeis.a005.A005558;

/**
 * A302185 Number of 3D n-step walks of type acc.
 * @author Georg Fischer
 */
public class A302185 extends LambdaSequence {

  private static final DirectSequence A001405 = new A001405();
  private static final DirectSequence A005558 = new A005558();

  /** Construct the sequence. */
  public A302185() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(n, k).multiply(A005558.a(k)).multiply(A001405.a(n - k))));
  }
}
