package irvine.oeis.a302;
// Generated by gen_seq4.pl 2024-11-01.ack/holos at 2024-11-01 22:07

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A302870 Expansion of e.g.f. 1 / Sum_{n &gt;= 0} (n+1)^3*x^n/n!.
 * 1/exp(x)/(x^3+6*x^2+7*x+1)
 * @author Georg Fischer
 */
public class A302870 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A302870() {
    super(0, "[[0],[1],[6,1],[7,6],[1,7],[0,1]]", "1,-8,101,-1840,44441,-1340696", 0, 1);
  }
}
