package irvine.oeis.a001;
// Generated by gen_seq4.pl genetf at 2020-12-16 11:03
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.a000.A000041;
import irvine.oeis.transform.GeneralizedEulerTransform;


/**
 * A001970 Functional determinants; partitions of partitions; Euler transform applied twice to all 1's sequence.
 * G.f.: <code>Product_{k&gt;=1} (1/(1-x^k)^A000041(k))</code>
 * @author Georg Fischer
 */
public class A001970 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A001970() {
    super(0, 1);
    mSeqF = new A000041();
    mSeqF.next();
  }

  @Override
  protected Z[] advanceF(final long k) {
    return new Z[]{mSeqF.next()};
  }

}
