package irvine.oeis.a099;
// Generated by gen_seq4.pl partsumm/partsum at 2022-04-12 22:10

import irvine.oeis.PartialSumSequence;
import irvine.oeis.a053.A053510;

/**
 * A099540 Sum of the first n digits of log(Pi)=1.14472988584940017...
 * @author Georg Fischer
 */
public class A099540 extends PartialSumSequence {

  /** Construct the sequence. */
  public A099540() {
    super(1, new A053510());
  }
}
