package irvine.oeis.a217;
// Generated by gen_seq4.pl 2026-01-06.ack/filnum at 2026-01-06 22:45

import irvine.math.function.Functions;
import irvine.math.predicate.Predicates;
import irvine.oeis.FilterNumberSequence;

/**
 * A217761 Numbers whose square has a square number of decimal digits.
 * @author Georg Fischer
 */
public class A217761 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A217761() {
    super(1, 0, k -> Predicates.SQUARE.is(Functions.DIGIT_LENGTH.i(k * k)));
  }
}
