package irvine.oeis.a135;
// Generated by gen_seq4.pl 2026-01-28.ack/trilambn at 2026-01-28 18:23

import irvine.math.z.Binomial;
import irvine.math.z.Z;
import irvine.oeis.triangle.LambdaTriangle;

/**
 * A135356 Triangle T(n,k) read by rows: coefficients in the recurrence of sequences which equal their n-th differences.
 * @author Georg Fischer
 */
public class A135356 extends LambdaTriangle {

  /** Construct the sequence. */
  public A135356() {
    super(1, 1, 1, (n, k) -> (n > k) ? Z.NEG_ONE.pow(k + 1).multiply(Binomial.binomial(n, k)) : Z.valueOf(2 * (n & 1)));
  }
}
