package irvine.oeis.a135;
// Generated by gen_seq4.pl eulerper 0 12 6, -9, 12, -3, 6, -18, 6, -3, 12, -9, 6, -6 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A135763 Expansion of <code>(theta_3(q) * theta_3(q^3))^3</code> in powers of q.
 * @author Georg Fischer
 */
public class A135763 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A135763() {
    super(new PeriodicSequence(6, -9, 12, -3, 6, -18, 6, -3, 12, -9, 6, -6), 0);
  }
}
