package irvine.oeis.a135;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A135028 Decimal expansion of 28/e.
 * @author Georg Fischer
 */
public class A135028 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A135028() {
    super(2, CR.valueOf(28).divide(CR.E));
  }
}
