package irvine.oeis.a135;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a001.A001248;
import irvine.oeis.a030.A030078;

/**
 * A135177 a(n) = p^2*(p-1), where p = prime(n).
 * @author Georg Fischer
 */
public class A135177 implements Sequence {

  final Sequence mA001248 = new A001248();
  final Sequence mA030078 = new A030078();
  @Override
  public Z next() {
    return mA030078.next().subtract(mA001248.next());
  }

}
