package irvine.oeis.a135;
// Generated by gen_seq4.pl trisum/trisum3 at 2023-06-07 16:03

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a002.A002260;
import irvine.oeis.a023.A023531;
import irvine.oeis.a128.A128174;

/**
 * A135151 A002260 + A128174 - I, I = Identity matrix.
 * @author Georg Fischer
 */
public class A135151 extends AbstractSequence {

  private final A002260 mSeq1 = new A002260();
  private final A128174 mSeq2 = new A128174();
  private final A023531 mSeq3 = new A023531();

  /** Construct the sequence. */
  public A135151() {
    super(1);
  }

  @Override
  public Z next() {
    return mSeq1.next().add(mSeq2.next()).subtract(mSeq3.next());
  }
}
