package irvine.oeis.a135;
// Generated by gen_seq4.pl 2024-01-25/filter at 2024-01-26 22:29

import irvine.math.function.Functions;
import irvine.oeis.FilterSequence;
import irvine.oeis.LambdaSequence;

/**
 * A135726 Primes of the form n!!!-1 = A007661(n)-1, n&gt;0.
 * @author Georg Fischer
 */
public class A135726 extends FilterSequence {

  /** Construct the sequence. */
  public A135726() {
    super(1, new LambdaSequence(0, n -> Functions.MULTIFACTORIAL.z(3, n).subtract(1)), PRIME);
  }
}
