package irvine.oeis.a135;
// Generated by gen_seq4.pl A135799/parm2 at 2021-12-08 10:34

/**
 * A135805 Eighth column (k=7) of triangle A134832 (circular succession numbers).
 * @author Georg Fischer
 */
public class A135805 extends A135799 {

  /** Construct the sequence. */
  public A135805() {
    super(8);
  }
}
