package irvine.oeis.a175;
// Generated by gen_seq4.pl A057934/parm2 at 2022-03-25 23:11

import irvine.oeis.a086.A086801;

/**
 * A175224 a(n) = prime(n) + 8.
 * @author Georg Fischer
 */
public class A175224 extends A086801 {

  /** Construct the sequence. */
  public A175224() {
    super(+8);
  }
}
