package irvine.oeis.a230;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A230702 Number of (n+3)X(2+3) 0..2 white square subarrays x(i,j) with each element diagonally or antidiagonally next to at least one element with value (x(i,j)+1) mod 3, and upper left element zero.
 * @author Georg Fischer
 */
public class A230702 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A230702() {
    super(1, "[0,8,0,-1,0,79,0,42,0,-126,0,31,0,-1]", "8,28,244,800,6576,21076,173428,554040,4558536,14555468,119758148,382358832", 0, 0);
  }
}
