package irvine.oeis.a230;
// Generated by gen_seq4.pl recordpos at 2021-05-28 22:45
// DO NOT EDIT here!

import irvine.oeis.RecordPositionSubsequence;
import irvine.oeis.a159.A159918;

/**
 * A230097 Indices of records in A159918.
 *
 * @author Georg Fischer
 */
public class A230097 extends RecordPositionSubsequence {

  /** Construct the sequence. */
  public A230097() {
    super(new A159918(), 0);
  }
}
