package irvine.oeis.a230;
// Generated by gen_seq4.pl holos [[0],[-2,1],[-1],[0,-1],[1]] [0,0,2,6,26] 0 at 2020-03-14 22:45
// Recurrence: a[n+0]=(2-n)*a[n-3]+a[n-2]+n*a[n-1]
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A230071 Sum over all permutations without double ascents on n elements and each permutation contributes 2 raised to the power of the number of double descents.
 * @author Georg Fischer
 */
public class A230071 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A230071() {
    super(0, "[[0],[-2,1],[-1],[0,-1],[1]]", "[0,0,2,6,26]", 0);
  }
}
