package irvine.oeis.a263;
// Generated by gen_seq4.pl union/union2 at 2023-08-16 22:08

import irvine.oeis.UnionSequence;
import irvine.oeis.a042.A042965;
import irvine.oeis.a097.A097269;

/**
 * A263715 Nonnegative integers that are the sum or difference of two squares.
 * @author Georg Fischer
 */
public class A263715 extends UnionSequence {

  /** Construct the sequence. */
  public A263715() {
    super(1, new A042965(), new A097269());
  }
}
