package irvine.oeis.a263;
// Generated by gen_seq4.pl egfu at 2021-12-07 21:31

import irvine.math.polynomial.Polynomial;
import irvine.math.q.Q;
import irvine.oeis.ExponentialGeneratingFunction;

/**
 * A263547 E.g.f. satisfies: A(x) = exp( x * real( A(x)^I ) ), where I^2 = -1.
 * E.g.f.: exp( reverse( x/cos(x) ) )
 * @author Georg Fischer
 */
public class A263547 extends ExponentialGeneratingFunction {

  /** Construct the sequence. */
  public A263547() {
    super(0);
  }

  @Override
  public Polynomial<Q> compute(final int n) {
    return RING.exp(RING.reversion(RING.series(RING.x(), RING.cos(RING.x(), n), n), n), n);
  }
}
