package irvine.oeis.a263;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.recur.PeriodicSequence;
import irvine.oeis.transform.EulerTransform;


/**
 * A263502 Expansion of phi(q) * f(-q^2)^3 / f(-q^6) in powers of q where phi(), f() are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A263502 extends EulerTransform {

  /** Construct the sequence. */
  public A263502() {
    super(new PeriodicSequence(2, -6, 2, -4, 2, -5, 2, -4, 2, -6, 2, -3), 1);
  }
}
