package irvine.oeis.a394;
// Generated by gen_seq4.pl 2026-04-13.ack/decexp at 2026-04-13 15:20

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A394964 Decimal expansion of Pi^5/768.
 * Formula: Decimal expansion of Pi^5/768.
 * @author Georg Fischer
 */
public class A394964 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A394964() {
    super(0, CR.PI.pow(5).divide(768));
  }
}
