package irvine.oeis.a332;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-27 21:29

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A332624 a(n) = Sum_{k=1..n} ceiling(n/k)^n.
 * a(n)=n + sum(k=1,n-1,sumdiv(k,d,((d + 1)^n - d^n)))
 * @author Georg Fischer
 */
public class A332624 extends LambdaSequence {

  /** Construct the sequence. */
  public A332624() {
    super(1, n -> Z.valueOf(n).add(Integers.SINGLETON.sum(1, n - 1, k -> Integers.SINGLETON.sumdiv(k, d -> Z.valueOf(d + 1).pow(n).subtract(Z.valueOf(d).pow(n))))));
  }
}
