package irvine.oeis.a070;
// Generated by gen_seq4.pl noncomp additional at 2020-06-27 16:22
// DO NOT EDIT here!

import irvine.oeis.NoncomputableSequence;


/**
 * A070879 Stern's diatomic array read by rows (version <code>3 -</code> same as version <code>2, A070878</code>, but with final 0 in each row omitted).
 * @author Georg Fischer
 */

public class A070879 extends NoncomputableSequence {

  /** Construct the sequence. */
  public A070879() {
    super(1, 1, 1, 1, 2, 1, 1, 1, 3, 2, 3, 1, 2, 1, 1, 1, 4, 3, 5, 2, 5, 3, 4, 1, 3, 2, 3, 1, 2, 1, 1, 1, 5, 4, 7, 3, 8, 5, 7, 2, 7, 5, 8, 3, 7, 4, 5, 1, 4, 3, 5, 2, 5, 3, 4, 1, 3, 2, 3, 1, 2, 1, 1, 1, 6, 5, 9, 4, 11, 7, 10, 3, 11, 8, 13, 5, 12, 7, 9, 2, 9, 7, 12, 5, 13, 8, 11, 3, 10, 7, 11, 4, 9, 5, 6, 1, 5, 4, 7, 3, 8);
  }
}
