package irvine.oeis.a375;
// Generated by gen_seq4.pl 2024-09-16.ack/lambdan at 2024-09-16 19:36

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.oeis.LambdaSequence;

/**
 * A375810 Expansion of e.g.f. 1/(1 - (exp(x^2) - 1)/x)^2.
 * @author Georg Fischer
 */
public class A375810 extends LambdaSequence {

  /** Construct the sequence. */
  public A375810() {
    super(0, n -> Rationals.SINGLETON.sum(0, n / 2, k -> new Q(Functions.FACTORIAL.z(n - 2 * k + 1).multiply(Functions.STIRLING2.z(n - k, n - 2 * k)), Functions.FACTORIAL.z(n - k))).multiply(Functions.FACTORIAL.z(n)).num());
  }
}
