package irvine.oeis.a375;
// Generated by gen_seq4.pl 2025-07-21.ack/lambdan at 2025-07-21 18:34

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A375541 a(n) = 2^n * n! * [x^n] (-1/2 - exp(-x))^n.
 * @author Georg Fischer
 */
public class A375541 extends LambdaSequence {

  /** Construct the sequence. */
  public A375541() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Z.valueOf(k).pow(n).multiply(Z.TWO.pow(k)).multiply(Binomial.binomial(n, k))));
  }
}
