package irvine.oeis.a380;
// Generated by gen_seq4.pl 2025-12-15.ack/recpos at 2025-12-15 19:13

import irvine.oeis.RecordPositionSequence;
import irvine.oeis.a113.A113901;

/**
 * A380146 Numbers that set records in A113901.
 * @author Georg Fischer
 */
public class A380146 extends RecordPositionSequence {

  /** Construct the sequence. */
  public A380146() {
    super(1, new A113901(), 1);
  }
}
