package irvine.oeis.a380;
// Generated by gen_seq4.pl 2026-06-19.ack/filnum at 2026-06-19 23:35

import irvine.factor.util.FactorUtils;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A380657 Numbers whose prime factorization has more Pythagorean prime factors than non-Pythagorean prime factors (including multiplicities).
 * @author Georg Fischer
 */
public class A380657 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A380657() {
    super(1, 1, k -> FactorUtils.iterate(k, Z.ZERO, (x, p, e) -> x.add(p.mod(4) == 1 ? e : -e)).compareTo(Z.ZERO) > 0);
  }
}
