package irvine.oeis.a380;
// Generated by gen_seq4.pl 2025-03-02.ack/decexpr at 2025-03-02 23:03

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A380942 Decimal expansion of the largest vertex angle, in radians, in a disdyakis triacontahedron face.
 * Formula: arccos((7 - 4*A001622)/30)
 * @author Georg Fischer
 */
public class A380942 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence */
  public A380942() {
    super(1, REALS.acos(CR.SEVEN.subtract(CR.PHI.multiply(4)).divide(30)));
  }
}
