package irvine.oeis.a054;
// Generated by gen_seq4.pl holos [0,-30,25,16,-10,-2,1] [1,0,3,0,15,6] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A054882 Closed walks of length n along the edges of a dodecahedron based at a vertex.
 * @author Georg Fischer
 */
public class A054882 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A054882() {
    super(1, "[0,-30,25,16,-10,-2,1]", "[1,0,3,0,15,6]", 0);
  }
}
