package irvine.oeis.a054;
// Generated by gen_seq4.pl bref at 2020-11-27 17:17
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.BriefSequence;


/**
 * A054560 Number of labeled pure 2-complexes on n nodes (0-simplexes) with 5 2-simplexes and 11 1-simplexes.
 *
 * @author Georg Fischer
 */
public class A054560 extends BriefSequence {

  /** Construct the sequence. */
  public A054560() {
    super(new Z("6300"), new Z("89586"), new Z("549528"));
  }
}
