package irvine.oeis.a392;
// Generated by gen_seq4.pl 2026-03-21.ack/holos at 2026-03-21 23:21

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A392460 Number of transitive relations on an n-set with exactly seven ordered pairs.
 * @author Georg Fischer
 */
public class A392460 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A392460() {
    super(0, "[0,1,-15,105,-455,1365,-3003,5005,-6435,6435,-5005,3003,-1365,455,-105,15,-1]", "0, 0, 0, 6, 668, 21830, 358290, 3821357, 29994016, 186452712, 963208980, 4276890420, 16732331484, 58779532526, 188192800406", 0, 0);
  }
}
