package irvine.oeis.a392;
// Generated by gen_seq4.pl 2026-01-25.ack/polyx at 2026-01-25 23:30

import irvine.oeis.PolynomialFieldSequence;

/**
 * A392825 E.g.f. A(x) satisfies A(x) = 1/(1 - x*(exp(x*A(x)) - 1)^2).
 * @author Georg Fischer
 */
public class A392825 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A392825() {
    super(0, "[1]", "1,1,A,<1,exp,1,-,^2,<1,-,/", 0, 1);
  }
}
