package irvine.oeis.a392;
// Generated by gen_seq4.pl 2026-01-14.ack/filnum at 2026-01-14 21:59

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A392383 Numbers m with abundance 28: sigma(m) - 2*m = 28.
 * @author Georg Fischer
 */
public class A392383 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A392383() {
    super(1, 1, k -> Functions.SIGMA1.z(k).subtract(2 * k).equals(Z.valueOf(28)));
  }
}
