package irvine.oeis.a392;
// Generated by gen_seq4.pl 2026-02-01.ack/lambdan at 2026-02-01 21:48

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Binomial;
import irvine.oeis.LambdaSequence;

/**
 * A392999 Expansion of e.g.f. (1/x) * Series_Reversion( x/(exp(x) + x^2) ).
 * @author Georg Fischer
 */
public class A392999 extends LambdaSequence {

  /** Construct the sequence. */
  public A392999() {
    super(0, n -> Rationals.SINGLETON.sum(0, n / 2, k -> new Q(n - k + 1).pow(n - 2 * k - 1).multiply(Binomial.binomial(n, k)).divide(Functions.FACTORIAL.z(n - 2 * k))).multiply(Functions.FACTORIAL.z(n)).num());
  }
}
