package irvine.oeis.a172;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A172206 Number of ways to place 7 nonattacking kings on a 7 X n board.
 * @author Georg Fischer
 */
public class A172206 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A172206() {
    super(1, new long[] {0, 0, 0, 24, 734, 30546, 120530, 324486, 137902, 217860, -55038, 
      57102, -13990, 3387},
      new long[] {1, -8, 28, -56, 70, -56, 28, -8, 1});
  }
}
