package irvine.oeis.a184;
// Generated by gen_seq4.pl holos [0,1,-4,6,-4,1] [2,8,27,64,125] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A184628 <code>Floor(1/frac((4+n^4)^(1/4)))</code>, where <code>frac(x)</code> is the fractional part of <code>x</code>.
 * @author Georg Fischer
 */
public class A184628 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A184628() {
    super(1, "[0,1,-4,6,-4,1]", "[2,8,27,64,125]", 0);
  }
}
