package irvine.oeis.a124;
// Generated by gen_seq4.pl 2026-02-13.ack/parmof5 at 2026-02-13 16:26

import irvine.math.z.Z;

/**
 * A124986 Primes of the form 12*k + 5 generated recursively. Initial prime is 5. General term is a(n) = Min_{p is prime; p divides 1 + 4*Q^2; p == 5 (mod 12)}, where Q is the product of previous terms in the sequence.
 * @author Georg Fischer
 */
public class A124986 extends A124984 {

  /** Construct the sequence. */
  public A124986() {
    super(1, Z.FIVE, 12, 5, q -> q.square().multiply(4).add(1));
  }
}
