package irvine.oeis.a120;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.RADDSequence;


/**
 * A120214 Start with 1013 and repeatedly reverse the digits and add 2 to get the next term.
 * @author Georg Fischer
 */
public class A120214 extends RADDSequence {

  /** Construct the sequence. */
  public A120214() {
    super(10, 1013, 2);
  }
}
