package irvine.oeis.a120;
// Generated by gen_seq4.pl 2025-07-13.ack/poly at 2025-07-13 21:23

import irvine.oeis.PolynomialFieldSequence;

/**
 * A120974 G.f. A(x) satisfies A(x/A(x)^4) = 1 + x; thus A(x) = 1 + series_reversion(x/A(x)^4).
 * @author Georg Fischer
 */
public class A120974 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A120974() {
    super(0, "[1]", "1,x,A,^4,/,rev,+");
  }
}
