package irvine.oeis.a120;
// Generated by gen_seq4.pl 2026-05-10.ack/prepend at 2026-05-10 23:05

import irvine.oeis.DifferenceSequence;
import irvine.oeis.PrependSequence;

/**
 * A120528 First differences of successive generalized meta-Fibonacci numbers A120506.
 * @author Georg Fischer
 */
public class A120528 extends PrependSequence {

  /** Construct the sequence. */
  public A120528() {
    super(1, new DifferenceSequence(1, new A120506()), 1);
  }
}
