package irvine.oeis.a120;
// Generated by gen_seq4.pl A120134/parm4 at 2022-03-24 23:21

/**
 * A120180 a(1)=3; a(n)=floor((20+sum(a(1) to a(n-1)))/6).
 * @author Georg Fischer
 */
public class A120180 extends A120134 {

  /** Construct the sequence. */
  public A120180() {
    super(3, 20, 6);
  }
}
