package irvine.oeis.a326;
// Generated by gen_seq4.pl 2024-11-10.ack/sintrif at 2024-11-10 23:25

import irvine.math.function.Functions;
import irvine.oeis.a054.A054391;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A326243 Number of capturing set partitions of {1..n}.
 * @author Georg Fischer
 */
public class A326243 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A326243() {
    super(0, (term, n) -> Functions.BELL.z(n).subtract(term), "", new A054391());
  }
}
