package irvine.oeis.a365;
// Generated by gen_seq4.pl 2023-11-11/holos at 2023-11-11 23:25

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A365028 a(n) = Sum_{k = 0..n} (-1)^(n+k) * binomial(n,k)*binomial(n+k-1,n)* binomial(3*n+k-1,n).
 * @author Georg Fischer
 */
public class A365028 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A365028() {
    super(0, "[[0],[86400,-960480,4448664,-11410578,17981829,-18126711,11724912,-4706100,1066527,-104247],[-25920,318024,-1647756,4752290,-8420841,9521172,-6884259,3078189,-774840,83941],[0,0,5004,-40446,128598,-212820,200739,-108993,31779,-3861]]", "1,3", 0);
  }
}
