package irvine.oeis.a372;
// Generated by gen_seq4.pl 2025-03-07.ack/multrar at 2025-03-07 21:14

import irvine.math.function.Functions;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A372993 a(n) = n! a(n-1) / a(n-2), where a(0) = 1, a(1) = 1.
 * @author Georg Fischer
 */
public class A372993 extends MultiTransformSequence {

  /** Construct the sequence. */
  public A372993() {
    super(0, (self, n) -> Functions.FACTORIAL.z(n).multiply(self.a(n - 1)).divide(self.a(n - 2)), "1,1");
  }
}
