package irvine.oeis.a188;
// Generated by gen_seq4.pl posins at 2020-06-21 23:01
// DO NOT EDIT here!

import irvine.oeis.PositionSequence;


/**
 * A188070 Positions of 1 in A188068; complement of A188069.
 * @author Georg Fischer
 */
public class A188070 extends PositionSequence {

  /** Construct the sequence. */
  public A188070() {
    super(1, new A188068(), 1);
  }
}
