package irvine.oeis.a188;
// Generated by gen_seq4.pl dex CR.SEVEN.sqrt().add(CR.EIGHT.sqrt()) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A188932 Decimal expansion of <code>sqrt(7)+sqrt(8)</code>.
 * @author Georg Fischer
 */
public class A188932 extends DecimalExpansionSequence {

  private static final CR N = CR.SEVEN.sqrt().add(CR.EIGHT.sqrt());

  @Override
  protected CR getCR() {
    return N;
  }
}
