package irvine.oeis.a381;
// Generated by gen_seq4.pl 2025-06-15.ack/polya at 2025-06-15 21:33

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a090.A090353;

/**
 * A381890 Expansion of Product_{k&gt;=1} (1 + k*x)^((1/12) * (3/4)^k).
 * new A090353()
 * @author Georg Fischer
 */
public class A381890 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A381890() {
    super(0, "[1]", "1,x,neg,B,/", 0, 0, 1, 1, new A090353());
  }
}
