package irvine.oeis.a284;
// Generated by gen_seq4.pl 2026-09-04.ack/partpred at 2026-09-04 21: 59

import irvine.math.partition.IntegerPartition;
import irvine.math.partition.PartitionUtils;
import irvine.math.q.Q;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A284615 Number of partitions of n such that the (sum of distinct odd parts) &gt;= n/2.
 * @author Georg Fischer
 */
public class A284615 extends LambdaSequence {

  /** Construct the sequence. */
  public A284615() {
    super(1, n -> (n == 0) ? Z.ZERO : IntegerPartition.count(Math.toIntExact(n), p -> new Q(PartitionUtils.evenOddSums(p)[1]).compareTo(new Q(n, 2)) >= 0));
  }
}
