package irvine.oeis.a284;
// Generated by gen_seq4.pl morfps at 2021-05-27 23:03
// DO NOT EDIT here!

import irvine.oeis.MorphismFixedPointSequence;


/**
 * A284954 0-limiting word of the morphism 0->10, 1-> 000.
 * @author Georg Fischer
 */
public class A284954 extends MorphismFixedPointSequence {

  /** Construct the sequence. */
  public A284954() {
    super("0", "0001", "0->10, 1->000");
  }
}
