package irvine.oeis.a284;
// Generated by gen_seq4.pl egfsi at 2021-12-01 15:37

import irvine.math.group.PolynomialRingField;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A284860 Alternating row sums of the Sheffer triangle (exp(x), exp(3*x) - 1) given in A282629.
 * E.g.f.: exp(x)*exp(1 - exp(3*x))
 * @author Georg Fischer
 */
public class A284860 implements Sequence {

  private static final PolynomialRingField<Q> RING = new PolynomialRingField<>(Rationals.SINGLETON);
  private int mN = -1;
  private Z mF = Z.ONE;

  @Override
  public Z next() {
    if (++mN != 0) {
      mF = mF.multiply(mN);
    }
    return RING.multiply(RING.exp(RING.x(), mN), RING.exp(RING.subtract(RING.one(), RING.exp(RING.monomial(Q.THREE, 1), mN)), mN), mN).coeff(mN).multiply(mF).toZ();
  }
}
