package irvine.oeis.a284;
// Generated by gen_seq4.pl simgcd/simgcdp at 2023-08-12 22:14

import irvine.math.z.Z;
import irvine.oeis.PrependSequence;
import irvine.oeis.a125.A125251;

/**
 * A284045 Numbers k such that p = 6k-1 and q = 6k+1 are twin primes and (p^2 + q^2)/2 is prime.
 * @author Georg Fischer
 */
public class A284045 extends PrependSequence {

  /** Construct the sequence. */
  public A284045() {
    super(1, new A125251() {
      @Override
      public Z next() {
        return super.next().multiply(5);
      }
    }, 1);
  }
}
