package irvine.oeis.a284;
// Generated by gen_seq4.pl 2024-02-07/lambdan at 2024-02-07 14:25

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A284258 a(n) = number of distinct prime factors of n that are &gt; the square of smallest prime factor of n, a(1) = 0.
 * @author Georg Fischer
 */
public class A284258 extends LambdaSequence {

  /** Construct the sequence. */
  public A284258() {
    super(1, n -> Integers.SINGLETON.sopf(n, p -> Z.valueOf(p).compareTo(Functions.LPF.z(n).square()) > 0 ? Z.ONE : Z.ZERO));
  }
}
