package irvine.oeis.a396;
// Generated by gen_seq4.pl 2026-10-08.ack/polya at 2026-10-08 

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a000.A000041;

/**
 * A396091 Number of integer partitions of 2*n with reverse-alternating sum 8.
 * new A000041(), new A396075()
 * @author Georg Fischer
 */
public class A396091 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A396091() {
    super(0, "[1]", "x,B,x,C,*", 0, 0, 1, 1, new A000041(), new A396075());
  }
}
