package irvine.oeis.a396;
// Generated by gen_seq4.pl 2026-05-26.ack/decexp at 2026-05-26 22:13

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A396273 Decimal expansion of the probability that if three dice are piled up at random on a horizontal plane the pile will not fall down.
 * Formula:
 * @author Georg Fischer
 */
public class A396273 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A396273() {
    super(0, CR.PI.divide(CR.PI.add(CR.FOUR).square()).multiply(CR.PI.divide(CR.FOUR).add(CR.ONE.divide(CR.valueOf(96))).subtract(CR.SQRT2.divide(CR.valueOf(12))).add(CR.SQRT2.subtract(CR.ONE).log().divide(CR.valueOf(12)))));
  }
}
