package irvine.oeis.a267;
// Generated by gen_seq4.pl 2026-08-27.ack/lambdan at 2026-08-27 23: 17

import irvine.oeis.LambdaSequence;
import irvine.oeis.a047.A047884;
import irvine.oeis.triangle.DirectArray;

/**
 * A267436 Number of self-inverse permutations of [2n] with longest increasing subsequence of length n.
 * @author Georg Fischer
 */
public class A267436 extends LambdaSequence {

  private static final DirectArray A047884 = new A047884();

  /** Construct the sequence. */
  public A267436() {
    super(0, n -> A047884.a(2 * n, n));
  }
}
