package irvine.oeis.a267;
// Generated by gen_seq4.pl caelem/ca1stageb at 2021-12-16 21:00

import irvine.math.z.Z;
import irvine.oeis.ca.Cellular1DAutomaton;

/**
 * A267613 Binary representation of the n-th iteration of the &quot;Rule 185&quot; elementary cellular automaton starting with a single ON (black) cell.
 * @author Georg Fischer
 */
public class A267613 extends Cellular1DAutomaton {

  /** Construct the sequence. */
  public A267613() {
    super(185);
  }

  @Override
  public Z next() {
    return super.nextStageB();
  }
}
