package irvine.oeis.a350;
// Generated by gen_seq4.pl 2023-08-18/simtraf at 2023-08-18 21:51

import irvine.math.z.Z;
import irvine.oeis.a048.A048715;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A350215 A048715, written in binary.
 * @author Georg Fischer
 */
public class A350215 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A350215() {
    super(0, new A048715(), t -> new Z(t.toString(2)));
  }
}
