package irvine.oeis.a141;
// Generated by gen_seq4.pl 2025-03-23.ack/trilambn at 2025-03-23 22:08

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.triangle.LambdaTriangle;

/**
 * A141412 Triangle c(n,k) of the denominators of coefficients [x^k] P(n,x) of the polynomials P(n,x) of A129891.
 * @author Georg Fischer
 */
public class A141412 extends LambdaTriangle {

  /** Construct the sequence. */
  public A141412() {
    super(0, 0, 0, (n, k) -> new Q(Functions.STIRLING1.z(n + 1, k + 1).multiply(Functions.FACTORIAL.z(k + 1)), Functions.FACTORIAL.z(n + 1)).den());
  }
}
