package irvine.oeis.a337;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-21 21:22

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A337465 a(n) = Sum_{k=0..n} (-n)^(n-k) * binomial(2*k,k) * binomial(2*n+1,2*k).
 * @author Georg Fischer
 */
public class A337465 extends LambdaSequence {

  /** Construct the sequence. */
  public A337465() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Z.valueOf(-n).pow(n - k).multiply(Binomial.binomial(2 * k, k)).multiply(Binomial.binomial(2 * n + 1, 2 * k))));
  }
}
