package irvine.oeis.a338;
// Generated by gen_seq4.pl 2025-10-19.ack/filtpos at 2025-10-19 21:24

import irvine.math.z.Z;
import irvine.oeis.FilterPositionSequence;
import irvine.oeis.a056.A056170;

/**
 * A338540 Numbers having exactly three non-unitary prime factors.
 * @author Georg Fischer
 */
public class A338540 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A338540() {
    super(1, 1, new A056170(), v -> v.equals(Z.THREE));
  }
}
