package irvine.oeis.a338;
// Generated by gen_seq4.pl 2025-01-01.ack/parmof2 at 2025-01-01 23:25

import irvine.oeis.a000.A000203;
import irvine.oeis.a111.A111594;

/**
 * A338871 Triangle T(n,k) defined by Sum_{k=1..n} T(n,k)*u^k*x^n/n! = exp(Sum_{n&gt;0} u*sigma(n)*x^n/n!).
 * @author Georg Fischer
 */
public class A338871 extends A111594 {

  /** Construct the sequence. */
  public A338871() {
    super(1, new A000203());
  }
}
