package irvine.oeis.a338;
// Generated by gen_seq4.pl A335669/parmof4 at 2022-07-20 21:18

import irvine.oeis.a001.A001906;
import irvine.oeis.a335.A335669;

/**
 * A338007 Odd composite integers m such that A001906(m)^2 == 1 (mod m).
 * @author Georg Fischer
 */
public class A338007 extends A335669 {

  /** Construct the sequence. */
  public A338007() {
    super(1, new A001906(), 2, 1);
  }
}
