package irvine.oeis.a289;
// Generated by gen_seq4.pl pfprime 1 4 10 -19 3 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A289081 Numbers k such that (4*10^k - 19)/3 is prime.
 * @author Georg Fischer
 */
public class A289081 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A289081() {
    super(1, 1, 4, 10, -19, 3);
  }
}
