package irvine.oeis.a289;
// Generated by gen_seq4.pl build/simple at 2022-06-14 21:39

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.Sequence1;

/**
 * A289945 a(n) = Sum_{k=1..n} k!^4.
 * @author Georg Fischer
 */
public class A289945 extends Sequence1 {

  private int mN = 0;

  @Override
  public Z next() {
    ++mN;
    return Integers.SINGLETON.sum(1, mN, k -> Functions.FACTORIAL.z(k).pow(4));
  }
}
