package irvine.oeis.a289;
// Generated by gen_seq4.pl rootet at 2023-01-22 20:14

import irvine.oeis.a004.A004009;
import irvine.oeis.transform.RootSequence;

/**
 * A289308 Coefficients in expansion of E_4^(3/8).
 * Coefficients in expansion of E_4^(3/8).
 * @author Georg Fischer
 */
public class A289308 extends RootSequence {

  /** Construct the sequence. */
  public A289308() {
    super(0, new A004009().skip(1), 3, 8);
  }
}
