package irvine.oeis.a341;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.Sequence1;
import irvine.oeis.a003.A003973;

/**
 * A341528 a(n) = n * sigma(A003961(n)), where A003961 shifts the prime factorization of n one step towards larger primes, and sigma is the sum of the divisors of n.
 * @author Georg Fischer
 */
public class A341528 extends Sequence1 {

  final Sequence mA003973 = new A003973();
  protected long mN;
  /** Construct the sequence. */
  public A341528() {
    mN = 0;
  }
  
  @Override
  public Z next() {
    ++mN;
    return Z.valueOf(mN).multiply(mA003973.next());
  }

}
