package irvine.oeis.a341;
// Generated by gen_seq4.pl holos at 2024-02-09 22:47

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A341961 G.f. A(x) satisfies: A(x) = (1 + x*A(x))*(1 + 2*x*A(x)) / (1 - x*A(x))^2.
 * G.f.A(x) satisfies -A+(A*x+1)*(2*A*x+1)/(-A*x+1)^2=0
 * @author Georg Fischer
 */
public class A341961 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A341961() {
    super(0, "[[0], [-12000, 7400, -1500, 100], [154080, -116376, 28872, -2352], [72516, 21647, -28956, 4753], [-1789920, 2068572, -807948, 105576], [-213840, 466020, -360720, 95580], [0, -9900, 19440, 3420], [0, -432, -1296, -864]]", "1, 5, 36, 307, 2880, 28714, 298620, 3203183", 0, 0);
  }
}
