package irvine.oeis.a341;
// Generated by gen_seq4.pl 2026-08-17.ack/parmof2 at 2026-08-17 21: 41

/**
 * A341132 Number of partitions of n into 2 distinct prime powers (including 1).
 * @author Georg Fischer
 */
public class A341132 extends A341147 {

  /** Construct the sequence. */
  public A341132() {
    super(3, 2);
  }
}
