package irvine.oeis.a003;
// Generated by gen_seq4.pl sumlipo at 2020-08-05 12:42

import irvine.oeis.SumOfLikePowersSequence;


/**
 * A003372 Numbers that are the sum of 5 positive 7th powers.
 * @author Sean A. Irvine
 */
public class A003372 extends SumOfLikePowersSequence {

  /** Construct the sequence. */
  public A003372() {
    super(7, 5, 5, false);
  }
}  
