package irvine.oeis.a037;
// Generated by gen_seq4.pl parm3 at 2020-10-30 20:57
// DO NOT EDIT here!

/**
 * A037380 Numbers whose base-3 digits are all present among their base-4 digits.
 * @author Georg Fischer
 */
public class A037380 extends A037372 {

  /** Construct the sequence. */
  public A037380() {
    super(3, 4);
  }
}
