package irvine.oeis.a258;
// Generated by gen_seq4.pl eulerper 0 6 -1, -2, 0, -2, -1, -2 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A258291 Expansion of <code>q^(-1/4) * eta(q) * eta(q^2) * eta(q^6) / eta(q^3)</code> in powers of q.
 * @author Georg Fischer
 */
public class A258291 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A258291() {
    super(new PeriodicSequence(-1, -2, 0, -2, -1, -2), 0);
  }
}
