package irvine.oeis.a258;
// Generated by gen_seq4.pl A258175/parmof2 at 2023-12-22 12:09

import irvine.math.z.Z;

/**
 * A258179 Sum over all Dyck paths of semilength n of products over all peaks p of y_p^2, where y_p is the y-coordinate of peak p.
 * @author Georg Fischer
 */
public class A258179 extends A258172 {

  /** Construct the sequence. */
  public A258179() {
    super(0, (x, y) -> Z.valueOf(y).square());
  }
}
