package irvine.oeis.a085;
// Generated by gen_seq4.pl decexp at 2021-07-18 19:09

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A085565 Decimal expansion of lemniscate constant A.
 * Formula: Pi/sqrt(8)/agm(1,sqrt(1/2))
 * @author Georg Fischer
 */
public class A085565 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A085565() {
    super(1, CR.PI.divide(CR.EIGHT.sqrt()).divide(CR.ONE.agm(CR.ONE.divide(CR.TWO).sqrt())));
  }
}
