package irvine.oeis.a085;
// Generated by gen_seq4.pl prisubf at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;
import irvine.oeis.prime.PrimePositionSubsequence;
import irvine.oeis.transform.SimpleTransformSequence;


/**
 * A085146 Numbers n such that n!!!!+1 is prime.
 * @author Georg Fischer
 */
public class A085146 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A085146() {
    super(new SimpleTransformSequence(new HolonomicRecurrence(0, "[[0],[0, 1],[0],[0],[0],[-1]]", "1, 1, 2, 3", 0), k -> k.add(1)), 0);
  }
}
