package irvine.oeis.a085;
// Generated by gen_seq4.pl holos at 2020-04-12 21:28
// ogf: sqrt((1-x)/(1+3*x))
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A085455 Sum_{i=0..n} Sum_{j=0..i} a(j) * a(i-j) = (-3)^n.
 * @author Georg Fischer
 */
public class A085455 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A085455() {
    super(0, "[[0],[0,3],[-4,-2],[-2,-1]]", "[1,-2,4,-10]", 2);
  }
}
