package irvine.oeis.a085;
// Generated by gen_seq4.pl 2025-08-03.ack/filter at 2025-08-03 19:52

import irvine.math.predicate.Predicates;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A085958 Primes p such that 8p +1 and (p-1)/8 are primes.
 * @author Georg Fischer
 */
public class A085958 extends FilterSequence {

  /** Construct the sequence. */
  public A085958() {
    super(1, new A000040(), p -> Predicates.PRIME.is(p.multiply(8).add(1)) && p.subtract(1).mod(8) == 0 && Predicates.PRIME.is(p.subtract(1).divide(8)));
  }
}
