package irvine.oeis.a085;
// Generated by gen_seq4.pl A057934/simple0 at 2022-03-25 23:11

import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A085606 (n-1)^n - 1.
 * @author Georg Fischer
 */
public class A085606 implements Sequence {

  private int mN = -1;

  @Override
  public Z next() {
    ++mN;
    return Z.valueOf(mN - 1).pow(mN).subtract(1);
  }
}
