package irvine.oeis.a085;
// Generated by ./gen_seq4.pl /partsum at 2022-06-25 09:09

import irvine.oeis.PartialSumSequence;
import irvine.oeis.a143.A143731;

/**
 * A085970 Number of integers ranging from 2 to n that are not prime-powers.
 * @author Sean A. Irvine
 */
public class A085970 extends PartialSumSequence {

  /** Construct the sequence. */
  public A085970() {
    super(1, new A143731());
  }
}
