package irvine.oeis.a085;
// Generated by gen_seq4.pl holos at 2020-04-12 21:28
// ogf: sqrt((1-x)/(1+11*x))
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A085457 Sum(Sum a(j)a(i-j),(j=0,..,i)),(i=0,..,n)=(-11)^n.
 * @author Georg Fischer
 */
public class A085457 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A085457() {
    super(0, "[[0],[0,11],[-16,-10],[-2,-1]]", "[1,-6,48,-438]", 2);
  }
}
