package irvine.oeis.a085;
// Generated by gen_seq4.pl A057934/parm2 at 2022-03-25 23:11

/**
 * A085906 Ramanujan sum c_n(6).
 * @author Georg Fischer
 */
public class A085906 extends A085097 {

  /** Construct the sequence. */
  public A085906() {
    super(6);
  }
}
