package irvine.oeis.a386;
// Generated by gen_seq4.pl 2026-05-30.ack/parmof4 at 2026-05-31 21:36

import irvine.oeis.a082.A082182;

/**
 * A386281 Numbers k such that (29^k - 4^k)/25 is prime.
 * @author Georg Fischer
 */
public class A386281 extends A082182 {

  /** Construct the sequence. */
  public A386281() {
    super(1, 29, -4, 25);
  }
}
