package irvine.oeis.a386;
// Generated by gen_seq4.pl 2025-07-31.ack/lambdan at 2025-07-31 07:01

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A386662 a(n) = Sum_{k=1..n} (binomial(n, k) * 3^k) (mod 4^k).
 * @author Georg Fischer
 */
public class A386662 extends LambdaSequence {

  /** Construct the sequence. */
  public A386662() {
    super(1, n -> Integers.SINGLETON.sum(1, n, k -> Binomial.binomial(n, k).multiply(Z.THREE.pow(k)).mod(Z.FOUR.pow(k))));
  }
}
