package irvine.oeis.a061;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A061172 Third column of Lucas bisection triangle (odd part).
 * @author Georg Fischer
 */
public class A061172 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A061172() {
    super(0, new long[] {9, 39, -57, 30, -8},
      new long[] {1, -9, 30, -45, 30, -9, 1});
  }
}
