package irvine.oeis.a061;
// Generated by ./gen_seq4.pl /partsum0 at 2022-07-13 15:15

import irvine.oeis.PartialSumSequence;
import irvine.oeis.PrependSequence;
import irvine.oeis.a008.A008685;

/**
 * A061251 Days in year to end of n-th month starting Jan 01 in a year just following a leap year or millennium.
 * @author Sean A. Irvine
 */
public class A061251 extends PartialSumSequence {

  /** Construct the sequence. */
  public A061251() {
    super(new PrependSequence(new A008685(), 0));
  }
}
