package irvine.oeis.a061;
// Generated by gen_seq4.pl holos [[-2],[-6],[1]] [1,8] 0 at 2019-12-08 00:24
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A061801 <code>(7*6^n - 2)/5</code>.
 * @author Georg Fischer
 */
public class A061801 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A061801() {
    super(1, "[[-2],[-6],[1]]", "[1,8]", 0);
  }
}
