package irvine.oeis.a193;
// Generated by gen_seq4.pl wraptr2 at 2021-10-17 19:42

import irvine.oeis.a088.A088305;
import irvine.oeis.triangle.WrappedRecurrence;

/**
 * A193923 Triangular array:  the fusion of (p(n,x)) by (q(n,x)), where p(n,x)=(x+1)^n and q(n,x)=Sum_{k=0..n}F(k+1)*x^(n-k), where F=A000045 (Fibonacci numbers).
 * @author Georg Fischer
 */
public class A193923 extends WrappedRecurrence {

  /** Construct the sequence. */
  public A193923() {
    super("1", new A088305());
  }
}
