package irvine.oeis.a193;
// Generated by gen_seq4.pl trigf 1, 0, -1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 1, -1, -3, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0 at 2020-02-18 21:32
// 0
// 
// DO NOT EDIT here!

import irvine.oeis.triangle.GeneratingFunctionTriangle;

/**
 * A193816 Triangular array: the fusion of polynomial sequences P and Q given by p(n,x) = x^n + x^(n-1) + ... + x+1 and q(n,x) = (x+2)^n.
 * @author Georg Fischer
 */
public class A193816 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A193816() {
    super(0, new long[] {1, 0, -1, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0}, new long[] {1, -1, -3, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0});
  }
}
