package irvine.oeis.a193;
// Generated by gen_seq4.pl 2025-08-12.ack/polyxa at 2025-08-12 21:55

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a010.A010054;

/**
 * A193375 E.g.f.: A(x) = exp( Sum_{n&gt;=1} x^(n*(n+1)/2) ).
 * new A010054()
 * @author Georg Fischer
 */
public class A193375 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A193375() {
    super(0, "[1]", "x,B,1,-,exp", 0, 1, 1, 1, new A010054());
  }
}
