package irvine.oeis.a249;
// Generated by gen_seq4.pl 2026-03-23.ack/lambdan at 2026-03-23 19:09

import irvine.math.cr.CR;
import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.LambdaSequence;

/**
 * A249669 a(n) = floor(prime(n)^(1+1/n)).
 * @author Georg Fischer
 */
public class A249669 extends LambdaSequence {

  /** Construct the sequence. */
  public A249669() {
    super(1, n -> CR.valueOf(Functions.PRIME.z(n)).pow(new Q(n + 1, n)).floor());
  }
}
