package irvine.oeis.a049;
// Generated by gen_seq4.pl joinlr 0 0 new long[] {1L, -2L, 0L, 2L} new long[] {10L, 21L, 34L, 53L} new long[] {1L, 4L} at 2019-07-26 00:04

import irvine.oeis.recur.LinearRecurrence;

/**
 * A049486 Maximum length of non-crossing path on n X n square lattice.
 * @author Georg Fischer
 */
public class A049486 extends LinearRecurrence {

  /** Construct the sequence. */
  public A049486() {
    super(1, new long[] {1L, -2L, 0L, 2L}, new long[] {10L, 21L, 34L, 53L}, 1L, 4L);
  }
}
