package irvine.oeis.a049;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A049853 a(n) = a(n-1) + Sum_{k=0..n-3} a(k) for n &gt;= 2, a(0)=1, a(1)=2.
 * @author Georg Fischer
 */
public class A049853 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A049853() {
    super(0, new long[] {1, 0, -1},
      new long[] {1, -2, 1, -1});
  }
}
