package irvine.oeis.a049;
// Generated by gen_seq4.pl primsol at 2021-02-28 18:46
// DO NOT EDIT here!

import irvine.oeis.a040.A040028;

/**
 * A049554 Primes p such that x^22 = 2 has a solution mod p.
 * @author Georg Fischer
 */
public class A049554 extends A040028 {

  /** Construct the sequence. */
  public A049554() {
    super(22, 2, true);
  }
}
