package irvine.oeis.a049;
// Generated by gen_linrec.pl - DO NOT EDIT here!

import irvine.oeis.LinearRecurrence;

/**
 * A049221 Number of horizontally convex n-ominoes in which the top row has exactly 1 square, which is not above the rightmost square in the second row.
 * @author Georg Fischer
 */
public class A049221 extends LinearRecurrence {

  /** Construct the sequence. */
  public A049221() {
    super(new long[] {4L, -7L, 5L}, new long[] {1L, 4L, 14L}, new long[] {1L, 0L});
  } // constructor()
} // A049221
