package irvine.oeis.a170;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.CoxeterSequence;

/**
 * A170683 Number of reduced words of length n in Coxeter group on 50 generators S_i with relations (S_i)^2 = (S_i S_j)^49 = I.
 * @author Georg Fischer
 */
public class A170683 extends CoxeterSequence {

  /** Construct the sequence. */
  public A170683() {
    super(
      49, 
      50);
  }
}
