package irvine.oeis.a296;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A296817 Expansion of 1/Sum_{k&gt;=0} (2*k+1)^2*x^k.
 * @author Georg Fischer
 */
public class A296817 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A296817() {
    super(0, new long[] {1, -3, 3, -1},
      new long[] {1, 6, 1});
  }
}
