package irvine.oeis.a296;
// Generated by gen_seq4.pl trisimple at 2021-11-08 22:02

import irvine.math.z.Z;
import irvine.oeis.triangle.Triangle;

/**
 * A296180 Triangle read by rows: T(n, k) = 3*(n - k)*k + 1, n &gt;= 0, 0 &lt;= k &lt;= n.
 * @author Georg Fischer
 */
public class A296180 extends Triangle {

  /** Construct the sequence. */
  public A296180() {
    super(0);
  }

  @Override
  public Z compute(final int n, final int k) {
    return Z.valueOf(3 * (n - k) * k + 1);
  }
}
