package irvine.oeis.a236;
// Generated by gen_seq4.pl wraptr2 at 2021-10-17 19:42

import irvine.oeis.a000.A000079;
import irvine.oeis.a001.A001792;
import irvine.oeis.a053.A053220;
import irvine.oeis.triangle.WrappedRecurrence;

/**
 * A236538 Triangle read by rows: T(n,k) = (n+1)*2^(n-2)+(k-1)*2^(n-1) for 1 &lt;= k &lt;= n.
 * @author Georg Fischer
 */
public class A236538 extends WrappedRecurrence {

  /** Construct the sequence. */
  public A236538() {
    super(new A001792(), new A053220());
    setPlus(new A000079());
    skipPlus(2);
  }
}
