package irvine.oeis.a163;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.CoxeterSequence;

/**
 * A163220 Number of reduced words of length n in Coxeter group on 37 generators S_i with relations (S_i)^2 = (S_i S_j)^4 = I.
 * @author Georg Fischer
 */
public class A163220 extends CoxeterSequence {

  /** Construct the sequence. */
  public A163220() {
    super(
      4, 
      37);
  }
}
