package irvine.oeis.a163;
// Generated by gen_seq4.pl 2026-06-07.ack/sintrif at 2026-06-07 21:37

import irvine.math.function.Functions;
import irvine.oeis.a008.A008847;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A163763 a(n) = sqrt(sigma(A008847(n)^2)), where A008847 lists numbers m such that sigma(m^2) is a square.
 * @author Georg Fischer
 */
public class A163763 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A163763() {
    super(1, (term, n) -> Functions.SQRT.z(Functions.SIGMA1.z(term.square())), "", new A008847());
  }
}
