package irvine.oeis.a163;
// Generated by gen_seq4.pl 2024-05-09/simtraf at 2024-05-09 22:36

import irvine.oeis.a125.A125061;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A163746 Expansion of (theta_3(q)^2 + 3 * theta_3(q^3)^2) / 4 - 1 in powers of q.
 * @author Georg Fischer
 */
public class A163746 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A163746() {
    super(1, new A125061().skip(1), v -> v);
  }
}
