package irvine.oeis.a163;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-27 21:29

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A163190 a(n) = Sum_{k=0..n} C(n,k)*sigma(n,k) for n&gt;0 with a(0)=1.
 * a(n)=sumdiv(n,d,(1+d)^n)
 * @author Georg Fischer
 */
public class A163190 extends LambdaSequence {

  /** Construct the sequence. */
  public A163190() {
    super(0, n -> Integers.SINGLETON.sumdiv(n, d -> Z.valueOf(1 + d).pow(n)));
  }
}
