package irvine.oeis.a143;
// Generated by gen_seq4.pl holsig2/holos at 2023-08-09 20:27

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A143994 Years in which there are five Tuesdays in the month of February.
 * @author Georg Fischer
 */
public class A143994 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A143994() {
    super(1, "[0,-1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,-1]", "1752, 1780, 1820, 1848, 1876, 1916, 1944, 1972, 2000, 2028, 2056, 2084, 2124, 2152", 0);
  }
}
