package irvine.oeis.a143;
// Generated by gen_seq4.pl holos [0,-3,0,0,-1,1] [1,4,7,10] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A143454 Expansion of <code>1/(x^k*(1-x-3*x^(k+1)))</code> for <code>k=3</code>.
 * @author Georg Fischer
 */
public class A143454 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A143454() {
    super(1, "[0,-3,0,0,-1,1]", "[1,4,7,10]", 0);
  }
}
