package irvine.oeis.a143;
// Generated by gen_seq4.pl robots/triprod at 2023-08-14 15:21

import irvine.oeis.a054.A054525;
import irvine.oeis.triangle.Product;

/**
 * A143316 Triangle read by rows, A054525 * A143315, 1&lt;=k&lt;=n.
 * @author Georg Fischer
 */
public class A143316 extends Product {

  /** Construct the sequence. */
  public A143316() {
    super(1, new A054525(), new A143315());
  }
}
