package irvine.oeis.a045;
// Generated by gen_seq4.pl holos [[0],[-14,4],[33,-13],[-24,15],[5,-7],[0,1]] [1,1,4,17,66] 0 at 2020-02-15 22:07
// Recurrence: n*a[n+0]+(-7*n+5)*a[n-1]+3*(5*n-8)*a[n-2]+(-13*n+33)*a[n-3]+2*(2*n-7)*a[n-4]=0
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A045992 <code>a(n) = binomial(2n,n) -</code> n; number of (weakly) increasing or decreasing maps from <code>1,...,n</code> to <code>1,...,n</code>.
 * @author Georg Fischer
 */
public class A045992 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A045992() {
    super(0, "[[0],[-14,4],[33,-13],[-24,15],[5,-7],[0,1]]", "[1,1,4,17,66]", 0);
  }
}
