package irvine.oeis.a045;
// Generated by gen_seq4.pl eulerper 0 9 0, 0, 1, 0, 0, 1, 0, 0, -2 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A045833 Expansion of <code>eta(q^9)^3 / eta(q^3)</code> in powers of q.
 * @author Georg Fischer
 */
public class A045833 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A045833() {
    super(new PeriodicSequence(0, 0, 1, 0, 0, 1, 0, 0, -2), 0, Z.ZERO);
  }
}
