package irvine.oeis.a377;
// Generated by gen_seq4.pl 2024-10-25.ack/holos at 2024-10-25 23:02

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A377198 Expansion of 1/(1 - 4*x/(1-x)^2)^(3/2).
 * 1/(1-4*x/(1-x)^2)^(3/2)
 * @author Georg Fischer
 */
public class A377198 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A377198() {
    super(0, "[[0],[-3,1],[20,-7],[-1,7],[0,-1]]", "1,6,42,278,1794", 0, 0);
  }
}
