package irvine.oeis.a377;
// Generated by gen_seq4.pl 2025-06-15.ack/polyxa at 2025-06-15 21:33

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a057.A057660;

/**
 * A377585 E.g.f.: exp(Sum_{k&gt;=1} A057660(k) * x^k).
 * new A057660()
 * @author Georg Fischer
 */
public class A377585 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A377585() {
    super(0, "[1]", "x,B,exp", 0, 1, 1, 1, new A057660());
  }
}
