package irvine.oeis.a242;
// Generated by gen_seq4.pl 2025-05-11.ack/polya at 2025-05-11 22:56

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a006.A006013;

/**
 * A242637 Number of quadrangulations of a hexagon having n inner faces.
 * new A006013()
 * @author Georg Fischer
 */
public class A242637 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A242637() {
    super(0, "[0,0,3]", "3,7,x,S,<1,*,-,x,S,<1,^2,*,1,x,S,<1,-,^3,/", 0, 0, 1, 1, new A006013());
  }
}
