package irvine.oeis.a361;
// Generated by gen_seq4.pl 2025-02-22.ack/lambdan at 2025-02-22 21:47

import irvine.math.q.Q;
import irvine.oeis.LambdaSequence;

/**
 * A361506 a(n) = floor( (4/5)*( (9/4)^(n+1)-1 ) ).
 * @author Georg Fischer
 */
public class A361506 extends LambdaSequence {

  /** Construct the sequence. */
  public A361506() {
    super(0, n -> new Q(4, 5).multiply(new Q(9, 4).pow(n + 1).subtract(1)).floor());
  }
}
