package irvine.oeis.a361;
// Generated by gen_seq4.pl 2024-02-26/holos at 2024-02-26 19:18

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A361896 Expansion of 1/(1 - 9*x/(1 - x)^4)^(1/3).
 * @author Georg Fischer
 */
public class A361896 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A361896() {
    super(0, "[[0], [-5, 1], [20, -5], [-30, 10], [47, -19], [-11, 14], [0, -1]]", "1", 0, 0);
  }
}
