package irvine.oeis.a361;
// Generated by gen_seq4.pl 2024-11-21.ack/lambdan at 2024-11-21 23:03

import irvine.oeis.LambdaSequence;

/**
 * A361891 a(n) = S(7,n)/S(1,n), where S(r,n) = Sum_{k = 0..floor(n/2)} ( binomial(n,k) - binomial(n,k-1) )^r.
 * @author Georg Fischer
 */
public class A361891 extends LambdaSequence {

  /** Construct the sequence. */
  public A361891() {
    super(0, n -> A361887.bisum(7, n).divide(A361887.bisum(1, n)));
  }
}
