package irvine.oeis.a361;
// Generated by gen_seq4.pl 2023-09-21/LAMBDA at 2023-09-21 17:48

import irvine.math.factorial.MemoryFactorial;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Binomial;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A361065 E.g.f. satisfies A(x) = exp( (x/(1-x)) * A(x)^2 ).
 * @author Georg Fischer
 */
public class A361065 extends LambdaSequence {

  /** Construct the sequence. */
  public A361065() {
    super(0, n -> Rationals.SINGLETON.sum(0, n, k -> new Q(Z.valueOf(2 * k + 1)).pow(k - 1).multiply(Binomial.binomial(n - 1, n - k)).divide(MemoryFactorial.SINGLETON.factorial(k))).multiply(MemoryFactorial.SINGLETON.factorial(n)).num());
  }
}
