package irvine.oeis.a361;
// Generated by gen_seq4.pl 2025-02-20.ack/filnum at 2025-02-20 23:05

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.FilterNumberSequence;
import irvine.oeis.a007.A007504;

/**
 * A361627 Positive integers such that GCD(A007504(n),n) != 1.
 * @author Georg Fischer
 */
public class A361627 extends FilterNumberSequence {

  private static final DirectSequence A007504 = new A007504();

  /** Construct the sequence. */
  public A361627() {
    super(1, 1, k -> !Functions.GCD.z(A007504.a(k), Z.valueOf(k)).equals(Z.ONE));
  }
}
