package irvine.oeis.a361;
// Generated by gen_seq4.pl 2026-06-05.ack/convprod at 2026-06-05 00:38

import irvine.oeis.a263.A263149;
import irvine.oeis.a263.A263150;
import irvine.oeis.transform.ConvolutionProduct;

/**
 * A361008 G.f.: Product_{k &gt;= 0} ((1 + x^(2*k+1)) / (1 - x^(2*k+1)))^k.
 * @author Georg Fischer
 */
public class A361008 extends ConvolutionProduct {

  /** Construct the sequence. */
  public A361008() {
    super(0, "1,1", new A263149(), new A263150());
  }
}
