package irvine.oeis.a366;
// Generated by gen_seq4.pl robots/lingf at 2023-12-08 21:04

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A366324 Number of tilings of a 5 X n rectangle using n pentominoes of shapes T, W, Y, X.
 * @author Georg Fischer
 */
public class A366324 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A366324() {
    super(0, "[1,0,-1,0,-3,-7,0,3,-1,4,-6,-1,11,0,-28,-1,5,14,-12,-26,-16,102,23,-36,-21,-47,33,50,-61,-82,79,-4,84,42,-13,-8,40,-4,-8,-20,-16,-32,-16]", "[1,0,-1,0,-5,-9,-6,5,-5,-8,-48,13,37,36,-58,-37,37,94,-8,-56,-188,254,181,-92,55,-155,267,346,-91,-444,61,-56,258,-36,-371,-116,122,94,-40,-116,-64,0,-16,0,-32]");
  }
}
