package irvine.oeis.a366;
// Generated by gen_seq4.pl 2024-06-21/simtraf at 2024-06-22 00:01

import irvine.math.function.Functions;
import irvine.oeis.a001.A001043;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A366274 a(n) is the least k such that prime(n+1+k) &gt;= prime(n)+prime(n+1).
 * @author Georg Fischer
 */
public class A366274 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A366274() {
    super(1, new A001043(), (n, v) -> Functions.PRIME_PI.z(v.subtract(1)).subtract(n));
  }
}
