package irvine.oeis.a366;
// Generated by gen_seq4.pl holfsig/holos at 2024-02-04 22:45

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A366488 a(n) = (n^11 - n)/11.
 * @author Georg Fischer
 */
public class A366488 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A366488() {
    super(0, "[0, -1, 12, -66, 220, -495, 792, -924, 792, -495, 220, -66, 12, -1]", "0, 0, 186, 16104, 381300, 4438920, 32981550, 179756976, 780903144, 2852823600, 9090909090, 25937424600, 67546215516, 162923672184, 368142288150, 786341441760, 1599289640400, 3115626937056", 0);
  }
}
