package irvine.oeis.a117;
// Generated by gen_seq4.pl mult at 2022-08-01 11:56

import irvine.math.z.Z;
import irvine.oeis.MultiplicativeSequence;

/**
 * A117000 a(n) = Sum_{d|n} Jacobi(2,d)*d.
 * @author Georg Fischer
 */
public class A117000 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A117000() {
    super(1, (p, e) -> is2(p) ? Z.ONE : (isMod(8, p, 1, 7) ? sigmaP(p, e) : sigmaP(p.negate(), e)));
  }
}
