package irvine.oeis.a106;
// Generated by gen_seq4.pl A078847/parm3 at 2022-02-14 19:20

/**
 * A106811 Largest prime of the set of seven consecutive primes whose sum of digits is a set of seven distinct primes.
 * @author Georg Fischer
 */
public class A106811 extends A106809 {

  /** Construct the sequence. */
  public A106811() {
    super(7, 7);
  }
}
