package irvine.oeis.a106;
// Generated by gen_seq4.pl 2024-03-19/filter at 2024-03-19 22:04

import irvine.math.z.ZUtils;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A106093 Primes with maximal digit = 9.
 * @author Georg Fischer
 */
public class A106093 extends FilterSequence {

  /** Construct the sequence. */
  public A106093() {
    super(1, new A000040(), p -> ZUtils.sortDigitsAscending(p).mod(10) == 9);
  }
}
