package irvine.oeis.a106;
// Generated by gen_seq4.pl 2024-03-19/filter at 2024-03-19 22:04

import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A106084 Primes p such that 5*p + 18 and 18*p + 5 are primes.
 * @author Georg Fischer
 */
public class A106084 extends FilterSequence {

  /** Construct the sequence. */
  public A106084() {
    super(1, new A000040(), p -> p.multiply(5).add(18).isProbablePrime() && p.multiply(18).add(5).isProbablePrime());
  }
}
