package irvine.oeis.a032;
// Generated by gen_seq4.pl pfprime 1 75 2 +1 0 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A032387 Numbers k such that <code>75*2^k+1</code> is prime.
 * @author Georg Fischer
 */
public class A032387 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A032387() {
    super(1, 1, 75, 2, 1);
  }
}
