package irvine.oeis.a032;
// Generated by gen_seq4.pl pfprime 1 119 2 +1 0 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A032409 Numbers k such that 119*2^k+1 is prime.
 * @author Georg Fischer
 */
public class A032409 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A032409() {
    super(1, 1, 119, 2, +1, 0);
  }
}
