package irvine.oeis.a272;
// Generated by gen_seq4.pl deris/recordpos at 2022-10-26 15:17
// DO NOT EDIT here!

import irvine.oeis.RecordPositionSubsequence;
import irvine.oeis.a054.A054025;

/**
 * A272720 Where records occur in A054025.
 * @author Georg Fischer
 */
public class A272720 extends RecordPositionSubsequence {

  /** Construct the sequence. */
  public A272720() {
    super(1, new A054025());
  }
}
