package irvine.oeis.a272;
// Generated by gen_seq4.pl egfu/egfue at 2021-12-04 17:50

import irvine.math.polynomial.Polynomial;
import irvine.math.q.Q;
import irvine.oeis.ExponentialGeneratingFunction;

/**
 * A272462 E.g.f.: (sin(3^2*x) + sin(4^2*x)) / sin(5^2*x).
 * E.g.f.: (cos(3^2*x) + cos(4^2*x))/(1 + cos(5^2*x))
 * @author Georg Fischer
 */
public class A272462 extends ExponentialGeneratingFunction {

  /** Construct the sequence. */
  public A272462() {
    super(0, 0, 2);
  }

  @Override
  public Polynomial<Q> compute(final int mN) {
    return RING.series(RING.add(RING.cos(RING.multiply(RING.pow(RING.monomial(new Q(3), 0), 2, mN), RING.x(), mN), mN), RING.cos(RING.multiply(RING.pow(RING.monomial(new Q(4), 0), 2, mN), RING.x(), mN), mN)), RING.add(RING.one(), RING.cos(RING.multiply(RING.pow(RING.monomial(new Q(5), 0), 2, mN), RING.x(), mN), mN)), mN);
  }
}
