package irvine.oeis.a272;
// Generated by gen_seq4.pl 2026-01-20.ack/filtpos at 2026-01-20 19:50

import irvine.math.z.Z;
import irvine.oeis.FilterPositionSequence;
import irvine.oeis.LambdaSequence;

/**
 * A272323 Nonnegative numbers n such that abs(82n^3 - 1228n^2 + 6130n - 5861) is prime.
 * @author Georg Fischer
 */
public class A272323 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A272323() {
    super(1, 0, new LambdaSequence(0, n -> Z.valueOf(82 * n - 1228).multiply(n).add(6130).multiply(n).subtract(5861).abs()), PRIME);
  }
}
