package irvine.oeis.a272;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A272267 The union of centered square numbers (A001844) and centered 9-gonal numbers (A060544).
 * @author Georg Fischer
 */
public class A272267 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A272267() {
    super(1, new long[] {0, 1, 4, 5, 3, 12, 1, 5, 4, 0, 0, 1},
      new long[] {1, -1, 0, 0, 0, -2, 2, 0, 0, 0, 1, -1});
  }
}
