package irvine.oeis.a136;
// Generated by gen_seq4.pl 2025-06-09.ack/polyex

import irvine.oeis.PolynomialFieldSequence;

/**
 * A136592 Column 2 of triangle A136590.
 * E.g.f.: <code>log(1+x+x^2)^2/2</code>.
 * @author Georg Fischer
 */
public class A136592 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A136592() {
    super(2, "[1]", "1,x,+,x,^2,+,log,^2,2,/", 0, 1);
  }
}
