package irvine.oeis.a169;
// Generated by gen_seq4.pl holos at 2021-05-08 19:57
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A169959 a(n) = binomial(10*n, n).
 * @author Georg Fischer
 */
public class A169959 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A169959() {
    super(0, "[[0],[3628800,-102657600, 1172700000,-7236800000, 26932500000,-63273000000, 94500000000,-87000000000, 45000000000,-10000000000],[0, 362880,-8876304, 86112396,-441450324, 1325591001,-2410616376, 2611501074,-1549681956, 387420489]]", "[1, 10]", 0);
  }
}
