package irvine.oeis.a169;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.CoxeterSequence;

/**
 * A169551 Number of reduced words of length n in Coxeter group on 10 generators S_i with relations (S_i)^2 = (S_i S_j)^35 = I.
 * @author Georg Fischer
 */
public class A169551 extends CoxeterSequence {

  /** Construct the sequence. */
  public A169551() {
    super(
      35, 
      10);
  }
}
