package irvine.oeis.a379;
// Generated by gen_seq4.pl 2024-12-30.ack/lambdan at 2024-12-30 19:33

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A379368 Denominators of the partial sums of the reciprocals of the squarefree kernel function (A007947).
 * @author Georg Fischer
 */
public class A379368 extends LambdaSequence {

  /** Construct the sequence. */
  public A379368() {
    super(1, n -> Rationals.SINGLETON.sum(1, n, k -> new Q(Z.ONE, Functions.RAD.z(k))).den());
  }
}
