package irvine.oeis.a379;
// Generated by gen_seq4.pl 2026-07-23.ack/sintrif at 2026-07-23 19:14

import irvine.math.z.Z;
import irvine.oeis.a163.A163801;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A379275 a(n) = A163801(n) mod 2.
 * @author Georg Fischer
 */
public class A379275 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A379275() {
    super(0, (term, n) -> term.and(Z.ONE), "", new A163801());
  }
}
