package irvine.oeis.a356;
// Generated by gen_seq4.pl 2023-09-21/LAMBDA at 2023-09-21 17:48

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A356608 a(n) = n! * Sum_{k=0..floor(n/4)} (n - 4*k)^k/(24^k * (n - 4*k)!).
 * @author Georg Fischer
 */
public class A356608 extends LambdaSequence {

  /** Construct the sequence. */
  public A356608() {
    super(0, n -> Rationals.SINGLETON.sum(0, n / 4, k -> new Q(Z.valueOf(n - 4L * k).pow(k), Z.valueOf(24).pow(k).multiply(Functions.FACTORIAL.z(n - 4 * k)))).multiply(Functions.FACTORIAL.z(n)).num());
  }
}
