package irvine.oeis.a292;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.math.z.Z;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A292311 Expansion of Product_{k&gt;=1} 1/(1 + k^k*x^k).
 * @author Georg Fischer
 */
public class A292311 extends RationalProductTransform {

  /** Construct the sequence. */
  public A292311() {
    super(0, new Builder().g(k -> Z.valueOf(k).pow(k).negate()));
  }
}
