package irvine.oeis.a292;
// Generated by gen_seq4.pl genetf at 2020-12-16 11:03
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;


/**
 * A292387 Expansion of Product_{k&gt;=1} (1 - x^k)^(k*(k+1)*(k+2)/6).
 * G.f.: <code>Product_{k&gt;=1} ((1-x^k)^(k*(k+1)*(k+2)/6))</code>
 * @author Georg Fischer
 */
public class A292387 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A292387() {
    super(0, 1);
  }

  @Override
  protected Z[] advanceF(final long k) {
    return new Z[]{Z.valueOf(-(k * (k + 1) * (k + 2) / 6))};
  }
  
}
