package irvine.oeis.a292;
// Generated by gen_seq4.pl 2026-07-05.ack/multia at 2026-07-05 22:30

import irvine.oeis.DirectSequence;
import irvine.oeis.a000.A000195;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A292621 a(n) = a(n-1) + a(floor(log(n))) with a(1) = 1, a(2) = 2.
 * @author Georg Fischer
 */
public class A292621 extends MultiTransformSequence {

  private static final DirectSequence A000195 = new A000195();

  /** Construct the sequence. */
  public A292621() {
    super(1, (self, n) -> self.a(n - 1).add(self.a(A000195.a(n).intValueExact())), "1,2");
  }
}
