package irvine.oeis.a292;
// Generated by gen_seq4.pl 2025-08-28.ack/lambdan at 2025-08-28 00:25

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A292782 a(n) = E(2n,n)/2, where E(n,x) is the Euler polynomial.
 * @author Georg Fischer
 */
public class A292782 extends LambdaSequence {

  /** Construct the sequence. */
  public A292782() {
    super(1, n -> Z.NEG_ONE.pow(n).multiply(Integers.SINGLETON.sum(1, n - 1, k -> Z.NEG_ONE.pow(k + 1).multiply(Z.valueOf(k).pow(2L * n)))));
  }
}
