package irvine.oeis.a140;
// Generated by gen_seq4.pl knest at 2023-03-02 20:46

import irvine.math.z.Z;
import irvine.math.z.ZUtils;
import irvine.oeis.a000.A000043;

/**
 * A140528 Sum of digits of Mersenne prime exponents.
 * @author Georg Fischer
 */
public class A140528 extends A000043 {
  @Override
  public Z next() {
    return Z.valueOf(ZUtils.digitSum(super.next()));
  }
}
