package irvine.oeis.a102;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.PrimePositionSubsequence;


/**
 * A102768 Numbers k such that 23*k + 11 is prime.
 * @author Georg Fischer
 */
public class A102768 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A102768() {
    super("[[23],[1],[-1]]", "[11]", 0);
  }
}
