package irvine.oeis.a101;
// Generated by gen_seq4.pl 2024-11-13.ack/filnum at 2024-11-13 22:27

import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.FilterNumberSequence;
import irvine.oeis.a033.A033880;

/**
 * A101259 Numbers whose deficiency is 54.
 * @author Georg Fischer
 */
public class A101259 extends FilterNumberSequence {

  private static final DirectSequence A033880 = new A033880();

  /** Construct the sequence. */
  public A101259() {
    super(1, 1, k -> A033880.a(k).equals(Z.valueOf(-54)));
  }
}
