package irvine.oeis.a101;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.PrimePositionSubsequence;


/**
 * A101084 Numbers k such that 97*k + 101 is a prime.
 * @author Georg Fischer
 */
public class A101084 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A101084() {
    super("[[97],[1],[-1]]", "[101]", 0);
  }
}
