package irvine.oeis.a369;
// Generated by gen_seq4.pl 2024-12-01.ack/filtpos at 2024-12-01 23:03

import irvine.oeis.FilterPositionSequence;
import irvine.oeis.a327.A327860;

/**
 * A369037 Numbers k for which A327860(k) is of the form 4m+2, where A327860 is the arithmetic derivative of the primorial base exp-function.
 * @author Georg Fischer
 */
public class A369037 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A369037() {
    super(1, 0, new A327860(), v -> v.mod(4) == 2);
  }
}
