package irvine.oeis.a369;
// Generated by gen_seq4.pl 2024-03-05/tuptraf at 2024-03-06 21:53

import irvine.oeis.a263.A263416;
import irvine.oeis.a263.A263417;
import irvine.oeis.transform.TupleTransformSequence;

/**
 * A369468 a(n) = Product_{k=0..n} ((3*k+1)*(3*k+2))^(n-k).
 * @author Georg Fischer
 */
public class A369468 extends TupleTransformSequence {

  /** Construct the sequence. */
  public A369468() {
    super(0, (n, s) -> s[0].multiply(s[1]), "", new A263416(), new A263417());
  }
}
