package irvine.oeis.a369;
// Generated by gen_seq4.pl 2025-07-15.ack/holos at 2025-07-15 23:51

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A369359 a(n) is the total semiperimeter over all Motzkin polyominoes of length n.
 * 1/2*(1+x^2-(1+x)*(-3*x^2-2*x+1)^(1/2))/x/(-3*x^2-2*x+1)^(1/2)
 * @author Georg Fischer
 */
public class A369359 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A369359() {
    super(0, "[[0],[36,-21,3],[12,-1,-1],[-8,19,-9],[2,-1,-3],[-2,0,2]]", "0,2", 0, 0);
  }
}
