package irvine.oeis.a131;
// Generated by gen_seq4.pl wraptr2 at 2021-10-17 19:42

import irvine.oeis.a005.A005408;
import irvine.oeis.triangle.WrappedRecurrence;

/**
 * A131768 2*(A007318 * A097807) - A000012.
 * @author Georg Fischer
 */
public class A131768 extends WrappedRecurrence {

  /** Construct the sequence. */
  public A131768() {
    super(new A005408(), "1");
    setPlus("1");
  }
}
