package irvine.oeis.a131;
// Generated by gen_seq4.pl trisum/trisum2 at 2023-06-07 16:03

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a051.A051731;
import irvine.oeis.a054.A054525;

/**
 * A131088 2*A051731 - A054525 as infinite lower triangular matrices.
 * @author Georg Fischer
 */
public class A131088 extends AbstractSequence {

  private final A051731 mSeq1 = new A051731();
  private final A054525 mSeq2 = new A054525();

  /** Construct the sequence. */
  public A131088() {
    super(1);
  }

  @Override
  public Z next() {
    return mSeq1.next().multiply2().subtract(mSeq2.next());
  }
}
