package irvine.oeis.a131;
// Generated by ./gen_seq4.pl /diffseq0 at 2022-06-26 10:36

import irvine.oeis.DifferenceSequence;
import irvine.oeis.PrependSequence;

/**
 * A131119 a(n) = (-1)^n * Sum_{i=1..floor(n/2)} i * floor(n/(n-i)).
 * @author Sean A. Irvine
 */
public class A131119 extends DifferenceSequence {

  /** Construct the sequence. */
  public A131119() {
    super(new PrependSequence(new A131174(), 0));
  }
}
