package irvine.oeis.a113;
// Generated by gen_seq4.pl dex (CR.ONE_THIRD).multiply(CR.TWO.log().add(CR.PI.divide(CR.THREE.sqrt()))) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A113476 Decimal expansion of <code>1/3*(log(2) + Pi/sqrt(3))</code>.
 * @author Georg Fischer
 */
public class A113476 extends DecimalExpansionSequence {

  private static final CR N = (CR.ONE_THIRD).multiply(CR.TWO.log().add(CR.PI.divide(CR.THREE.sqrt())));

  @Override
  protected CR getCR() {
    return N;
  }
}
