package irvine.oeis.a113;
// Generated by gen_seq4.pl holos [[0],[16,-8],[0],[-4,4],[2,-4],[0,1]] [1,2,4,8,20] 0 at 2019-12-06 18:14
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.HolonomicRecurrence;

/**
 * A113180 Expansion of 1/sqrt((1-2*x)^2-8*x^4).
 * @author Georg Fischer
 */
public class A113180 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A113180() {
    super(0, "[[0],[16,-8],[0],[-4,4],[2,-4],[0,1]]", "[1,2,4,8,20]", 0);
  }
}
