package irvine.oeis.a056;
// Generated by gen_seq4.pl A060164/parm2 at 2022-03-25 14:15

/**
 * A056495 Number of primitive (period n) periodic palindromes using a maximum of four different symbols.
 * @author Georg Fischer
 */
public class A056495 extends A056271 {

  /** Construct the sequence. */
  public A056495() {
    super(new A056486());
  }
}
