package irvine.oeis.a056;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.prime.PrimePositionSubsequence;


/**
 * A056686 Numbers k such that 50*R_k + 7 is prime, where R_k = 11...1 is the repunit (A002275) of length k.
 * @author Georg Fischer
 */
public class A056686 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A056686() {
    super("[[-13],[10],[-1]]", "[7, 57]", 0);
  }
}
