package irvine.oeis.a056;
// Generated by gen_seq4.pl holfsig/holos at 2024-02-04 22:45

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A056778 Number of 3-element antichains on an unlabeled n-element set; equivalence classes of monotone Boolean functions of n variables with 3 mincuts under action of symmetric group S_n.
 * @author Georg Fischer
 */
public class A056778 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A056778() {
    super(0, "[0, -1, 4, -4, -2, 2, 4, 3, -12, 3, 4, 2, -2, -4, 4, -1]", "0, 0, 0, 2, 9, 30, 84, 202, 437, 872, 1627, 2874, 4853, 7882, 12383, 18902, 28130, 40934, 58391, 81812", 0);
  }
}
