package irvine.oeis.a293;
// Generated by gen_seq4.pl pfprime 2 61 10 +119 9 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.prime.PowerFactorPrimeSequence;

/**
 * A293036 Numbers k such that (61*10^k + 119)/9 is prime.
 * @author Georg Fischer
 */
public class A293036 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A293036() {
    super(1, 2, 61, 10, +119, 9);
  }
}
