package irvine.oeis.a293;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.oeis.a049.A049401;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A293744 Number of sets of nonempty words with a total of n letters over quinary alphabet such that within each prefix of a word every letter of the alphabet is at least as frequent as the subsequent alphabet letter.
 * @author Georg Fischer
 */
public class A293744 extends RationalProductTransform {

  /** Construct the sequence. */
  public A293744() {
    super(0, new Builder().f((k, t) -> t.negate(), new A049401()).g(-1));
  }
}
