package irvine.oeis.a154;
// Generated by gen_seq4.pl andiv 2023-01-11 22:52

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;

/**
 * A154785 Row sums of triangle in A154724.
 * @author Georg Fischer
 */
public class A154785 extends AbstractSequence {

  private final A154786 mSeq1 = new A154786();
  private int mN;

  /** Construct the sequence. */
  public A154785() {
    super(1);
    mN = 0;
  }

  @Override
  public Z next() {
    return mSeq1.next().add(++mN);
  }
}
