package irvine.oeis.a119;
// Generated by gen_seq4.pl holos [[0],[-5,1],[-5,1],[4,-2],[6,-6],[3,-3],[1,1]] [1,1,2,6,19,64] 0 at 2019-12-06 18:14
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A119370 G.f. satisfies: A(x) = 1 + x*A(x)^2 + x^2*(A(x)^2 - A(x)).
 * @author Georg Fischer
 */
public class A119370 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A119370() {
    super(0, "[[0],[-5,1],[-5,1],[4,-2],[6,-6],[3,-3],[1,1]]", "[1,1,2,6,19,64]", 0);
  }
}
