package irvine.oeis.a119;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A119516 Expansion of x*(7*x^3+7*x^2+9*x+1)/(5*x^4+10*x^2+1).
 * @author Georg Fischer
 */
public class A119516 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A119516() {
    super(0, new long[] {0, 1, 9, 7, 7},
      new long[] {1, 0, 10, 0, 5});
  }
}
