package irvine.oeis.a119;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.RADDSequence;


/**
 * A119455 Start with 1027 and repeatedly reverse the digits and add 16 to get the next term.
 * @author Georg Fischer
 */
public class A119455 extends RADDSequence {

  /** Construct the sequence. */
  public A119455() {
    super(10, 1027, 16);
  }
}
