package irvine.oeis.a119;
// Generated by gen_seq4.pl 2025-09-02.ack/rowsum at 2025-09-02 11:14

import irvine.oeis.a071.A071946;
import irvine.oeis.triangle.RowSumSequence;

/**
 * A119254 Row sums of A071946.
 * @author Georg Fischer
 */
public class A119254 extends RowSumSequence {

  /** Construct the sequence. */
  public A119254() {
    super(0, new A071946());
  }
}
