package irvine.oeis.a119;
// Generated by gen_seq4.pl 2024-11-27.ack/lambdan at 2024-11-27 22:04

import irvine.math.z.Binomial;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A119553 Binomial(binomial(2*n,n)*n^2,n).
 * @author Georg Fischer
 */
public class A119553 extends LambdaSequence {

  /** Construct the sequence. */
  public A119553() {
    super(0, n -> Binomial.binomial(Binomial.binomial(2L * n, n).multiply(Z.valueOf(n).square()), Z.valueOf(n)));
  }
}
