package irvine.oeis.a294;
// Generated by gen_seq4.pl holose at 2020-04-12 21:28
// egf: exp(1/((1-x)*(1-x^2))-1)
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A294213 E.g.f.: <code>exp(1/((1-x)*(1-x^2)) - 1)</code>.
 * @author Georg Fischer
 */
public class A294213 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A294213() {
    super(0, "[[0],[0,1],[-1,-1],[-4,-2],[9,2],[5,1],[-5,-1]]", "[1,1,5,25,193,1601,16741]", 5);
    setGfType(1);
  }
}
