package irvine.oeis.a294;
// Generated by gen_seq4.pl 2024-01-25/filnum at 2024-01-26 22:29

import irvine.math.function.Functions;
import irvine.oeis.FilterNumberSequence;

/**
 * A294278 Numbers n such that omega(n) &gt; omega(n+1) (where omega(m) = A001221(m), the number of distinct primes dividing m).
 * @author Georg Fischer
 */
public class A294278 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A294278() {
    super(1, 1, k -> Functions.OMEGA.i(k) > Functions.OMEGA.i(k + 1));
  }
}
