package irvine.oeis.a245;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A245871 Number of length 2+2 0..n arrays with some pair in every consecutive three terms totalling exactly n.
 * @author Georg Fischer
 */
public class A245871 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A245871() {
    super(1, new long[] {0, 10, 15, -15, 3, -1},
      new long[] {1, -3, 2, 2, -3, 1});
  }
}
