package irvine.oeis.a245;
// Generated by gen_seq4.pl 2024-04-10/filter at 2024-04-10 22:07

import irvine.oeis.FilterSequence;
import irvine.oeis.a005.A005900;

/**
 * A245232 Semiprimes of the form (2*n^3+n)/3.
 * @author Georg Fischer
 */
public class A245232 extends FilterSequence {

  /** Construct the sequence. */
  public A245232() {
    super(1, new A005900(), SEMIPRIME);
  }
}
