package irvine.oeis.a214;
// Generated by gen_seq4.pl 2026-04-29.ack/lambmin1k at 2026-04-29 22:34

import irvine.math.function.Functions;
import irvine.oeis.LeastLambdaSequence;

/**
 * A214721 Least m&gt;0 such that 2*n+1+m and n-m are not relatively prime.
 * @author Georg Fischer
 */
public class A214721 extends LeastLambdaSequence {

  /** Construct the sequence. */
  public A214721() {
    super(1, (n, k) -> Functions.GCD.i(2 * n + 1 + k, n - k) != 1, 1, (n, k) -> 1);
  }
}
