package irvine.oeis.a214;
// Generated by gen_seq4.pl eulerxfm -1 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A214157 Expansion of (1/x) * (f(-x^2, -x^11) * f(-x^5, -x^8) * f(-x^6, -x^7)) / (f(-x, -x^12) * f(-x^3, -x^10) * f(-x^4, -x^9)) in powers of x where f(, ) is Ramanujan's general theta function.
 * @author Georg Fischer
 */
public class A214157 extends EulerTransform {

  /** Construct the sequence. */
  public A214157() {
    super(new PeriodicSequence(1, -1, 1, 1, -1, -1, -1, -1, 1, 1, -1, 1, 0), 1);
  }
}
