package irvine.oeis.a214;
// Generated by gen_seq4.pl floor at 2021-08-30 23:16

import irvine.math.cr.CR;
import irvine.math.z.Z;
import irvine.oeis.FloorSequence;

/**
 * A214077 a(n) = floor(e^(n/3)).
 * @author Georg Fischer
 */
public class A214077 extends FloorSequence {
  /** Construct the sequence. */
  public A214077() {
    super(1);
  }

  protected Z evalCR(final long n) {
    return CR.E.pow(CR.valueOf(n).divide(CR.THREE)).floor();
  }

}
