package irvine.oeis.a298;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A298315 Number of nX3 0..1 arrays with every element equal to 0, 1, 3, 4 or 6 king-move adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A298315 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A298315() {
    super(1, "[0,0,-48,-64,-49,49,102,-11,-146,-92,92,133,62,-53,-40,-15,12,4,1,-1]", "3,3,3,9,17,48,94,234,589,1333,3352,8249,19791,49537,121580,298541,742378,1829015", 0, 0);
  }
}
