package irvine.oeis.a298;
// Generated by gen_seq4.pl 2026-01-29.ack/complem at 2026-01-29 18:56

import irvine.math.z.Z;
import irvine.oeis.ComplementSequence;
import irvine.oeis.a235.A235331;

/**
 * A298879 Numbers whose square is not odious.
 * @author Georg Fischer
 */
public class A298879 extends ComplementSequence {

  /** Construct the sequence. */
  public A298879() {
    super(1, Z.ZERO, new A235331());
  }
}
