package irvine.oeis.a298;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A298216 Number of nX3 0..1 arrays with every element equal to 0, 1, 2, 4 or 5 king-move adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A298216 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A298216() {
    super(1, "[0,0,-4,-1,-6,5,-7,7,-4,18,-1,3,-13,1,0,3,-1]", "4,13,20,40,89,195,451,1046,2453,5810,13796,32903,78633,188163,450830", 0, 0);
  }
}
