package irvine.oeis.a298;
// Generated by gen_seq4.pl 2026-03-05.ack/decexp at 2026-03-05 23:18

import irvine.math.cr.CR;
import irvine.math.cr.functions.CrFunctions;
import irvine.math.q.Q;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A298241 Decimal expansion of BesselI(1,2/3)/BesselI(0,2/3).
 * Formula:
 * @author Georg Fischer
 */
public class A298241 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A298241() {
    super(0, CrFunctions.BESSEL_I.cr(1, CR.valueOf(new Q(2, 3))).divide(CrFunctions.BESSEL_I.cr(0, CR.valueOf(new Q(2, 3)))));
  }
}
