package irvine.oeis.a209;
// Generated by gen_seq4.pl 2025-03-31.ack/filter at 2025-03-31 23:38

import irvine.math.function.Functions;
import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A209663 Numbers n with property that n is prime, n+18 is prime and both have equal sum of digits.
 * @author Georg Fischer
 */
public class A209663 extends FilterSequence {

  /** Construct the sequence. */
  public A209663() {
    super(1, new A000040(), p -> {
      final Z p18 = p.add(18);
      return Predicates.PRIME.is(p18) && Functions.DIGIT_SUM.l(p) == Functions.DIGIT_SUM.l(p18);
    });
  }
}
