package irvine.oeis.a209;
// Generated by gen_seq4.pl build/parmof2 at 2022-06-05 23:04

import irvine.oeis.a008.A008655;

/**
 * A209448 a(n) = Pell(n)*A008655(n) for n&gt;=1, with a(0)=1, where A008655 lists the coefficients in (theta_3(x)*theta_3(3*x)+theta_2(x)*theta_2(3*x))^4.
 * @author Georg Fischer
 */
public class A209448 extends A209443 {

  /** Construct the sequence. */
  public A209448() {
    super(0, new A008655());
  }
}
