package irvine.oeis.a209;
// Generated by gen_seq4.pl holos [[-1,-14,-89,-340,-870,-1572,-2058,-1968,-1365,-670,-221,-44,-4],[1]] [9216] 0 at 2019-12-08 00:24
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A209595 Number of 4X4 0..n arrays with every element equal to a diagonal or antidiagonal reflection.
 * @author Georg Fischer
 */
public class A209595 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A209595() {
    super(1, "[[-1,-14,-89,-340,-870,-1572,-2058,-1968,-1365,-670,-221,-44,-4],[1]]", "[9216]", 0);
  }
}
