package irvine.oeis.a122;
// Generated by gen_seq4.pl 2025-07-13.ack/polya at 2025-07-13 21:23

import irvine.oeis.PolynomialFieldSequence;

/**
 * A122940 L.g.f.: A(x) satisfies: A(x+x^2) = 2*A(x) - log(1+x) with A(0)=0; thus A(x) = log(B(x)), where B(x) is g.f. of A122938.
 * new A122938()
 * @author Georg Fischer
 */
public class A122940 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A122940() {
    super(1, "[1]", "x,B,log,n,*", 0, 0, 1, 1, new A122938());
  }
}
