package irvine.oeis.a015;
// Generated by gen_seq4.pl A015323/parmof3 at 2023-07-06 09:57

/**
 * A015276 Gaussian binomial coefficient [ n,3 ] for q = -8.
 * @author Georg Fischer
 */
public class A015276 extends A015323 {

  /** Construct the sequence. */
  public A015276() {
    super(3, 3, -8);
  }
}
