package irvine.oeis.a050;
// Generated by gen_seq4.pl posofnin at 2021-08-06 13:56

import irvine.oeis.PositionOfNSequence;

/**
 * A050009 a(n)=position of n in A050008.
 * @author Georg Fischer
 */
public class A050009 extends PositionOfNSequence {

  /** Construct the sequence. */
  public A050009() {
    super(new A050008());
  }
}
