package irvine.oeis.a050;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A050930 Number of directed loopless multigraphs on 4 nodes with n arcs.
 * @author Georg Fischer
 */
public class A050930 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A050930() {
    super(0, new long[] {1, -1, 2, 8, 24, 43, 92, 128, 207, 240, 254, 226, 196, 133, 
      98, 46, 20, 9, 2},
      new long[] {1, -2, -2, 2, 5, 8, -10, -16, -10, 12, 42, 12, -21, -54, -30, 
      38, 50, 38, -30, -54, -21, 12, 42, 12, -10, -16, -10, 8, 5, 
      2, -2, -2, 1});
  }
}
