package irvine.oeis.a050;
// Generated by gen_seq4.pl parm2 at 2021-08-06 13:56

/**
 * A050023 Numbers k such that A050020(k) &gt; A050020(k+1).
 * @author Georg Fischer
 */
public class A050023 extends A050003 {

  /** Construct the sequence. */
  public A050023() {
    super(new A050020());
  }
}
