package irvine.oeis.a145;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A145389 Digital roots of triangular numbers.
 * @author Georg Fischer
 */
public class A145389 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A145389() {
    super(0, new long[] {0, 1, 3, 6, 1, 6, 3, 1, 9, 9},
      new long[] {1, 0, 0, 0, 0, 0, 0, 0, 0, -1});
  }
}
