package irvine.oeis.a129;
// Generated by gen_seq4.pl 2024-03-27/filter at 2024-03-27 21:37

import irvine.factor.factor.Jaguar;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000567;

/**
 * A129927 3-almost prime octagonal numbers.
 * @author Georg Fischer
 */
public class A129927 extends FilterSequence {

  /** Construct the sequence. */
  public A129927() {
    super(1, new A000567(), v -> Jaguar.factor(v).bigOmega() == 3);
  }
}
