package irvine.oeis.a129;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A129617 <code>a(1) = 0; a(2) = a(3) = 1</code>; for <code>n &gt; 3: a(n) = 16*a(n-2)+14*a(n-3)</code>.
 * @author Georg Fischer
 */
public class A129617 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A129617() {
    super(1, new long[] {0, 0, -1, -1},
      new long[] {-1, 0, 16, 14});
  }
}
