package irvine.oeis.a129;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A129744 a(n) = -(u^n-1)*(v^n-1) with u = 1+sqrt(2), v = 1-sqrt(2).
 * @author Georg Fischer
 */
public class A129744 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A129744() {
    super(1, new long[] {0, 2, 0, 2},
      new long[] {1, -2, -2, 2, 1});
  }
}
