package irvine.oeis.a100;
// Generated by gen_seq4.pl dead at 2024-03-13 19:20

import irvine.oeis.DeadSequence;

/**
 * A100488
 * @author Georg Fischer
 */
public class A100488 extends DeadSequence {

  /** Construct the sequence. */
  public A100488() {
    super(0);
  }
}
