package irvine.oeis.a100;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A100727 Continued fraction expansion of (1/2) [tan(1) + sec(1)].
 * @author Georg Fischer
 */
public class A100727 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A100727() {
    super(0, new long[] {1, 1, 2, 2, -1, -1, -3, -2, 0, 1, 1},
      new long[] {1, 0, 0, 0, -2, 0, 0, 0, 1});
  }
}
