package irvine.oeis.a100;
// Generated by gen_seq4.pl holos [[-6],[-1],[0],[-2],[1]] [1,4,12,30] 0 at 2020-03-14 22:45
// Recurrence: a[n+0]=2*a[n-1]+a[n-3]+6
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A100691 Number of self-avoiding paths with n steps on a triangular lattice in the strip Z <code>x {0,1}</code>.
 * @author Georg Fischer
 */
public class A100691 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A100691() {
    super(0, "[[-6],[-1],[0],[-2],[1]]", "[1,4,12,30]", 0);
  }
}
