package irvine.oeis.a084;
// Generated by gen_seq4.pl 2025-12-20.ack/filnum at 2025-12-20 22:55

import irvine.math.function.Functions;
import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A084898 Numbers k such that k^k*k! + 1 is prime.
 * @author Georg Fischer
 */
public class A084898 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A084898() {
    super(1, 1, k -> Predicates.PRIME.is(Z.valueOf(k).pow(k).multiply(Functions.FACTORIAL.z(k)).add(1)));
  }
}
