package irvine.oeis.a363;
// Generated by gen_seq4.pl 2023-09-20/lambda at 2023-09-21 01:53

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A363514 Sum of divisors of 3*n-1 of form 3*k+1.
 * @author Georg Fischer
 */
public class A363514 extends LambdaSequence {

  /** Construct the sequence. */
  public A363514() {
    super(1, n -> Integers.SINGLETON.sumdiv(3 * n - 1, d -> Z.valueOf(d % 3 != 1 ? 0 : d)));
  }
}
