package irvine.oeis.a363;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-22 13:29

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A363631 Expansion of Sum_{k&gt;0} (1/(1+x^k)^4 - 1).
 * a(n) = sumdiv(n,d,(-1)^d*binom(d+3,3));
 * @author Georg Fischer
 */
public class A363631 extends LambdaSequence {

  /** Construct the sequence. */
  public A363631() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> Z.NEG_ONE.pow(d).multiply(Binomial.binomial(d + 3, 3))));
  }
}
