package irvine.oeis.a363;
// Generated by gen_seq4.pl 2024-04-17/multraf at 2024-04-17 19:29

import irvine.math.z.Z;
import irvine.oeis.a046.A046660;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A363919 a(n) = n^excess(n), where excess(n) = A046660(n).
 * @author Georg Fischer
 */
public class A363919 extends MultiTransformSequence {

  /** Construct the sequence. */
  public A363919() {
    super(1, (self, n) -> Z.valueOf(n).pow(self.s(0)), "", new A046660());
  }
}
