package irvine.oeis.a363;
// Generated by gen_seq4.pl recuf7/holos at 2023-06-02 21:34

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A363267 Squares (A000290) alternating with centered squares (A001844).
 * @author Georg Fischer
 */
public class A363267 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A363267() {
    super(1, "[[0],[-1],[0],[3],[0],[-3],[0],[1]]", "[1,1,4,5,9,13,16]", 0);
  }
}
