package irvine.oeis.a363;
// Generated by gen_seq4.pl 2025-03-12.ack/wpartsf2 at 2025-03-12 21:05

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A363325 Total number of parts coprime to n in the partitions of n into 7 parts.
 * @author Georg Fischer
 */
public class A363325 extends LambdaSequence {

  private static int eval2(final int i, final int j) {
    return Functions.GCD.i(i, j) == 1 ? 1 : 0;
  }

  /** Construct the sequence. */
  public A363325() {
    super(1, n -> Integers.SINGLETON.sum(1, n / 7, o -> Integers.SINGLETON.sum(o, (n - o) / 6, m -> Integers.SINGLETON.sum(m, (n - m - o) / 5, l -> Integers.SINGLETON.sum(l, (n - l - m - o) / 4, k -> Integers.SINGLETON.sum(k, (n - k - l - m - o) / 3, j -> Integers.SINGLETON.sum(j, (n - j - k - l - m - o) / 2, i -> Z.valueOf(eval2(n, i) + eval2(n, j) + eval2(n, k) + eval2(n, l) + eval2(n, m) + eval2(n, o) + eval2(n, n - i - j - k - l - m - o)))))))));
  }
}
