package irvine.oeis.a363;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-27 21:29

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A363871 a(n) = A108625(2*n, 3*n).
 * a(n)=sum(k=0,2*n,(-1)^k * binom(2*n,k)*binom(5*n-k,2*n)^2)
 * @author Georg Fischer
 */
public class A363871 extends LambdaSequence {

  /** Construct the sequence. */
  public A363871() {
    super(0, n -> Integers.SINGLETON.sum(0, 2 * n, k -> Z.NEG_ONE.pow(k).multiply(Binomial.binomial(2L * n, k)).multiply(Binomial.binomial(5L * n - k, 2L * n).square())));
  }
}
