package irvine.oeis.a260;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.recur.PeriodicSequence;
import irvine.oeis.transform.EulerTransform;


/**
 * A260150 Expansion of f(x, x^5)^3 / (f(-x, -x^5) * f(-x^2, -x^2)^2) in powers of x where f(, ) is Ramanujan's general theta function.
 * @author Georg Fischer
 */
public class A260150 extends EulerTransform {

  /** Construct the sequence. */
  public A260150() {
    super(new PeriodicSequence(4, 1, 0, 2, 4, 2, 4, 2, 0, 1, 4, 0), 1);
  }
}
