package irvine.oeis.a260;
// Generated by gen_seq4.pl dex CR.THREE.log().divide(CR.TWO.log()) true 2 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A260595 The binary expansion of log(3)/log(2).
 * @author Georg Fischer
 */
public class A260595 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A260595() {
    super(0, CR.THREE.log().divide(CR.TWO.log()), 2);
  }
}
