package irvine.oeis.a192;
// Generated by gen_seq4.pl 2026-08-19.ack/lambdan at 2026-08-19 21: 55

import irvine.oeis.LambdaSequence;
import irvine.oeis.a022.A022818;
import irvine.oeis.triangle.DirectArray;

/**
 * A192435 Number of terms in n-th derivative of a function composed with itself n times.
 * @author Georg Fischer
 */
public class A192435 extends LambdaSequence {

  private static final DirectArray A022818 = new A022818();

  /** Construct the sequence. */
  public A192435() {
    super(1, n -> A022818.a(n, n));
  }
}
