package irvine.oeis.a253;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a074.A074294;
import irvine.oeis.a130.A130829;

/**
 * A253515 Count down from 2*k to 1, then from 2*(k+1) to 1 and so on.
 * @author Georg Fischer
 */
public class A253515 implements Sequence {

  final Sequence mA074294 = new A074294();
  final Sequence mA130829 = new A130829();
  /** Construct the sequence. */
  public A253515() {
  }
  
  @Override
  public Z next() {
    return mA130829.next().subtract(mA074294.next());
  }

}
