package irvine.oeis.a051;
// Generated by gen_seq4.pl primsol at 2021-02-28 18:46
// DO NOT EDIT here!

import irvine.oeis.a040.A040028;

/**
 * A051085 Primes p such that x^32 = -2 has a solution mod p.
 * @author Georg Fischer
 */
public class A051085 extends A040028 {

  /** Construct the sequence. */
  public A051085() {
    super(32, -2, true);
  }
}
