package irvine.oeis.a051;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A051172 T(n,7), array T as in A051168; a count of Lyndon words; aperiodic necklaces with 7 black beads and n-7 white beads.
 * @author Georg Fischer
 */
public class A051172 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A051172() {
    super(7, new long[] {0, 0, 0, 0, 0, 0, 0, 0, -7, 21, -35, 35, -21, 7},
      new long[] {-7, 49, -147, 245, -245, 147, -49, 14, -49, 147, -245, 245, -147, 
      49, -7});
  }
}
