package irvine.oeis.a075;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a001.A001222;

/**
 * A075795 Number of k, 0&lt;k&lt;=n, such that the resultant of the k-th cyclotomic polynomial and the n-th cyclotomic polynomial is equal to 1.
 * @author Georg Fischer
 */
public class A075795 implements Sequence {

  final Sequence mA001222 = new A001222();
  protected long mN;
  /** Construct the sequence. */
  public A075795() {
    mN = 0;
  }
  
  @Override
  public Z next() {
    ++mN;
    return Z.valueOf(mN).subtract(mA001222.next()).subtract(Z.ONE);
  }

}
