package irvine.oeis.a273;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A273833 Partial sums of the number of active <code>(ON,black)</code> cells in n-th stage of growth of two-dimensional cellular automaton defined by "Rule <code>961"</code>, based on the 5-celled von Neumann neighborhood.
 * @author Georg Fischer
 */
public class A273833 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A273833() {
    super(0, new long[] {1, 2, 13, 5, -7, 3, -1},
      new long[] {1, -3, 2, 2, -3, 1});
  }
}
