package irvine.oeis.a273;
// Generated by gen_seq4.pl ca2elem/partsum at 2021-12-23 22:26

import irvine.oeis.PartialSumSequence;

/**
 * A273447 Partial sums of the number of active (ON,black) cells in n-th stage of growth of two-dimensional cellular automaton defined by "Rule 721", based on the 5-celled von Neumann neighborhood.
 * @author Georg Fischer
 */
public class A273447 extends PartialSumSequence {

  /** Construct the sequence. */
  public A273447() {
    super(new A273443());
  }
}
