package irvine.oeis.a273;
// Generated by gen_seq4.pl A272671/filter at 2023-12-23 22:45

import irvine.math.z.Z;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000027;

/**
 * A273360 Numbers n such that the decimal number concat(5,n) is a square.
 * @author Georg Fischer
 */
public class A273360 extends FilterSequence {

  /** Construct the sequence. */
  public A273360() {
    super(1, new A000027(), v -> new Z("5" + v.toString()).isSquare());
  }
}
