package irvine.oeis.a270;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A270985 Number of active <code>(ON,black)</code> cells at stage <code>2^n-1</code> of the two-dimensional cellular automaton defined by "Rule <code>238"</code>, based on the 5-celled von Neumann neighborhood.
 * @author Georg Fischer
 */
public class A270985 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A270985() {
    super(0, new long[] {1, -3, 1, -1, 10, 8, -8},
      new long[] {1, -8, 21, -22, 8});
  }
}
