package irvine.oeis.a118;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.base.RaddSequence;


/**
 * A118159 Start with 1 and repeatedly reverse the digits and add 64 to get the next term.
 * @author Georg Fischer
 */
public class A118159 extends RaddSequence {

  /** Construct the sequence. */
  public A118159() {
    super(10, 1, 64);
  }
}
