package irvine.oeis.a118;
// Generated by gen_seq4.pl 2025-03-26.ack/sintrif at 2025-03-26 22:40

import irvine.math.function.Functions;
import irvine.oeis.a109.A109611;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A118495 Chen primes written backwards.
 * @author Georg Fischer
 */
public class A118495 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A118495() {
    super(1, (term, n) -> Functions.REVERSE.z(term), "", new A109611());
  }
}
