package irvine.oeis.a118;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.base.RaddSequence;


/**
 * A118615 Start with 1 and repeatedly reverse the digits and add 26 to get the next term.
 * @author Georg Fischer
 */
public class A118615 extends RaddSequence {

  /** Construct the sequence. */
  public A118615() {
    super(10, 1, 26);
  }
}
