package irvine.oeis.a312;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a311.A311521;

/**
 * A312040 Coordination sequence <code>Gal.4.49.4</code> where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A312040 extends A311521 {

  /** Construct the sequence. */
  public A312040() {
    super();
    defineBaseSet(3);
  }
}
