package irvine.oeis.a313;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a310.A310475;

/**
 * A313385 Coordination sequence Gal.6.498.3 where Gal.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A313385 extends A310475 {

  /** Construct the sequence. */
  public A313385() {
    super();
    defineBaseSet(2);
  }
}
