package irvine.oeis.a313;
// Generated by gen_seq4.pl tile1 at 2020-05-30 23:34
// DO NOT EDIT here!

import org.teherba.tile.TilingSequence;

/**
 * A313223 Coordination sequence Gal.5.275.1 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A313223 extends TilingSequence {

  /** Construct the sequence. */
  public A313223() {
    super(0, new String[]
        { "6.3.6.3;A180-1,B300+1,C240+2,D300+3"
        , "6.3.3.3.3;A60+2,A60-2,C180-3,E180+4,C300+3"
        , "6.3.3.3.3;E60+2,A120+3,B60+5,E240+3,C180+5"
        , "6.3.6.3;A240+4,A240-4,A60+4,A60-4"
        , "6.3.3.3.3;C180-1,C300+1,C120+4,B180+4,C0-4"
        });
    defineBaseSet(0);
  }
}
