package irvine.oeis.a313;
// Generated by gen_seq4.pl tile1 at 2020-05-30 23:34
// DO NOT EDIT here!

import org.teherba.tile.TilingSequence;

/**
 * A313941 Coordination sequence Gal.4.151.1 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A313941 extends TilingSequence {

  /** Construct the sequence. */
  public A313941() {
    super(0, new String[]
        { "6.3.3.3.3;B60+2,C300+1,A180+3,C120+5,D0+3"
        , "6.3.3.3.3;C60+2,A300+1,D300+2,B180+4,D120+1"
        , "6.3.3.3.3;A60+2,B300+1,D60+6,D240+4,A240+4"
        , "3.3.3.3.3.3;B240+5,B60+3,A0+5,C120+4,D180+5,C300+3"
        });
    defineBaseSet(0);
  }
}
