package irvine.oeis.a103;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A103627 Let S(n) = {n,1,n}; sequence gives concatenation S(0), S(1), S(2), ...
 * @author Georg Fischer
 */
public class A103627 extends GeneratingFunctionSequence implements Conjectural {


  /** Construct the sequence. */
  public A103627() {
    super(0, new long[] {0, 1, 0, 1, -1, 1},
      new long[] {1, 0, 0, -2, 0, 0, 1});
  }
}
