package irvine.oeis.a103;
// Generated by gen_seq4.pl 2026-04-23.ack/trigf at 2026-04-23 18:40

import irvine.oeis.triangle.GeneratingFunctionTriangle;

/**
 * A103283 Triangle read by rows: T(n,k) is the coefficient of x^k in the monic characteristic polynomial of the n X n matrix with 2's on the diagonal and 1's elsewhere (n &gt;= 1 and  0 &lt;= k &lt;= n). Row 0 consists of the single term 1.
 * @author Georg Fischer
 */
public class A103283 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A103283() {
    super(0, "1,0,-1,0,0,0", "1,2,-2,1,-2,1,0,0,0,0,0,0,0,0,0");
  }
}
