package irvine.oeis.a103;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-27 20:43

import irvine.math.function.Functions;
import irvine.oeis.LambdaSequence;

/**
 * A103624 Quotient F(n(n+1))/{F(n)*F(n+1)}, where F(n) is the n-th Fibonacci number A000045(n).
 * a(n)=fibonacci(n*(n+1))/(fibonacci(n)*fibonacci(n+1))
 * @author Georg Fischer
 */
public class A103624 extends LambdaSequence {

  /** Construct the sequence. */
  public A103624() {
    super(1, n -> {
      return Functions.FIBONACCI.z(n * n + n * 1L).divide(Functions.FIBONACCI.z(n).multiply(Functions.FIBONACCI.z((long) (n + 1))));
    });
  }
}
