package irvine.oeis.a103;
// Generated by gen_seq4.pl A078847/parm3 at 2022-02-14 19:20

/**
 * A103171 Start of nine consecutive primes whose digit reversals are also prime.
 * @author Georg Fischer
 */
public class A103171 extends A103169 {

  /** Construct the sequence. */
  public A103171() {
    super(1, 9);
  }
}
