package irvine.oeis.a103;
// Generated by gen_seq4.pl 2024-06-24/sintrif at 2024-06-24 23:40

import irvine.oeis.transform.SingleTransformSequence;

/**
 * A103565 Primes of the form 3 p^2+2, where p is prime.
 * @author Georg Fischer
 */
public class A103565 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A103565() {
    super(1, (term, n) -> term.square().multiply(3).add(2), "", new A103564());
  }
}
