package irvine.oeis.a378;
// Generated by gen_seq4.pl 2025-07-17.ack/lambdan at 2025-07-18 00:03

import irvine.math.z.Integers;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a369.A369001;

/**
 * A378546 a(n) is the sum of the divisors d of n for which A083345(n/d) is even, where A083345(n) is the numerator of Sum(e/p: n=Product(p^e)).
 * @author Georg Fischer
 */
public class A378546 extends LambdaSequence {

  private static final DirectSequence A369001 = new A369001();

  /** Construct the sequence. */
  public A378546() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> A369001.a(n / d).multiply(d)));
  }
}
