package irvine.oeis.a378;
// Generated by gen_seq4.pl 2026-06-21.ack/arrlamb at 2026-06-21 22:51

import irvine.math.z.Z;
import irvine.oeis.triangle.LambdaArray;

/**
 * A378200 Square array read by upward antidiagonals: T(n,k) = ((k + n - 1)^2 + (k - n + 1)*(-1)^n + (1 - k - n)*(-1)^k + (1 - k - n)*(-1)^(k + n) + 2)/2.
 * @author Georg Fischer
 */
public class A378200 extends LambdaArray {

  /** Construct the sequence. */
  public A378200() {
    super(1, 1, 1, 1, (n, k) -> Z.valueOf(k + n - 1).square().add(Z.NEG_ONE.pow(n).multiply(k - n + 1)).add(Z.NEG_ONE.pow(k).multiply(1 - k - n)).add(Z.NEG_ONE.pow(k + n).multiply(1 - k - n).add(2)).divide(2));
  }
}
