package irvine.oeis.a388;
// Generated by gen_seq4.pl 2025-09-27.ack/lambdan at 2025-09-27 20:48

import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a003.A003961;
import irvine.oeis.a033.A033885;

/**
 * A388975 a(n) = A033885(A003961(n)), where A033885(n) = 3*n-sigma(n), and A003961 is fully multiplicative with a(p) = nextprime(p).
 * @author Georg Fischer
 */
public class A388975 extends LambdaSequence {

  private static final DirectSequence A003961 = new A003961();
  private static final DirectSequence A033885 = new A033885();

  /** Construct the sequence. */
  public A388975() {
    super(1, n -> A033885.a(A003961.a(n)));
  }
}
