package irvine.oeis.a388;
// Generated by gen_seq4.pl 2025-09-21.ack/holos at 2025-09-21 22:49

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A388411 a(n) = Sum_{k=0..n} 3^(n-k) * binomial(n,k) * binomial(n+4,k).
 * @author Georg Fischer
 */
public class A388411 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A388411() {
    super(0, "[[0],[-24,4,16,4],[0,-36,-36,-8],[0,4,5,1]]", "1", 0, 0);
  }
}
