package irvine.oeis.a388;
// Generated by gen_seq4.pl 2025-09-23.ack/polyx at 2025-09-23 20:23

import irvine.oeis.PolynomialFieldSequence;

/**
 * A388731 Expansion of (1/x) * Series_Reversion( x / ((1+x)^2 * (x+(1+x)^4)) ).
 * @author Georg Fischer
 */
public class A388731 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A388731() {
    super(0, "[1],[1,1]", "x,p1,^2,x,p1,^4,+,*,/,rev,x,/", 1, 0);
  }
}
