package irvine.oeis.a339;
// Generated by gen_seq4.pl 2023-10-21/pairtra at 2023-10-22 21:59

import irvine.oeis.a023.A023358;
import irvine.oeis.a323.A323633;
import irvine.oeis.transform.PairTransformSequence;

/**
 * A339420 Number of compositions (ordered partitions) of n into an even number of cubes.
 * @author Georg Fischer
 */
public class A339420 extends PairTransformSequence {

  /** Construct the sequence. */
  public A339420() {
    super(0, new A023358(), new A323633(), (n, u, v) -> u.add(v).divide2());
  }
}
