package irvine.oeis.a097;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A097064 Expansion of (1-4x+6x^2)/(1-2x)^2.
 * @author Georg Fischer
 */
public class A097064 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A097064() {
    super(0, new long[] {1, -4, 6},
      new long[] {1, -4, 4});
  }
}
