package irvine.oeis.a097;
// Generated by gen_seq4.pl 2026-09-06.ack/rambdad at 2026-09-06 21: 22

/**
 * A097424 Denominator of Product_{k=1..n} H(k), where H(k) = Sum_{j=1..k} 1/j, the k-th harmonic number.
 * @author Georg Fischer
 */
public class A097424 extends A097423 {

  /** Construct the sequence. */
  public A097424() {
    super.setDenominator();
  }
}
