package irvine.oeis.a097;
// Generated by gen_seq4.pl mult at 2022-07-21 21:19

import irvine.math.z.Z;
import irvine.oeis.MultiplicativeSequence;

/**
 * A097988 a(n) = Sum_{d dividing n} tau(d)^3 = (Sum_{d dividing n} tau(d))^2.
 * @author Georg Fischer
 */
public class A097988 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A097988() {
    super(1, (p, e) -> Z.valueOf(e + 1).multiply(e + 2).divide2().square());
  }
}
