package irvine.oeis.a097;
// Generated by gen_seq4.pl trigf 1, 1, 0 1, 0, -1, 0, 0, 0 at 2020-02-18 21:32
// 0
// 
// DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionTriangle;

/**
 * A097806 Riordan array <code>(1+x, 1)</code> read by rows.
 * @author Georg Fischer
 */
public class A097806 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A097806() {
    super(0, new long[] {1, 1, 0}, new long[] {1, 0, -1, 0, 0, 0});
  }
}
