package irvine.oeis.a097;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a033.A033051;

/**
 * A097261 Numbers whose set of base 15 digits is {0,E}, where E base 15 = 14 base 10.
 * @author Georg Fischer
 */
public class A097261 implements Sequence {

  final Sequence mA033051 = new A033051();
  /** Construct the sequence. */
  public A097261() {
  }
  
  @Override
  public Z next() {
    return Z.valueOf(14).multiply(mA033051.next());
  }

}
