package irvine.oeis.a205;
// Generated by gen_seq4.pl mckay 30A A at 2020-10-07 19:31
// DO NOT EDIT here!

import irvine.oeis.McKayThompsonSequence;


/**
 * A205826 McKay-Thompson series of class 30A for the Monster group with a(0) = -3.
 * @author Georg Fischer
 */
public class A205826 extends McKayThompsonSequence {

  /**
   * Construct the sequence.
   */
  public A205826() {
    super("30A", new long[]{1, -3});
  }
}
