package irvine.oeis.a205;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A205937 Number of (n+1) X 2 0..3 arrays with no 2 X 2 subblock having the number of clockwise edge increases equal to the number of counterclockwise edge increases in its adjacent leftward or upward neighbors.
 * @author Georg Fischer
 */
public class A205937 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A205937() {
    super(1, "[0,80,96,1011,2140,2204,1504,626,132,16,0,-1]", "256,1776,12712,91440,656272,4711264,33827496,242859696,1743558448,12517828752", 0, 0);
  }
}
