package irvine.oeis.a205;
// Generated by gen_seq4.pl A204892/parm3 at 2022-05-03 21:51

import irvine.oeis.a002.A002378;
import irvine.oeis.a204.A204890;
/**
 * A205016 Ordered differences of oblong numbers.
 * @author Georg Fischer
 */
public class A205016 extends A204890 {

  /** Construct the sequence. */
  public A205016() {
    super(new A002378(), 0);
  }
}
