package irvine.oeis.a205;
// Generated by gen_seq4.pl A204892/parm4 at 2022-05-02 19:06

import irvine.oeis.a006.A006094;
import irvine.oeis.a204.A204892;

/**
 * A205148 Least s(k) such that n divides s(k)-s(j) for some j&lt;k, where s(j)=prime(j)*prime(j+1).
 * @author Georg Fischer
 */
public class A205148 extends A204892 {

  /** Construct the sequence. */
  public A205148() {
    super(new A006094(), 1, 3);
  }
}
