package irvine.oeis.a286;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.oeis.a001.A001694;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A286305 Number of partitions of n into powerful parts (A001694).
 * @author Georg Fischer
 */
public class A286305 extends RationalProductTransform {

  /** Construct the sequence. */
  public A286305() {
    super(0, new Builder().h(new A001694()));
  }
}
