package irvine.oeis.a286;
// Generated by gen_seq4.pl mortra at 2021-09-23 21:42

import irvine.oeis.MorphismTransform;
import irvine.oeis.a080.A080764;

/**
 * A286996 {0-&gt;000, 11-&gt;null}-transform of the Sturmian word A080764.
 * @author Georg Fischer
 */
public class A286996 extends MorphismTransform {

  /** Construct the sequence. */
  public A286996() {
    super(new A080764(), "0->000, 11->");
  }
}
