package irvine.oeis.a286;
// Generated by gen_seq4.pl pairing/parmof5 at 2023-10-04 12:43

import irvine.oeis.a001.A001511;
import irvine.oeis.a049.A049820;
import irvine.oeis.a285.A285729;

/**
 * A286259 Compound filter: a(n) = P(A001511(n), A049820(n)), where P(n,k) is sequence A000027 used as a pairing function.
 * @author Georg Fischer
 */
public class A286259 extends A285729 {

  /** Construct the sequence. */
  public A286259() {
    super(1, new A001511(), 1, new A049820(), 1);
  }
}
