package irvine.oeis.a286;
// Generated by gen_seq4.pl mortra at 2021-09-23 21:42

import irvine.oeis.a171.A171588;
import irvine.oeis.base.MorphismTransform;

/**
 * A286665 {0-&gt;01}-transform of the Pell word, A171588.
 * @author Georg Fischer
 */
public class A286665 extends MorphismTransform {

  /** Construct the sequence. */
  public A286665() {
    super(new A171588(), "0->01");
  }
}
