package irvine.oeis.a286;
// Generated by gen_seq4.pl adicroot/parmof6 at 2024-01-26 22:58

/**
 * A286841 One of the two successive approximations up to 13^n for 13-adic integer sqrt(-1). Here the 8 (mod 13) case (except for n=0).
 * @author Georg Fischer
 */
public class A286841 extends A286840 {

  /** Construct the sequence. */
  public A286841() {
    super(0, 2, +1, 4, 13, "0, 8");
  }
}
