package irvine.oeis.a286;
// Generated by gen_seq4.pl ca2elem/ca2inb at 2021-12-23 22:26

import irvine.math.z.Z;
import irvine.oeis.ca.FiveNeighbor2DAutomaton;

/**
 * A286507 Binary representation of the diagonal from the corner to the origin of the n-th stage of growth of the two-dimensional cellular automaton defined by "Rule 190", based on the 5-celled von Neumann neighborhood.
 * @author Georg Fischer
 */
public class A286507 extends FiveNeighbor2DAutomaton {

  /** Construct the sequence. */
  public A286507() {
    super(190);
  }

  @Override
  public Z next() {
    return super.nextCornerOriginB();
  }
}
