package irvine.oeis.a286;
// Generated by gen_seq4.pl holfsig/holos at 2023-05-05 23:17

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A286187 Number of connected induced (non-null) subgraphs of the web graph with 3n nodes.
 * @author Georg Fischer
 */
public class A286187 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A286187() {
    super(1, "[0,-16,16,52,-76,-17,80,-50,12,-1]", "6,33,188,985,4990,24645,119712,574225,2727218,12847821,60115060,279652793,1294441894,5965567125", 0);
  }
}
