package irvine.oeis.a091;
// Generated by gen_seq4.pl holsig2/holos at 2023-08-09 20:27

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A091433 a(n)=2*3^n - 18*4^n + 24*5^n.
 * @author Georg Fischer
 */
public class A091433 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A091433() {
    super(0, "[0, 60,-47, 12,-1]", "8, 54, 330", 0);
  }
}
