package irvine.oeis.a384;
// Generated by gen_seq4.pl 2025-05-30.ack/polya at 2025-05-30 21:48

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a090.A090358;

/**
 * A384305 Expansion of Product_{k&gt;=1} 1/(1 - k*x)^((5/6)^k).
 * new A090358()
 * @author Georg Fischer
 */
public class A384305 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A384305() {
    super(0, "[1]", "x,S,^30", 0, 0, 1, 1, new A090358());
  }
}
