package irvine.oeis.a384;
// Generated by gen_seq4.pl 2025-07-01.ack/lambdan at 2025-07-01 16:42

import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A384852 a(n) = 2*binomial(n,2) + 3*binomial(n,3) + 4*binomial(n,4).
 * @author Georg Fischer
 */
public class A384852 extends LambdaSequence {

  /** Construct the sequence. */
  public A384852() {
    super(0, n -> Z.valueOf(n).subtract(3).multiply(n).add(8).multiply(n).subtract(6).multiply(n).divide(6));
  }
}
