package irvine.oeis.a384;
// Generated by gen_seq4.pl 2026-01-11.ack/parmof7 at 2026-01-11 21:52

/**
 * A384802 Square array A(n,k), n &gt;= 0, k &gt;= 0, read by antidiagonals downwards, where column k is the expansion of e.g.f. B(x)^k, where B(x) is the e.g.f. of A213109.
 * @author Georg Fischer
 */
public class A384802 extends A384801 {

  /** Construct the sequence. */
  public A384802() {
    super(0, -3, 3, 1, -1, 1, -1);
  }
}
