package irvine.oeis.a219;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A219003 Unmatched value maps: number of 2 X n binary arrays indicating the locations of corresponding elements not equal to any horizontal, diagonal or antidiagonal neighbor in a random 0..2 2 X n array.
 * @author Georg Fischer
 */
public class A219003 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A219003() {
    super(1, "[0,1,6,9]", "[1,-4,3,-9]");
  }
}
