package irvine.oeis.a219;
// Generated by gen_seq4.pl 2024-05-27/lambdan at 2024-05-28 02:23

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A219549 Smallest prime factor of 2^(8n) + 1.
 * @author Georg Fischer
 */
public class A219549 extends LambdaSequence {

  /** Construct the sequence. */
  public A219549() {
    super(1, n -> Functions.LPF.z(Z.TWO.pow(8 * n).add(1)));
  }
}
