package irvine.oeis.a300;
// Generated by gen_seq4.pl 2025-02-12.ack/polyx at 2025-02-12 23:23

import irvine.oeis.PolynomialFieldSequence;

/**
 * A300735 E.g.f. A(x) satisfies: [x^n] A(x)^(2*n) = (n+1) * [x^(n-1)] A(x)^(2*n) for n&gt;=1.
 * exp(x*(A(x)-x*dif(A(x)))/(A(x)-2*x*dif(A(x))))
 * @author Georg Fischer
 */
public class A300735 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A300735() {
    super(0, "[[1]]", ";x;A;x;A;dif;*;-;*;A;2;x;*;A;dif;*;-;/;exp", 0, 1);
  }
}
