package irvine.oeis.a221;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A221859 Expansion of (1-3*x+x^2)*(1-2*x)/(1-9*x+28*x^2-35*x^3+15*x^4-x^5).
 * @author Georg Fischer
 */
public class A221859 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A221859() {
    super(0, new long[] {1, -5, 7, -2},
      new long[] {1, -9, 28, -35, 15, -1});
  }
}
