package irvine.oeis.a221;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A221416 Number of n X 5 arrays of occupancy after each element stays put or moves to some horizontal or antidiagonal neighbor, with every occupancy equal to zero or two.
 * @author Georg Fischer
 */
public class A221416 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A221416() {
    super(1, "[0,7072,0,-197190,0,978022,0,7351166,0,-40860150,0,-95749783,0,150123806,0,-81585322,0,22802458,0,-3590954,0,318164,0,-14620,0,276,0,-1]", "0,84,0,17792,0,3813004,0,817415641,0,175230221888,0,37564072017396,0,8052596858631830,0,1726232153308945597,0,370051730646797787514,0,79327848710774305638388,0,17005480743351155889065248,0,3645458436139606587349879765,0,781475537806495535924444328220", 0, 0);
  }
}
