package irvine.oeis.a177;
// Generated by gen_seq4.pl dex CR.valueOf(85).add(CR.valueOf(9029).sqrt()).divide(CR.valueOf(82)) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A177972 Decimal expansion of (85+sqrt(9029))/82.
 * @author Georg Fischer
 */
public class A177972 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A177972() {
    super(CR.valueOf(85).add(CR.valueOf(9029).sqrt()).divide(CR.valueOf(82)));
  }
}
