package irvine.oeis.a346;
// Generated by gen_seq4.pl 2025-06-09.ack/polyex

import irvine.oeis.PolynomialFieldSequence;

/**
 * A346889 Expansion of e.g.f. 1 / (1 - x^3 * exp(x) / 3!).
 * E.g.f.: <code>1/(1-x^3*exp(x)/6)</code>.
 * @author Georg Fischer
 */
public class A346889 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A346889() {
    super(0, "[1]", "1,1,x,^3,x,exp,*,6,/,-,/", 0, 1);
  }
}
