package irvine.oeis.a346;
// Generated by gen_seq4.pl holos at 2024-02-08 23:00

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A346048 a(0) = ... = a(3) = 1; a(n) = Sum_{k=1..n-4} a(k) * a(n-k-4).
 * @author Georg Fischer
 */
public class A346048 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A346048() {
    super(0, "[[0], [-210, 29, -1], [420, -58, 2], [1482, -231, 9], [2640, -460, 20], [4170, -873, 45], [1200, -224, 10], [-690, 287, -25], [-1680, 660, -60], [-1230, 663, -75], [-420, 334, -50], [-90, 139, -29], [0, 48, -12], [-42, -35, 7], [-48, -12, 6], [-30, 5, 5], [0, 16, 4]]", "1, 1, 1, 1, 0, 1, 2, 3, 3, 3, 5, 9, 15, 19, 24, 35, 59");
  }
}
