package irvine.oeis.a346;
// Generated by gen_seq4.pl deris at 2021-10-28 23:42
// DO NOT EDIT here!

import irvine.oeis.a002.A002294;
import irvine.oeis.transform.Stirling2TransformSequence;

/**
 * A346766 a(n) = Sum_{k=0..n} Stirling2(n,k) * binomial(5*k,k) / (4*k + 1).
 *
 * @author Georg Fischer
 */
public class A346766 extends Stirling2TransformSequence {

  /** Construct the sequence. */
  public A346766() {
    super(new A002294(), 0);
  }
}
