package irvine.oeis.a301;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A301725 Partial sums of <code>A301724</code>.
 * @author Georg Fischer
 */
public class A301725 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A301725() {
    super(0, new long[] {1, 4, 0, 6, 1, 3, 1, 6, 0, 4, 1},
      new long[] {1, -3, 4, -4, 4, -4, 4, -4, 4, -4, 3, -1});
  }
}
