package irvine.oeis.a301;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A301780 Number of nX4 0..1 arrays with every element equal to 0, 1, 2 or 3 horizontally or vertically adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A301780 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A301780() {
    super(1, "[0,-64,-16,20,13,-1]", "8,128,1808,25872", 0, 0);
  }
}
