package irvine.oeis.a301;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A301962 Number of nX6 0..1 arrays with every element equal to 0, 1 or 4 horizontally or antidiagonally adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A301962 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A301962() {
    super(1, "[0,0,1,-3,5,1,-3,-1,-7,-8,4,8,1,-1]", "13,22,74,219,749,2544,8705,29750,101869,348726,1194018,4088095", 0, 0);
  }
}
