package irvine.oeis.a301;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-22 13:29

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A301419 a(n) = [x^n] Sum_{k&gt;=0} x^k/Product_{j=1..k} (1 - n*j*x).
 * a(n) = sum(k=0,n,n^(n-k)*stirl(n,k,2));
 * @author Georg Fischer
 */
public class A301419 extends LambdaSequence {

  /** Construct the sequence. */
  public A301419() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Z.valueOf(n).pow(n - k).multiply(Functions.STIRLING2.z((long) n, (long) k))));
  }
}
