package irvine.oeis.a301;
// Generated by ./gen_seq4.pl /partsum at 2022-06-25 09:09

import irvine.oeis.PartialSumSequence;
import irvine.oeis.a049.A049219;

/**
 * A301994 Number of n X 3 0..1 arrays with every element equal to 1, 2 or 4 horizontally or antidiagonally adjacent elements, with upper left element zero.
 * @author Sean A. Irvine
 */
public class A301994 extends PartialSumSequence {

  /** Construct the sequence. */
  public A301994() {
    super(1, new A049219());
  }
}
