package irvine.oeis.a301;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.oeis.a010.A010872;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A301588 Expansion of Product_{k&gt;=1} (1 + x^k)^(mod(k,3)).
 * @author Georg Fischer
 */
public class A301588 extends RationalProductTransform {

  /** Construct the sequence. */
  public A301588() {
    super(0, new Builder().f((k, t) -> t.negate(), new A010872()).g(-1));
  }
}
