package irvine.oeis.a164;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.CoxeterSequence;

/**
 * A164969 Number of reduced words of length n in Coxeter group on 27 generators <code>S_i</code> with relations <code>(S_i)^2 = (S_i S_j)^8 =</code> I.
 * @author Georg Fischer
 */
public class A164969 extends CoxeterSequence {

  /** Construct the sequence. */
  public A164969() {
    super(
      8, 
      27);
  }
}
