package irvine.oeis.a164;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A164871 The number of permutations of length n that can be sorted by 3 pop stacks in parallel.
 * @author Georg Fischer
 */
public class A164871 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A164871() {
    super(0, new long[] {1, -13, 63, -148, 177, -98, 18},
      new long[] {1, -14, 75, -201, 288, -216, 72});
  }
}
