package irvine.oeis.a164;
// Generated by gen_seq4.pl 2026-02-01.ack/filter at 2026-02-01 21:48

import irvine.math.function.Functions;
import irvine.oeis.FilterSequence;
import irvine.oeis.a000.A000040;

/**
 * A164318 Primes p such that the sum of divisors of p-1 is larger than 2*p.
 * @author Georg Fischer
 */
public class A164318 extends FilterSequence {

  /** Construct the sequence. */
  public A164318() {
    super(1, new A000040(), p -> Functions.SIGMA1.z(p.subtract(1)).compareTo(p.multiply(2)) > 0);
  }
}
