package irvine.oeis.a008;
// Generated by gen_seq4.pl latcoors at 2020-07-22 14:21

import irvine.oeis.LatticeCoordinationSequence;


/**
 * A008355 Coordination sequence for <code>D_5</code> lattice.
 * @author Georg Fischer
 */
public class A008355 extends LatticeCoordinationSequence {

  /** Construct the sequence. */
  public A008355() {
    super("D", 5);
  }
}
