package irvine.oeis.a139;
// Generated by gen_seq4.pl modpow3 7 6 at 2020-03-09 17:27
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A139786 <code>a(n) = 7^n mod 6^n</code>.
 * @author Georg Fischer
 */
public class A139786 implements Sequence {

  private int mN = 0;
  private final Z mBase = Z.SEVEN;
  private final Z mMod = Z.SIX;

  @Override
  public Z next() {
    final Z modulus = mMod.pow(mN);
    return mBase.modPow(Z.valueOf(mN++), modulus);
  }
}
