package irvine.oeis.a139;
// Generated by gen_seq4.pl diffseq at 2020-06-21 22:58
// DO NOT EDIT here!

import irvine.oeis.DifferenceSequence;
import irvine.oeis.a000.A000668;

/**
 * A139231 First differences of Mersenne primes A000668.
 * @author Georg Fischer
 */
public class A139231 extends DifferenceSequence {

  /** Construct the sequence. */
  public A139231() {
    super(new A000668());
  }
}
