package irvine.oeis.a139;
// Generated by gen_seq4.pl knowna4/simtraf at 2023-09-26 15:09

import irvine.factor.factor.Jaguar;
import irvine.oeis.a000.A000041;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A139055 Sum of proper divisors of the number of partitions of n.
 * @author Georg Fischer
 */
public class A139055 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A139055() {
    super(1, new A000041(), v -> Jaguar.factor(v).sigma().subtract(v));
    super.next();
  }
}
