package irvine.oeis.a139;
// Generated by gen_seq4.pl eulerper 0 36 2, -3, 4, -1, 2, 0, 2, -1, 4, -3, 2, 1, 2, -3, 4, -1, 2, -2, 2, -1, 4, -3, 2, 1, 2, -3, 4, -1, 2, 0, 2, -1, 4, -3, 2, 0 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A139213 Expansion of <code>phi(q) * phi(-q^18) / (phi(-q^3) * phi(-q^6))</code> in powers of q where <code>phi()</code> is a Ramanujan theta function.
 * @author Georg Fischer
 */
public class A139213 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A139213() {
    super(new PeriodicSequence(2, -3, 4, -1, 2, 0, 2, -1, 4, -3, 2, 1, 2, -3, 4, -1, 2, -2, 2, -1, 4, -3, 2, 1, 2, -3, 4, -1, 2, 0, 2, -1, 4, -3, 2, 0), 0);
  }
}
