package irvine.oeis.a060;
// Generated by gen_seq4.pl egfsi at 2021-12-01 15:37

import irvine.math.group.PolynomialRingField;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A060909 E.g.f.: exp(x*exp(x*exp(x)) + 1/3*x^3*exp(x*exp(x))^3).
 * E.g.f.: exp(x*exp(x*exp(x)) + 1/3*x^3*exp(x*exp(x))^3)
 * @author Georg Fischer
 */
public class A060909 implements Sequence {

  private static final PolynomialRingField<Q> RING = new PolynomialRingField<>(Rationals.SINGLETON);
  private int mN = -1;
  private Z mF = Z.ONE;

  @Override
  public Z next() {
    if (++mN != 0) {
      mF = mF.multiply(mN);
    }
    return RING.exp(RING.add(RING.multiply(RING.x(), RING.exp(RING.multiply(RING.x(), RING.exp(RING.x(), mN), mN), mN), mN), RING.multiply(RING.multiply(RING.series(RING.one(), RING.monomial(new Q(3), 0), mN), RING.pow(RING.x(), 3, mN), mN), RING.pow(RING.exp(RING.multiply(RING.x(), RING.exp(RING.x(), mN), mN), mN), 3, mN), mN)), mN).coeff(mN).multiply(mF).toZ();
  }
}
