package irvine.oeis.a060;
// Generated by gen_seq4.pl n2 at 2022-04-08 22:12

import irvine.math.z.Z;
import irvine.oeis.a151.A151800;

/**
 * A060264 First prime after 2n.
 * @author Georg Fischer
 */
public class A060264 extends A151800 {

  @Override
  public Z next() {
    final Z result = super.next();
    super.next();
    return result;
  }
}
