package irvine.oeis.a057;
// Generated by gen_seq4.pl sumsi/sumgcd at 2021-11-20 22:12

import irvine.math.LongUtils;
import irvine.math.z.Z;
import irvine.oeis.Sequence1;

/**
 * A057660 a(n) = Sum_{k=1..n} n/gcd(n,k).
 * @author Georg Fischer
 */
public class A057660 extends Sequence1 {

  private int mN = 0;

  @Override
  public Z next() {
    ++mN;
    Z sum = Z.ZERO;
    for (int k = 1; k <= mN; ++k) {
      final long gd = LongUtils.gcd(mN, k);
      sum = sum.add(Z.valueOf(mN / gd));
    }
    return sum;
  }
}
