package irvine.oeis.a316;
// Generated by gen_seq4.pl egfsi at 2021-12-01 15:37

import irvine.math.group.PolynomialRingField;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.Sequence0;

/**
 * A316778 a(n) = exp(-1/2) * Sum_{k&gt;=0} H_n(k) / (k!*2^k), where H_n(x) is n-th Hermite polynomial.
 * E.g.f.: exp(exp(2*x)/2 - x^2 - 1/2)
 * @author Georg Fischer
 */
public class A316778 extends Sequence0 {

  private static final PolynomialRingField<Q> RING = new PolynomialRingField<>(Rationals.SINGLETON);
  private int mN = -1;
  private Z mF = Z.ONE;

  @Override
  public Z next() {
    if (++mN != 0) {
      mF = mF.multiply(mN);
    }
    return RING.exp(RING.subtract(RING.subtract(RING.series(RING.exp(RING.monomial(Q.TWO, 1), mN), RING.monomial(Q.TWO, 0), mN), RING.pow(RING.x(), 2, mN)), RING.series(RING.one(), RING.monomial(Q.TWO, 0), mN)), mN).coeff(mN).multiply(mF).toZ();
  }
}
