package irvine.oeis.a111;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.PrimePositionSubsequence;


/**
 * A111226 Numbers n such that 5*n + 12 is prime.
 * @author Georg Fischer
 */
public class A111226 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A111226() {
    super("[[5],[1],[-1]]", "[12]", 0);
  }
}
