package irvine.oeis.a111;
// Generated by gen_seq4.pl decexp at 2021-07-27 22:38

import irvine.math.cr.CR;
import irvine.oeis.cons.DecimalExpansionSequence;
/**
 * A111197 Decimal expansion of (Pi!)! = gamma(gamma(Pi+1)+1).
 * Formula: Gamma(Gamma(Pi+1)+1)
 * @author Georg Fischer
 */
public class A111197 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A111197() {
    super(4, CR.PI.add(CR.ONE).gamma().add(CR.ONE).gamma());
  }
}
