package irvine.oeis.a304;
// Generated by gen_seq4.pl dex CR.PI.multiply(CR.THREE.sqrt()) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A304656 Decimal expansion of Pi*sqrt(3).
 * @author Georg Fischer
 */
public class A304656 extends DecimalExpansionSequence {

  private static final CR N = CR.PI.multiply(CR.THREE.sqrt());

  @Override
  protected CR getCR() {
    return N;
  }
}
