package irvine.oeis.a304;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A304304 Number of nX2 0..1 arrays with every element unequal to 0, 1, 2, 3 or 5 king-move adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A304304 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A304304() {
    super(1, "[0,0,-8,-6,3,3,-1]", "2,8,23,65,192", 0, 0);
  }
}
