package irvine.oeis.a304;
// Generated by gen_seq4.pl 2025-07-03.ack/polyx at 2025-07-03 22:12

import irvine.oeis.PolynomialFieldSequence;

/**
 * A304454 G.f. satisfies: A(x) = 1 / (1/x - 1 - A(A(x))), with A(0) = 0.
 * @author Georg Fischer
 */
public class A304454 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A304454() {
    super(0, "[0,1],[1,-1]", "x,p1,A,sub,<1,-,/", 1, 0);
  }
}
