package irvine.oeis.a304;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A304162 <code>a(n) = n^4 - 3*n^3 + 9*n^2 - 7*n + 5 (n&gt;=1)</code>.
 * @author Georg Fischer
 */
public class A304162 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A304162() {
    super(1, new long[] {0, 5, -6, 20, 0, 5},
      new long[] {1, -5, 10, -10, 5, -1});
  }
}
