package irvine.oeis.a304;
// Generated by gen_seq4.pl convprom/convprod at 2023-07-10 14:24

import irvine.oeis.a000.A000009;
import irvine.oeis.a000.A000984;
import irvine.oeis.transform.ConvolutionProduct;

/**
 * A304823 Convolution of number of partitions into distinct parts and central binomial coefficients.
 * @author Georg Fischer
 */
public class A304823 extends ConvolutionProduct {

  /** Construct the sequence. */
  public A304823() {
    super(0, "1, 1", new A000009(), new A000984());
  }
}
