package irvine.oeis.a304;
// Generated by gen_seq4.pl A059805/parm4 at 2022-12-27 00:44

import irvine.oeis.a033.A033308;
import irvine.oeis.a059.A059805;

/**
 * A304652 Digits of the Copeland-Erd\u0151s constant taken in groups of five digits.
 * @author Georg Fischer
 */
public class A304652 extends A059805 {

  /** Construct the sequence. */
  public A304652() {
    super(new A033308(), 0, 5, 1);
  }
}
