package irvine.oeis.a073;
// Generated by gen_seq4.pl A114350/parmof3 at 2023-08-16 21:40

import irvine.oeis.a114.A114350;

/**
 * A073337 Primes of the form 4*k^2 - 10*k + 7 with k positive.
 * @author Georg Fischer
 */
public class A073337 extends A114350 {

  /** Construct the sequence. */
  public A073337() {
    super(1, 1, x -> x.pow(2).multiply(4).add(x.multiply(-10)).add(+7));
  }
}
