package irvine.oeis.a280;
// Generated by gen_seq4.pl dex CR.valueOf(12).multiply(CR.PI.divide(CR.valueOf(12)).sin()) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A280819 Decimal expansion of <code>12*sin(Pi/12)</code>.
 * @author Georg Fischer
 */
public class A280819 extends DecimalExpansionSequence {

  private static final CR N = CR.valueOf(12).multiply(CR.PI.divide(CR.valueOf(12)).sin());

  @Override
  protected CR getCR() {
    return N;
  }
}
