package irvine.oeis.a280;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.oeis.a000.A000040;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A280245 Expansion of Product_{k&gt;=1} (1 + x^prime(k))^2.
 * @author Georg Fischer
 */
public class A280245 extends RationalProductTransform {

  /** Construct the sequence. */
  public A280245() {
    super(0, new Builder().fl(k -> -2L).g(-1).h(new A000040()));
  }
}
