package irvine.oeis.a280;
// Generated by gen_seq4.pl 2024-05-08/parmof2 at 2024-05-08 21:31

import irvine.oeis.a056.A056911;
import irvine.oeis.a076.A076739;

/**
 * A280198 Expansion of 1/(1 - Sum_{k&gt;=1} mu(2*k-1)^2*x^(2*k-1)), where mu() is the Moebius function (A008683).
 * @author Georg Fischer
 */
public class A280198 extends A076739 {

  /** Construct the sequence. */
  public A280198() {
    super(0, new A056911());
  }
}
