package irvine.oeis.a280;
// Generated by gen_seq4.pl robot/partprod at 2023-05-04 21:32

import irvine.oeis.PartialProductSequence;
import irvine.oeis.a057.A057661;

/**
 * A280133 Partial products of A057661 (Sum_{d|n} psi(d)).
 * @author Georg Fischer
 */
public class A280133 extends PartialProductSequence {

  /** Construct the sequence. */
  public A280133() {
    super(new A057661());
  }
}
