package irvine.oeis.a251;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A251445 Number of (n+1)X(2+1) 0..2 arrays with no 2X2 subblock having the minimum of its diagonal elements less than the absolute difference of its antidiagonal elements.
 * @author Georg Fischer
 */
public class A251445 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A251445() {
    super(1, "[0,1,-4,1,20,-65,2,234,-110,-151,231,-265,-258,534,272,-243,-100,34,9,-1]", "230,2429,26633,295339,3275490,36343085,403222305,4473823718,49637592540,550735918201,6110487718079,67796678363317,752213181106743,8345905588826365,92598935523367524,1027397539720172063,11399112725846171141,126474675988211500846", 0, 0);
  }
}
