package irvine.oeis.a251;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A251430 Number of length 3+2 0..n arrays with the sum of the maximum minus twice the median plus the minimum of adjacent triples multiplied by some arrangement of +-1 equal to zero.
 * @author Georg Fischer
 */
public class A251430 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A251430() {
    super(1, "[0,1,2,4,5,5,2,-3,-10,-17,-21,-21,-14,-3,13,27,38,40,34,19,0,-19,-34,-40,-38,-27,-13,3,14,21,21,17,10,3,-2,-5,-5,-4,-2,-1]", "12,97,380,1113,2532,5097,9120,15449,24344,36877,53400,75541,103332,138857,182012,235645,299348,376229,465720,572073,693956,836041,996988,1182653,1390604,1627337,1890212,2187213,2514672,2880669,3281476,3727513,4213048,4748693,5329044,5966865,6654744,7405797", 0, 0);
  }
}
