package irvine.oeis.a251;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A251294 Number of (n+1) X (2+1) 0..3 arrays with every 2 X 2 subblock summing to 3 6 or 9.
 * @author Georg Fischer
 */
public class A251294 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A251294() {
    super(1, "[0,444,-8848,53196,-58272,-225832,-38648,53760]", "[1,-27,260,-970,405,3449,722,-840]");
  }
}
