package irvine.oeis.a161;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a001.A001097;
import irvine.oeis.a007.A007510;

/**
 * A161164 Absolute value of (the n-th twin prime minus the n-th non-twin prime).
 * @author Georg Fischer
 */
public class A161164 implements Sequence {

  final Sequence mA001097 = new A001097();
  final Sequence mA007510 = new A007510();
  /** Construct the sequence. */
  public A161164() {
  }
  
  @Override
  public Z next() {
    return mA001097.next().subtract(mA007510.next()).abs();
  }

}
