package irvine.oeis.a161;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-22 22:46
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PaddingSequence;


/**
 * A161652 Number of reduced words of length n in the Weyl group A_39.
 * @author Georg Fischer
 */
public class A161652 extends EulerTransform {

  /** Construct the sequence. */
  public A161652() {
    super(new PaddingSequence(new long[] {39}, new long[] {-1}), 1);
  }
}
