package irvine.oeis.a161;
// Generated by gen_seq4.pl hypergeon at 2023-11-10 15:47

import irvine.math.z.Z;
import irvine.oeis.HypergeometricSequence;

/**
 * A161936 The number of direct isometries that are derangements of the (n-1)-dimensional facets of an n-cube.
 * @author Georg Fischer
 */
public class A161936 extends HypergeometricSequence {

  /** Construct the sequence. */
  public A161936() {
    super(1, 2, 0, "[[1],[1,-1],[2]]", "", (n, v) -> v.multiply(-n).add(1).multiply(Z.NEG_ONE.pow(n)).num());
  }
}
