package irvine.oeis.a161;
// generated by patch_offset.pl at 2022-08-17 15:41

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A161771 Decimal expansion of (70*exp(Pi*sqrt(163)))^2.
 * @author Georg Fischer
 */
public class A161771 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence. */
  public A161771() {
    super(39, REALS.pow(CR.valueOf(70).multiply(CR.PI.multiply(CR.valueOf(163).sqrt()).exp()), CR.TWO));
  }
}
