package irvine.oeis.a161;
// Generated by gen_seq4.pl 2024-06-23/lambdan at 2024-06-23 23:33

import irvine.math.function.Functions;
import irvine.oeis.LambdaSequence;

/**
 * A161942 Odd part of sum of divisors of n.
 * @author Georg Fischer
 */
public class A161942 extends LambdaSequence {

  /** Construct the sequence. */
  public A161942() {
    super(1, n -> Functions.MAKE_ODD.z(Functions.SIGMA.z(1, n)));
  }
}
