package irvine.oeis.a190;
// Generated by gen_seq4.pl dex CR.ONE.add(CR.ONE.add(CR.SQRT2).sqrt()) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A190283 Decimal expansion of 1+sqrt(1+sqrt(2)).
 * @author Georg Fischer
 */
public class A190283 extends DecimalExpansionSequence {

  private static final CR N = CR.ONE.add(CR.ONE.add(CR.SQRT2).sqrt());

  @Override
  protected CR getCR() {
    return N;
  }
}
