package irvine.oeis.a190;
// Generated by gen_seq4.pl posins at 2020-06-21 23:01
// DO NOT EDIT here!

import irvine.oeis.FilterPositionSequence;


/**
 * A190209 Positions of 1 in A190207; complement of A190208.
 * @author Georg Fischer
 */
public class A190209 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A190209() {
    super(1, new A190207(), 1);
  }
}
