package irvine.oeis.a107;
// Generated by gen_seq4.pl latcoors at 2020-07-22 14:21

import irvine.oeis.LatticeCoordinationSequence;


/**
 * A107526 Coordination sequence for D_31 lattice.
 * @author Georg Fischer
 */
public class A107526 extends LatticeCoordinationSequence {

  /** Construct the sequence. */
  public A107526() {
    super("D", 31);
  }
}
