package irvine.oeis.a397;
// Generated by gen_seq4.pl 2026-07-02.ack/lambdan at 2026-07-02 22:33

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A397507 a(n) = Sum_{k=0..n} (binomial(4*n+2*k-3,k) - binomial(4*n+2*k-3,k-1)).
 * @author Georg Fischer
 */
public class A397507 extends LambdaSequence {

  /** Construct the sequence. */
  public A397507() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(4 * n + 2 * k - 3, k).subtract(Binomial.binomial(4 * n + 2 * k - 3, k - 1))));
  }
}
