package irvine.oeis.a397;
// Generated by gen_seq4.pl 2026-07-05.ack/decexpr at 2026-07-05 22:30

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A397544 Decimal expansion of the height of a canonical (dual-uniform) pentagonal trapezohedron with unit short edge length.
 * Formula:
 * @author Georg Fischer
 */
public class A397544 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;

  /** Construct the sequence */
  public A397544() {
    super(1, REALS.csc(CR.PI.divide(CR.TEN)).pow(3).multiply(REALS.sin(CR.PI.divide(CR.FIVE))).divide(CR.FOUR));
  }
}
