package irvine.oeis.a397;
// Generated by gen_seq4.pl 2026-06-27.ack/trilambn at 2026-06-27 22:51

import irvine.math.function.Functions;
import irvine.math.z.Binomial;
import irvine.math.z.Z;
import irvine.oeis.triangle.LambdaTriangle;

/**
 * A397421 Triangle read by rows: T(n, k) = binomial(n+k, n) * Stirling2(n, k) * n^k.
 * @author Georg Fischer
 */
public class A397421 extends LambdaTriangle {

  /** Construct the sequence. */
  public A397421() {
    super(0, 0, 0, (n, k) -> Binomial.binomial(n + k, n).multiply(Functions.STIRLING2.z(n, k)).multiply(Z.valueOf(n).pow(k)));
  }
}
