package irvine.oeis.a295;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-28 19:36

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A295220 a(n) = Sum_{i=1..floor(n/2)} floor((n+i)/i) - floor((n-i-1)/i).
 * a(n)=sum(i=1,floor(n/2),floor((n+i)/i)-floor((n-i-1)/i))
 * @author Georg Fischer
 */
public class A295220 extends LambdaSequence {

  /** Construct the sequence. */
  public A295220() {
    super(1, n -> Integers.SINGLETON.sum(1, n / 2, i -> Z.valueOf(n + i).divide(i).subtract(Z.valueOf(n - i - 1).divide(i))));
  }
}
