package irvine.oeis.a295;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A295869 Numbers not divisible by <code>2, 3</code> or <code>5 (A007775)</code> with digital root 8.
 * @author Georg Fischer
 */
public class A295869 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A295869() {
    super(1, new long[] {0, 17, 36, 18, 18, 1},
      new long[] {1, -1, 0, 0, -1, 1});
  }
}
