package irvine.oeis.a226;
// Generated by gen_seq4.pl deriv at 2020-07-01 19:03
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.Sequence1;
import irvine.oeis.a085.A085192;

/**
 * A226478 A085192(n)/2.
 * @author Georg Fischer
 */
public class A226478 extends Sequence1 {

  final Sequence mA085192 = new A085192();
  @Override
  public Z next() {
    return mA085192.next().divide(Z.TWO);
  }

}
