package irvine.oeis.a226;
// Generated by gen_seq4.pl eulerps -1 at 2020-11-16 21:39
// DO NOT EDIT here!

import irvine.oeis.transform.EulerTransform;
import irvine.oeis.recur.PeriodicSequence;


/**
 * A226054 McKay-Thompson series of class 45A for the Monster group with a(0) = 1.
 * Somos formula: <code>e45A=ecalc([3, 2;15, 2;1,-1;5,-1;9,-1;45,-1}]);</code>
 * @author Georg Fischer
 */
public class A226054 extends EulerTransform {

  /** Construct the sequence. */
  public A226054() {
    super(new PeriodicSequence(1, 1, -1, 1, 2, -1, 1, 1, 0, 2, 1, -1, 1, 1, -2, 1, 1, 0, 1, 2, -1, 1, 1, -1, 2, 1, 0, 1, 1, -2, 1, 1, -1, 1, 2, 0, 1, 1, -1, 2, 1, -1, 1, 1, 0), 1);
  }
}
