package irvine.oeis.a160;
// Generated by gen_seq4.pl holos at 2021-02-03 19:11
// 0: holon
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;


/**
 * A160076 Numerator of Hermite(n, 17/26).
 * @author Georg Fischer
 */
public class A160076 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A160076() {
    super(0, "[[0],[338,-338],[17],[-1]]", "", 0);
  }
}
