package irvine.oeis.a160;
// Generated by gen_seq4.pl holose at 2020-04-12 21:28
// egf: exp(26*x-625*x^2)
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A160059 Numerator of Hermite(n, 13/25).
 * @author Georg Fischer
 */
public class A160059 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A160059() {
    super(0, "[[0],[1250],[-26],[2,1]]", "[1,26,-574,-79924]", 2);
    setGfType(1);
  }
}
