package irvine.oeis.a160;
// Generated by gen_seq4.pl dexcr REALS.pow(CR.TWO, CR.ONE_THIRD).add(CR.THREE.sqrt()) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.math.cr.ComputableReals;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A160331 Decimal expansion of <code>2^(1/3) + sqrt(3)</code>.
 * @author Georg Fischer
 */
public class A160331 extends DecimalExpansionSequence {

  private static final ComputableReals REALS = ComputableReals.SINGLETON;
  private static final CR N = REALS.pow(CR.TWO, CR.ONE_THIRD).add(CR.THREE.sqrt());

  @Override
  protected CR getCR() {
    return N;
  }
}
