package irvine.oeis.a195;
// Generated by gen_seq4.pl floor at 2021-08-31 21:27

import irvine.math.cr.CR;
import irvine.math.z.Z;
import irvine.oeis.FloorSequence;

/**
 * A195177 a(n) = 3*n - floor(2*n*sqrt(2)).
 * @author Georg Fischer
 */
public class A195177 extends FloorSequence {
  /** Construct the sequence. */
  public A195177() {
    super(0);
  }

  protected Z evalCR(final long n) {
    return Z.THREE.multiply(Z.valueOf(n)).subtract(CR.TWO.multiply(CR.valueOf(n)).multiply(CR.SQRT2).floor());
  }

}
