package irvine.oeis.a195;
// Generated by gen_seq4.pl 2025-03-16.ack/lambdan at 2025-03-16 17:02

import irvine.math.cr.CR;
import irvine.math.q.Q;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A195604 Numerator of floor(e*10^n)/10^n, where e = exp(1) = A001113.
 * @author Georg Fischer
 */
public class A195604 extends LambdaSequence {

  /** Construct the sequence. */
  public A195604() {
    super(0, n -> {
      final Z c10 = Z.TEN.pow(n);
      return new Q(CR.E.multiply(c10).floor(), c10).num();
    });
  }
}
