package irvine.oeis.a195;
// Generated by gen_seq4.pl decexp at 2021-07-18 18:00

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A195290 Decimal expansion of shortest length, (A), of segment from side AB through incenter to side AC in right triangle ABC with sidelengths (a,b,c)=(7,24,25).
 * Formula: 30/7*2^(1/2)
 * @author Georg Fischer
 */
public class A195290 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A195290() {
    super(1, CR.valueOf(30).divide(CR.SEVEN).multiply(CR.TWO.sqrt()));
  }
}
