package irvine.oeis.a250;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A250343 Number of length 7+5 0..n arrays with every six consecutive terms having the maximum of some three terms equal to the minimum of the remaining three terms.
 * @author Georg Fischer
 */
public class A250343 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A250343() {
    super(1, "[0,-1,10,-45,120,-210,252,-210,120,-45,10,-1]", "648,46941,682576,5156313,26422104,104374957,341862816,971811153,2472291496,5751557757", 0, 0);
  }
}
