package irvine.oeis.a250;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A250633 Number of (1+1) X (n+1) 0..2 arrays with nondecreasing x(i,j)+x(i,j-1) in the i direction and nondecreasing min(x(i,j),x(i-1,j)) in the j direction.
 * @author Georg Fischer
 */
public class A250633 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A250633() {
    super(1, "[0,36,-26,-113,70,83,-46,-17,9]", "[1,-5,2,14,-7,-10,5,2,-1]");
  }
}
