package irvine.oeis.a218;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A218839 Unmatched value maps: number of nX5 binary arrays indicating the locations of corresponding elements not equal to any horizontal or antidiagonal neighbor in a random 0..1 nX5 array.
 * @author Georg Fischer
 */
public class A218839 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A218839() {
    super(1, "[0,0,-7,11,35,-178,549,-416,-787,762,-93,1154,-523,-630,-41,-128,103,6,12,-1]", "12,156,2050,26635,346501,4507281,58634265,762745363,9922198586,129073371922,1679056577224,21842080049186,284133645307551,3696164842194424,48081720559244098,625473146037672596,8136494531939059917,105843941802101587553", 0, 0);
  }
}
