package irvine.oeis.a232;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A232231 G.f.: (1-3*x+2*x^2+2*x^4+4*x^5)/((1-x)*(1-3*x-4*x^3)).
 * @author Georg Fischer
 */
public class A232231 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A232231() {
    super(0, new long[] {1, -3, 2, 0, 2, 4},
      new long[] {1, -4, 3, -4, 4});
  }
}
