package irvine.oeis.a232;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-24 21:51

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A232545 Number of Euler tours of the complete digraph on n vertices.
 * a(n) = n^(n-2)*(n-2)!^n
 * @author Georg Fischer
 */
public class A232545 extends LambdaSequence {

  /** Construct the sequence. */
  public A232545() {
    super(2, n -> Z.valueOf(n).pow(n - 2).multiply(Functions.FACTORIAL.z(n - 2).pow(n)));
  }
}
