package irvine.oeis.a004;
// Generated by gen_seq4.pl sumpow at 2020-08-02 22:32

import irvine.oeis.a003.A003340;

/**
 * A004817 Numbers that are the sum of 6 positive <code>11th</code> powers.
 * @author Sean A. Irvine
 */
public class A004817 extends A003340 {

  protected int power() {
    return 11;
  }
}
