package irvine.oeis.a299;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A299074 Expansion of <code>1/((1-x)*(1-2*x)*(1-6*x)*(1-24*x))</code>.
 * @author Georg Fischer
 */
public class A299074 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A299074() {
    super(0, new long[] {1},
      new long[] {1, -33, 236, -492, 288});
  }
}
