package irvine.oeis.a299;
// Generated by gen_seq4.pl 2025-06-16.ack/lambdan at 2025-06-16 21:55

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a002.A002620;
import irvine.oeis.a006.A006218;

/**
 * A299251 a(n) = ((Sum_{k=1..floor((n+1)^2/4)} d(k)) - T(n)) / 2, where d(n) = number of divisors of n (A000005) and T(n) = the n-th triangular number (A000217).
 * @author Georg Fischer
 */
public class A299251 extends LambdaSequence {

  private static final DirectSequence A002620 = new A002620();
  private static final DirectSequence A006218 = new A006218();

  /** Construct the sequence. */
  public A299251() {
    super(1, n -> (new Q(A006218.a(A002620.a(n + 1))).subtract(Functions.TRIANGULAR.z(n))).divide(2).num());
  }
}
