package irvine.oeis.a393;
// Generated by gen_seq4.pl 2026-02-09.ack/lambdan at 2026-02-09 21:57

import irvine.math.z.Integers;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a356.A356162;

/**
 * A393051 Number of divisors d of n such that d and A276086(d) are coprime, where A276086 is the primorial base exp-function.
 * @author Georg Fischer
 */
public class A393051 extends LambdaSequence {

  private static final DirectSequence A356162 = new A356162();

  /** Construct the sequence. */
  public A393051() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> A356162.a(d)));
  }
}
