package irvine.oeis.a393;
// Generated by gen_seq4.pl 2026-05-25.ack/holos at 2026-05-25 22:40

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A393908 a(n) = Sum_{i=0..n} Sum_{j=0..i} binomial(n+2*i,3*i) * binomial(i+2*j,3*j).
 * @author Georg Fischer
 */
public class A393908 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A393908() {
    super(0, "[0,1,-9,40,-108,189,-215,154,-63,13,-1]", "1, 3, 15, 82, 459, 2589, 14632, 82708, 467399", 0, 0);
  }
}
