package irvine.oeis.a191;
// Generated by gen_seq4.pl 2025-06-25.ack/polyx at 2025-06-25 23:22

import irvine.oeis.PolynomialFieldSequence;

/**
 * A191242 Reversion of x-x^2-x^3-2*x^4.
 * @author Georg Fischer
 */
public class A191242 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A191242() {
    super(1, "[1],[0,1,-1,-1,-2]", "p1,rev", 1, 0);
  }
}
