package irvine.oeis.a063;
// Generated by gen_seq4.pl A063nnnp/lingf at 2023-05-06 21:15

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A063277 Dimension of the space of weight n cuspidal newforms for Gamma_1( 4 ).
 * @author Georg Fischer
 */
public class A063277 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A063277() {
    super(2, "[0,0,-1,0,0,0,2,1,3,0,2]", "[1,0,0,0,-1,0,-1,0,0,0,1]");
  }
}
