package irvine.oeis.a063;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A063816 Growth series for fundamental group of orientable closed surface of genus 6.
 * @author Georg Fischer
 */
public class A063816 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A063816() {
    super(0, new long[] {1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, -1, -1},
      new long[] {1, -23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 23, -1});
  }
}
