package irvine.oeis.a063;
// Generated by gen_seq4.pl A063115/parmof3 at 2023-07-18 16:59

/**
 * A063598 Smallest k such that 6^k has exactly n 2&apos;s in its decimal representation.
 * @author Georg Fischer
 */
public class A063598 extends A063115 {

  /** Construct the sequence. */
  public A063598() {
    super(0, 6, 2);
  }
}
