package irvine.oeis.a063;
// Generated by gen_seq4.pl A063nnnp/lingf at 2023-05-06 21:15

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A063144 Dimension of the space of weight 2n cusp forms for Gamma_0( 76 ).
 * @author Georg Fischer
 */
public class A063144 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A063144() {
    super(1, "[0,8,11,1]", "[1,-2,1]");
  }
}
