package irvine.oeis.a063;
// Generated by gen_seq4.pl A063nnnp/lingf at 2023-05-06 21:15

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A063338 Dimension of the space of weight n cuspidal newforms for Gamma_1( 65 ).
 * @author Georg Fischer
 */
public class A063338 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A063338() {
    super(2, "[0,0,-1,117,272,424,577,611,609,491,336,184,31,1]", "[1,0,0,0,-1,0,-1,0,0,0,1]");
  }
}
