package irvine.oeis.a063;
// Generated by gen_seq4.pl A063115/parmof3 at 2023-07-18 16:59

/**
 * A063593 Smallest k such that 5^k has exactly n 8's in its decimal representation.
 * @author Georg Fischer
 */
public class A063593 extends A063115 {

  /** Construct the sequence. */
  public A063593() {
    super(0, 5, 8);
  }
}
