package irvine.oeis.a334;
// Generated by gen_seq4.pl holos at 2020-10-26 23:20
// 9: 9
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;


/**
 * A334281 Number of n-colorings of the vertices of the 4-dimensional cross polytope such that no two adjacent vertices have the same color.
 * @author Georg Fischer
 */
public class A334281 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A334281() {
    super(0, "[[0],[1],[-9],[36],[-84],[126],[-126],[84],[-36],[9],[-1]]", "[0, 0, 0, 0, 24, 600, 7560, 61320, 351120]", 0);
  }
}
