package irvine.oeis.a334;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A334995 Twice the area of triangle with coordinates (Fn, Fn+k), (Fn+2k, Fn+3k) and (Fn+4k, Fn+5k), where Fn is the n-th Fibonacci number A000045.
 * @author Georg Fischer
 */
public class A334995 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A334995() {
    super(1, "[0,1,5,75,0,75,-5,1]", "[1,-10,-31,190,236,-190,-31,10,1]");
  }
}
