package irvine.oeis.a334;
// Generated by gen_seq4.pl holos at 2020-10-26 23:20
// 4: 4
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;


/**
 * A334909 Area/6 of primitive Pythagorean triangles given in A334638 as triples.
 * @author Georg Fischer
 */
public class A334909 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A334909() {
    super(0, "[[0],[-1024],[960],[-280],[30],[-1]]", "[1, 35, 770, 14260]", 0);
  }
}
