package irvine.oeis.a007;
// Generated by gen_seq4.pl 2025-09-02.ack/dead at 2025-09-02 11:14

import irvine.oeis.DeadSequence;

/**
 * A007308 Erroneous version of A383108.
 * @author Georg Fischer
 */
public class A007308 extends DeadSequence {

  /** Construct the sequence. */
  public A007308() {
    super(0);
  }
}
