package irvine.oeis.a197;
// Generated by gen_seq4.pl 2024-05-09/simtraf at 2024-05-09 22:36

import irvine.math.z.Z;
import irvine.oeis.a138.A138576;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A197594 Sum of the cubes of the first odd numbers up to a(n) equals the n-th perfect number.
 * @author Georg Fischer
 */
public class A197594 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A197594() {
    super(2, new A138576(), v -> Z.TWO.pow(v).subtract(1));
  }
}
