package irvine.oeis.a197;
// Generated by gen_seq4.pl decsolv at 2021-07-28 18:47

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCRFunction;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A197256 Decimal expansion of least x&gt;0 having sin(2x)=(sin 5x)^2.
 * Equation; sin(2*x)-(sin(5*x))^2
 * @author Georg Fischer
 */
public class A197256 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A197256() {
    super(0, new UnaryCRFunction() { 
      @Override 
      public CR execute(final CR x) {
        return CR.TWO.multiply(x).sin().subtract(CR.FIVE.multiply(x).sin().pow(CR.TWO));
      }
    }.inverseMonotone(CR.valueOf(0.083), CR.valueOf(0.086)).execute(CR.ZERO));
  }
}
