package irvine.oeis.a197;
// Generated by gen_seq4.pl dex CR.TAU.divide(CR.ONE.add(CR.TAU)) true 10 at 2020-04-05 12:17
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.DecimalExpansionSequence;

/**
 * A197732 Decimal expansion of 2*Pi/(1 + 2*Pi).
 * @author Georg Fischer
 */
public class A197732 extends DecimalExpansionSequence {

  private static final CR N = CR.TAU.divide(CR.ONE.add(CR.TAU));

  @Override
  protected CR getCR() {
    return N;
  }
}
