package irvine.oeis.a327;
// Generated by gen_seq4.pl mult at 2022-07-21 21:19

import irvine.oeis.MultiplicativeSequence;

/**
 * A327939 Multiplicative with a(p^e) = p^(e-(e mod p)).
 * @author Georg Fischer
 */
public class A327939 extends MultiplicativeSequence {

  /** Construct the sequence. */
  public A327939() {
    super(1, (p, e) -> p.pow(e - (e % p.intValue())));
  }
}
