package irvine.oeis.a327;
// Generated by gen_seq4.pl 2026-08-08.ack/declamb at 2026-08-08 20:21

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A327558 Decimal expansion of Sum_{k&gt;=1} 1/F(k)! where F(k) = A000045(k).
 * @author Georg Fischer
 */
public class A327558 extends DecimalExpansionSequence {

  /** Construct the sequence */
  public A327558() {
    super(1, 1, k -> new Q(1, Functions.FACTORIAL.z(Functions.FIBONACCI.z(k))));
  }
}
