package irvine.oeis.a216;
// Generated by gen_seq4.pl 2025-08-14.ack/lambdan at 2025-08-14 22:46

import irvine.math.function.Functions;
import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A216078 Number of horizontal and antidiagonal neighbor colorings of the odd squares of an n X 2 array with new integer colors introduced in row major order.
 * @author Georg Fischer
 */
public class A216078 extends LambdaSequence {

  /** Construct the sequence. */
  public A216078() {
    super(1, n -> {
      final int m = (n - 1) / 2;
      final int e = (n + 1) & 1;
      return Integers.SINGLETON.sum(0, m, k -> Binomial.binomial(m, k).multiply(Functions.BELL.z(m + k + e)));
    });
  }
}
