package irvine.oeis.a216;
// Generated by gen_seq4.pl 2025-06-08.ack/polyxa at 2025-06-08 23:06

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a000.A000169;

/**
 * A216534 Number of cycles in all partial functions on {1,2,...,n}.
 * egf(new A000169())
 * @author Georg Fischer
 */
public class A216534 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A216534() {
    super(0, "[1]", "x,B,exp,1,1,x,B,-,/,log,*,1,x,B,-,/", 0, 1, 1, 1, egf(new A000169()));
  }
}
