package irvine.oeis.a216;
// Generated by gen_seq4.pl primof at 2021-01-16 00:20
// DO NOT EDIT here!

import irvine.oeis.PrimeSubsequence;


/**
 * A216977 Primes of the form n^5+2.
 * @author Georg Fischer
 */
public class A216977 extends PrimeSubsequence {

  /** Construct the sequence. */
  public A216977() {
    super("[[2, 0, 0, 0, 0, 1],[-1]]", "[2]", 0);
  }
}
