package irvine.oeis.a216;
// Generated by gen_seq4.pl insect/insect2 at 2022-02-22 19:20

import irvine.oeis.IntersectionSequence;
import irvine.oeis.a000.A000292;
import irvine.oeis.a002.A002378;

/**
 * A216267 Numbers that are both tetrahedral and pronic.
 * @author Georg Fischer
 */
public class A216267 extends IntersectionSequence {

  /** Construct the sequence. */
  public A216267() {
    super(new A000292(), new A002378());
  }
}
