package irvine.oeis.a094;
// Generated by gen_seq4.pl 2023-10-04/filtpos at 2023-10-04 14:25

import irvine.math.cr.CR;
import irvine.math.z.Z;
import irvine.oeis.FilterPositionSequence;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A094058 Positions of ones in binary expansion of e/4.
 * @author Georg Fischer
 */
public class A094058 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A094058() {
    super(1, 1, new DecimalExpansionSequence(1, CR.E.divide(Z.FOUR), 2), ONE);
  }
}
