package irvine.oeis.a094;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A094827 Number of (s(0), s(1), ..., s(2n+1)) such that 0 &lt; s(i) &lt; 9 and |s(i) - s(i-1)| = 1 for i = 1,2,....,2n+1, s(0) = 1, s(2n+1) = 4.
 * @author Georg Fischer
 */
public class A094827 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A094827() {
    super(1, new long[] {0, -1, 3, -1},
      new long[] {-1, 7, -15, 10, -1});
  }
}
