package irvine.oeis.a185;
// Generated by gen_seq4.pl eulerper -2 16 2, -3, 2, 1, 2, -3, 2, -6, 2, -3, 2, 1, 2, -3, 2, 0 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A185146 Expansion of <code>q^-2 * phi(q) * phi(q^4) / psi(q^8)^2</code> in powers of q where <code>phi(), psi()</code> are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A185146 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A185146() {
    super(new PeriodicSequence(2, -3, 2, 1, 2, -3, 2, -6, 2, -3, 2, 1, 2, -3, 2, 0), 0);
  }
}
