package irvine.oeis.a331;
// Generated by gen_seq4.pl holos at 2020-04-12 21:28
// ogf: (sqrt(1-4*x+4*x^4)-sqrt(1-4*x))/(2*x)
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A331951 Number of binary trees with n internal nodes that contain the subtree <code>[Z, [Z</code>, U, <code>U], [Z</code>, U, <code>U]]</code>.
 * @author Georg Fischer
 */
public class A331951 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A331951() {
    super(0, "[[0],[-24,-24,48],[0,-52,-28],[12,16,4],[-84,-192,-48],[264,244,40],[-144,-89,-11],[21,10,1]]", "[0,0,0,1,2,6,20,69]", 6);
  }
}
