package irvine.oeis.a256;
// Generated by gen_seq4.pl primof at 2021-01-16 00:20
// DO NOT EDIT here!

import irvine.oeis.PrimeSubsequence;


/**
 * A256312 Primes of the form n^2 + n + 712329866165608771.
 * @author Georg Fischer
 */
public class A256312 extends PrimeSubsequence {

  /** Construct the sequence. */
  public A256312() {
    super("[[712329866165608771, 1, 1],[-1]]", "[712329866165608771]", 0);
  }
}
