package irvine.oeis.a256;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-09-12 11:03

import irvine.math.z.Binomial;
import irvine.oeis.LambdaSequence;

/**
 * A256277 C(2*n,n) mod 2*n+1.
 * a(n)=mod(binom(2*n, n), 2*n+1)
 * @author Georg Fischer
 */
public class A256277 extends LambdaSequence {

  /** Construct the sequence. */
  public A256277() {
    super(1, n -> Binomial.binomial(2 * n, n).modZ(2 * n + 1));
  }
}
