package irvine.oeis.a256;
// Generated by gen_seq4.pl eulerxfm 3 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.transform.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A256004 Expansion of q^3 * f( -q, -q^8)^4 * f( -q^2, -q^7) / (f( -q) * f( -q^4, -q^5)^2) in powers of q where f() is Ramanujan's general theta function.
 * @author Georg Fischer
 */
public class A256004 extends EulerTransform {

  /** Construct the sequence. */
  public A256004() {
    super(new PeriodicSequence(-3, 0, 1, 3, 3, 1, 0, -3, -2), 1);
  }
}
