package irvine.oeis.a306;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-24 21:51

import irvine.math.function.Functions;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A306241 a(n) = Sum_{k=0..n} (k*n)!/n!^k.
 * a(n) = sum(k=0,n,(k*n)!/n!^k)
 * @author Georg Fischer
 */
public class A306241 extends LambdaSequence {

  /** Construct the sequence. */
  public A306241() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Functions.FACTORIAL.z(k * n).divide(Functions.FACTORIAL.z(n).pow(k))));
  }
}
