package irvine.oeis.a306;
// Generated by gen_seq4.pl 2026-09-10.ack/lambdan at 2026-09-10 15: 43

import irvine.math.z.Integers;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a296.A296607;

/**
 * A306635 a(n) = Product_{k=1..n} BarnesG(2*k).
 * @author Georg Fischer
 */
public class A306635 extends LambdaSequence {

  private static final DirectSequence A296607 = new A296607();

  /** Construct the sequence. */
  public A306635() {
    super(1, n -> Integers.SINGLETON.product(1, n, k -> A296607.a(k)));
  }
}
