package irvine.oeis.a306;
// Generated by gen_seq4.pl holos [0,-8,28,-56,70,-56,28,-8,1] [1,1,1,1,1,1,1,1] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A306859 <code>a(n) = Sum_{k=0..floor(n/8)} binomial(n,8*k)</code>.
 * @author Georg Fischer
 */
public class A306859 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A306859() {
    super(1, "[0,-8,28,-56,70,-56,28,-8,1]", "[1,1,1,1,1,1,1,1]", 0);
  }
}
