package irvine.oeis.a105;
// Generated by gen_seq4.pl morfps at 2021-05-27 23:03

import irvine.oeis.base.MorphismFixedPointSequence;

/**
 * A105500 Trajectory of 1 under the morphism 1-&gt;{1,2}, 2-&gt;{3,2}, 3-&gt;{3,4}, 4-&gt;{1,4}.
 * @author Georg Fischer
 */
public class A105500 extends MorphismFixedPointSequence {

  /** Construct the sequence. */
  public A105500() {
    super(0, "1", "1232", "1->12, 2->32, 3->34, 4->14");
  }
}
