package irvine.oeis.a105;
// Generated by gen_seq4.pl trigf at 2021-02-20 21:59
// DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionTriangle;


/**
 * A105809 Riordan array (1/(1-x-x^2), x/(1-x)).
 *
 * @author Georg Fischer
 */
public class A105809 extends GeneratingFunctionTriangle {

  /**
   * Construct the sequence.
   */
  public A105809() {
    super(0, new long[] {1, -1, 0}, new long[] {1, -2, -1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0});
  }
}
