package irvine.oeis.a203;
// Generated by gen_seq4.pl quots at 2021-11-26 23:52

import irvine.oeis.SelfQuotientSequence;

/**
 * A203513 a(n) = A203312(n+1)/A203312(n).
 * @author Georg Fischer
 */
public class A203513 extends SelfQuotientSequence {

  /** Construct the sequence. */
  public A203513() {
    super(new A203312(), 1);
  }
}
