package irvine.oeis.a203;
// Generated by gen_seq4.pl prodsi2 at 2021-11-20 22:11

import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A203477 a(n) = Product_{0 &lt;= i &lt; j &lt;= n-1} (2^i + 2^j).
 * @author Georg Fischer
 */
public class A203477 implements Sequence {

  private int mN = 0;

  @Override
  public Z next() {
    ++mN;
    Z prod = Z.ONE;
    for (int j = 1; j <= mN - 1; ++j) {
      for (int i = 0; i <= j - 1; ++i) {
        prod = prod.multiply(Z.ONE.shiftLeft(i).add(Z.ONE.shiftLeft(j)));
      }
    }
    return prod;
  }
}
