package irvine.oeis.a204;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A204487 Number of (n+2)X5 0..1 arrays with every 3X3 subblock having three equal elements in a row horizontally, vertically or nw-to-se diagonally exactly one way, and new values 0..1 introduced in row major order.
 * @author Georg Fischer
 */
public class A204487 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A204487() {
    super(1, "[0,0,0,0,0,0,0,0,0,4,-3,-6,-5,-21,20,-10,48,-15,20,-20,-7,-10,-5,9,1,1,-1]", "610,1189,2547,5407,11331,23851,50897,109489,236402,512911,1118772,2440948,5333293,11686972,25595013,56075719,123070849,269926981,592042603,1300024973,2853037552,6260804838,13749466588,30182600469,66249470711", 0, 0);
  }
}
