package irvine.oeis.a204;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A204609 Number of (n+1) X 2 0..1 arrays with the determinants of 2 X 2 subblocks nondecreasing rightwards and downwards.
 * @author Georg Fischer
 */
public class A204609 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A204609() {
    super(1, "[0,0,0,0,-2,0,3,-1]", "16,47,125,335,907,2470", 0, 0);
  }
}
