package irvine.oeis.a204;
// Generated by gen_seq4.pl latriang at 2020-07-28 21:29

import irvine.math.z.Z;
import irvine.oeis.recur.LatticeCoordinationSequence;


/**
 * A204621 Triangle read by rows: coordinator triangle for lattice A*_n.
 * @author Georg Fischer
 */
public class A204621 extends LatticeCoordinationSequence {

  /** Construct the sequence. */
  public A204621() {
    super("A*", 0);
  }

  @Override
  public Z next() {
    return nextTriangleElement("A*", 0); 
  } 
}
