package irvine.oeis.a204;
// Generated by gen_seq4.pl sigman1/sigma1 at 2023-02-28 23:52

import irvine.math.function.Functions;
import irvine.math.z.Z;
import irvine.oeis.a005.A005101;

/**
 * A204822 Sum of divisors (A000203) of abundant numbers (A005101).
 * @author Georg Fischer
 */
public class A204822 extends A005101 {

  @Override
  public Z next() {
    return Functions.SIGMA.z(super.next());
  }
}
