package irvine.oeis.a204;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A204707 Number of <code>(n+1) X 3 0..1</code> arrays with the permanents of all <code>2 X 2</code> subblocks equal and nonzero.
 * @author Georg Fischer
 */
public class A204707 extends GeneratingFunctionSequence {

  // WARNING Conjectural formula: do not use this implementation to extend the sequence.

  /** Construct the sequence. */
  public A204707() {
    super(1, new long[] {0, 13, 7, -24},
      new long[] {1, -2, -3, 4});
  }
}
