package irvine.oeis.a204;
// Generated by gen_seq4.pl parmof2 at 2021-10-25 20:25

import irvine.oeis.a203.A203991;

/**
 * A204007 Array:  row n shows the coefficients of the characteristic polynomial of the n-th principal submatrix of min{2i+j-2, 2j+i-2} (A204006).
 *
 * @author Georg Fischer
 */
public class A204007 extends A203991 {

  /**
   * Construct the sequence.
   */
  public A204007() {
    super(1, new A204006());
  }
}
