package irvine.oeis.a130;
// generated by patch_offset.pl at 2022-08-16 19:10

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A130713 a(0)=a(2)=1, a(1)=2, a(n)=0 for n &gt; 2.
 * @author Georg Fischer
 */
public class A130713 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A130713() {
    super(0, "[[0],[1]]", "[1, 2, 1]", 0);
  }
}
