package irvine.oeis.a130;
// Generated by gen_seq4.pl padding 0 at 2020-08-22 18:36
// DO NOT EDIT here!

import irvine.oeis.PaddingSequence;


/**
 * A130706 <code>a(0) = 1, a(1) = 2, a(n) = 0</code> for <code>n &gt; 1</code>.
 * @author Georg Fischer
 */
public class A130706 extends PaddingSequence {

  /** Construct the sequence. */
  public A130706() {
    super(new long[] {1, 2}, new long[] {0});
  }
}
