package irvine.oeis.a038;
// Generated by gen_linrec.pl - DO NOT EDIT here!

import irvine.oeis.LinearRecurrence;

/**
 * A038620 Growth function (or coordination sequence) of the infinite cubic graph corresponding to the srs net <code>(a(n) =</code> number of nodes at distance n from a fixed <code>node)</code>.
 * @author Georg Fischer
 */
public class A038620 extends LinearRecurrence {

  /** Construct the sequence. */
  public A038620() {
    super(new long[] {1L, -1L, 0L, -2L, 2L, 0L, 1L}, new long[] {12L, 24L, 35L, 48L, 69L, 86L, 108L}, new long[] {1L, 3L, 6L});
  } // constructor()
} // A038620
