package irvine.oeis.a038;
// Generated by gen_seq4.pl trigf 1 1, -10, -7 at 2020-04-01 15:31
// 
// 
// DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionTriangle;

/**
 * A038309 Triangle whose <code>(i,j)-th</code> entry is <code>binomial(i,j)*10^(i-j)*7^j</code>.
 * @author Georg Fischer
 */
public class A038309 extends GeneratingFunctionTriangle {

  /** Construct the sequence. */
  public A038309() {
    super(0, new long[] {1}, new long[] {1, -10, -7});
  }
}
