package irvine.oeis.a092;
// Generated by gen_seq4.pl holos [0,-1,4,4,-9,11,-6,1] [0,0,1,4,14,48,165] 0 at 2019-12-17 15:30
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A092489 Arises in enumeration of 321-hexagon-avoiding permutations.
 * @author Georg Fischer
 */
public class A092489 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A092489() {
    super(1, "[0,-1,4,4,-9,11,-6,1]", "[0,0,1,4,14,48,165]", 0);
  }
}
