package irvine.oeis.a092;
// Generated by gen_seq4.pl A288580/arrselect

import irvine.oeis.a288.A288580;
import irvine.oeis.triangle.ArraySelector;

/**
 * A092399 Row 5 of array in A288580.
 * @author Georg Fischer
 */
public class A092399 extends ArraySelector {

  /** Construct the sequence. */
  public A092399() {
    super(0, new A288580(), 0, 1, n -> new int[] {n, 5});
  }
}

