package irvine.oeis.a114;
// Generated by gen_seq4.pl diffseq at 2020-06-21 22:58
// DO NOT EDIT here!

import irvine.oeis.DifferenceSequence;
import irvine.oeis.a014.A014613;

/**
 * A114404 4-almost prime gaps. First differences of <code>A014613</code>.
 * @author Georg Fischer
 */
public class A114404 extends DifferenceSequence {

  /** Construct the sequence. */
  public A114404() {
    super(new A014613());
  }
}
