package irvine.oeis.a114;
// Generated by gen_seq4.pl A059805/parm4 at 2022-12-27 00:44

import irvine.oeis.a024.A024023;
import irvine.oeis.a059.A059805;

/**
 * A114804 The numbers 3^n-1 written in groups of three digits, with leading zeros omitted.
 * @author Georg Fischer
 */
public class A114804 extends A059805 {

  /** Construct the sequence. */
  public A114804() {
    super(new A024023(), 1, 3);
  }
}
