package irvine.oeis.a114;
// Generated by gen_seq4.pl 2024-12-02.ack/filter at 2024-12-02 23:40

import irvine.math.predicate.Predicates;
import irvine.oeis.FilterSequence;

/**
 * A114520 Composites in sequence A114518.
 * @author Georg Fischer
 */
public class A114520 extends FilterSequence {

  /** Construct the sequence. */
  public A114520() {
    super(1, new A114518(), v -> !Predicates.PRIME.is(v));
  }
}
