package irvine.oeis.a096;
// Generated by gen_seq4.pl tuptraf/simtraf at 2023-10-28 00:07

import irvine.math.z.Z;
import irvine.oeis.a001.A001175;
import irvine.oeis.transform.SimpleTransformSequence;

/**
 * A096982 Define a(1)=0. Then define b(1)=1, b(2)=1 and for k &gt; 2, b(k) = (b(k-2) + b(k-1)) (mod n). This gives for each n a cyclic repetitive sequence; a(n) is the least k &gt; 1 for the first 1 of the sequence 1,1,....
 * @author Georg Fischer
 */
public class A096982 extends SimpleTransformSequence {

  /** Construct the sequence. */
  public A096982() {
    super(1, new A001175(), (n, v) -> (n <= 1) ? Z.ZERO : v.add(1));
  }
}
