package irvine.oeis.a096;
// Generated by gen_seq4.pl A063983/parm3 at 2022-05-02 19:05

/**
 * A096684 Least k such that decimal representation of k*n contains only digits 0 and 5.
 * @author Georg Fischer
 */
public class A096684 extends A096681 {

  /** Construct the sequence. */
  public A096684() {
    super(0, 5);
  }
}
