package irvine.oeis.a089;
// Generated by gen_seq4.pl A139056/parm2 at 2022-05-24 23:14

import irvine.oeis.a139.A139056;

/**
 * A089085 Numbers k such that (k! + 3)/3 is prime.
 * @author Georg Fischer
 */
public class A089085 extends A139056 {

  /** Construct the sequence. */
  public A089085() {
    super(3);
  }
}
