package irvine.oeis.a288;
// Generated by gen_seq4.pl trisimple/trisimard at 2021-11-07 23:41

import irvine.math.z.Z;
import irvine.oeis.triangle.UpperLeftTriangle;

/**
 * A288870 Triangle T from array A(k,n) = (2*k+1)*2^n + 1, k &gt;=0, n &gt;= 0 read by downwards antidiagonals.
 *
 * @author Georg Fischer
 */
public class A288870 extends UpperLeftTriangle {

  /** Construct the sequence. */
  public A288870() {
    super(0, 0, -1);
  }

  @Override
  public Z matrixElement(final int n, final int k) {
    return Z.ONE.shiftLeft(k).multiply(2 * n + 1).add(1);
  }
}
