package irvine.oeis.a288;
// Generated by gen_seq4.pl dirtraf at 2023-11-18 23:07

import irvine.oeis.a000.A000217;
import irvine.oeis.a006.A006577;
import irvine.oeis.transform.DirectTransformSequence;

/**
 * A288023 Number of steps to reach 1 in the Collatz 3x+1 problem starting with the n-th triangular number, or -1 if 1 is never reached.
 * @author Georg Fischer
 */
public class A288023 extends DirectTransformSequence {

  /** Construct the sequence. */
  public A288023() {
    super(1, new A006577(), new A000217());
  }
}
