package irvine.oeis.a288;
// Generated by gen_seq4.pl geneth at 2020-12-16 11:03
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.GeneralizedEulerTransform;
import irvine.oeis.a005.A005478;


/**
 * A288122 Number of partitions of n into prime Fibonacci numbers (A005478).
 * G.f.: <code>Product_{k&gt;=1} (1/(1-x^A005478(k)))</code>
 * @author Georg Fischer
 */
public class A288122 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A288122() {
    super(0, 1);
    mSeqH = new A005478();
    mNextH = advanceH(mKh);
  }

  @Override
  protected Z advanceH(final long k) {
    return mSeqH.next();
  }

}
