package irvine.oeis.a288;
// Generated by gen_seq4.pl joinlr 0 0 new long[] {-2L, 1L, 1L, 1L} new long[] {4L, 5L, 8L, 11L} new long[] {2L} at 2019-07-26 00:04

import irvine.oeis.LinearRecurrence;

/**
 * A288523 <code>a(n) = a(n-1) + a(n-2) + a(n-3) - 2*a(n-4)</code> for <code>n &gt;= 5</code>, where <code>a(0) = 2, a(1) = 4, a(2) = 5, a(3) = 8, a(4) = 11</code>.
 * @author Georg Fischer
 */
public class A288523 extends LinearRecurrence {

  /** Construct the sequence. */
  public A288523() {
    super(new long[] {-2L, 1L, 1L, 1L}, new long[] {4L, 5L, 8L, 11L}, new long[] {2L});
  }
}
