package irvine.oeis.a358;
// Generated by gen_seq4.pl 2025-08-05.ack/parmof2 at 2025-08-05 22:57

import irvine.oeis.a045.A045939;

/**
 * A358017 Numbers m such that the factorizations of m..m+8 have the same number of primes (including multiplicities).
 * @author Georg Fischer
 */
public class A358017 extends A045939 {

  /** Construct the sequence. */
  public A358017() {
    super(1, 8, 3405122);
  }
}
