package irvine.oeis.a227;
// Generated by gen_seq4.pl egfu at 2021-12-05 23:06

import irvine.math.polynomial.Polynomial;
import irvine.math.q.Q;
import irvine.oeis.ExponentialGeneratingFunction;

/**
 * A227462 E.g.f. equals the series reversion of x - x^2*exp(x^2).
 * E.g.f.: 0
 * @author Georg Fischer
 */
public class A227462 extends ExponentialGeneratingFunction {

  /** Construct the sequence. */
  public A227462() {
    super(1);
  }

  @Override
  public Polynomial<Q> compute(final int n) {
    return RING.reversion(RING.subtract(RING.x(), RING.multiply(RING.pow(RING.x(), 2, n), RING.exp(RING.pow(RING.x(), 2, n), n), n)), n);
  }
}
