package irvine.oeis.a227;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A227747 Number of n X 2 0,1 arrays indicating 2 X 2 subblocks of some larger (n+1) X 3 binary array having determinant equal to one.
 * @author Georg Fischer
 */
public class A227747 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A227747() {
    super(1, "[0,4,9,11,5,0,-1]", "[1,-1,-4,-8,-4,-1,1]");
  }
}
