package irvine.oeis.a227;
// Generated by gen_seq4.pl 2024-07-26/lambdan at 2024-07-27 00:11

import irvine.math.function.Functions;
import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A227234 G.f.: Sum_{n&gt;=1} x^n * (1+x)^prime(n).
 * @author Georg Fischer
 */
public class A227234 extends LambdaSequence {

  /** Construct the sequence. */
  public A227234() {
    super(1, n -> Integers.SINGLETON.sum(1, n, k -> Binomial.binomial(Functions.PRIME.z(k), n - k)));
  }
}
