package irvine.oeis.a142;
// Generated by gen_seq4.pl pricongr at 2022-01-06 16:44

import irvine.oeis.prime.CongruenceForm;

/**
 * A142948 Primes congruent to 51 mod 64.
 * @author Georg Fischer
 */
public class A142948 extends CongruenceForm {

  /** Construct the sequence. */
  public A142948() {
    super(64, 0, 51);
  }
}
