package irvine.oeis.a142;
// Generated by gen_seq4.pl pricongr at 2022-01-06 16:44

import irvine.oeis.prime.CongruenceForm;

/**
 * A142168 Primes congruent to 16 mod 39.
 * @author Georg Fischer
 */
public class A142168 extends CongruenceForm {

  /** Construct the sequence. */
  public A142168() {
    super(39, 0, 16);
  }
}
