package irvine.oeis.a137;
// generated by patch_offset.pl at 2022-08-16 19:10

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A137529 a(n)=8a(n-4).
 * @author Georg Fischer
 */
public class A137529 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A137529() {
    super(0, "[[0],[-8],[0],[0],[0],[1]]", "[1, 3, 4, 4, 8]", 0);
  }
}
