package irvine.oeis.a137;
// Generated by gen_seq4.pl 2026-05-21.ack/filnum at 2026-05-21 21:44

import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A137446 Positive numbers k such that k^2 +- (k-1) are primes.
 * @author Georg Fischer
 */
public class A137446 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A137446() {
    super(1, 1, k -> {
      final Z a = Z.valueOf(k).square();
      final Z b = Z.valueOf(k).subtract(1);
      return Predicates.PRIME.is(a.add(b)) && Predicates.PRIME.is(a.subtract(b));
    });
  }
}
