package irvine.oeis.a137;
// Generated by gen_seq4.pl squaredig 25689 at 2019-07-11 10:10
// DO NOT EDIT here!

import irvine.oeis.base.SquareDigitsSequence;

/**
 * A137114 Numbers k such that k and k^2 use only the digits 2, 5, 6, 8 and 9.
 * @author Georg Fischer
 */
public class A137114 extends SquareDigitsSequence {

  /** Construct the sequence. */
  public A137114() {
    super(1, 10, 2, "25689");
  }
}
