package irvine.oeis.a137;
// Generated by gen_seq4.pl eulerxfm 0 at 2020-08-17 18:03
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.PeriodicSequence;


/**
 * A137828 Expansion of phi(x) / f(-x^4)^2 in powers of x where phi(), f() are Ramanujan theta functions.
 * @author Georg Fischer
 */
public class A137828 extends EulerTransform {

  /** Construct the sequence. */
  public A137828() {
    super(new PeriodicSequence(2, -3, 2, 1), 1);
  }
}
