package irvine.oeis.a137;
// Generated by gen_seq4.pl parm2 at 2021-04-20 13:54
// DO NOT EDIT here!

import irvine.oeis.a030.A030516;

/**
 * A137486 Numbers with 23 divisors.
 * @author Georg Fischer
 */
public class A137486 extends A030516 {

  /** Construct the sequence. */
  public A137486() {
    super(23);
  }
}
