package irvine.oeis.a137;
// Generated by gen_seq4.pl squaredig 1456 at 2019-07-11 10:10
// DO NOT EDIT here!

import irvine.oeis.SquareDigitsSequence;

/**
 * A137045 Numbers k such that k and k^2 use only the digits 1, 4, 5 and 6.
 * @author Georg Fischer
 */
public class A137045 extends SquareDigitsSequence {

  /** Construct the sequence. */
  public A137045() {
    super(1, 10, 2, "1456");
  }
}
