package irvine.oeis.a353;
// Generated by gen_seq4.pl 2026-07-05.ack/lambdan at 2026-07-05 22:30

import irvine.math.z.Z;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;
import irvine.oeis.a053.A053669;

/**
 * A353529 a(n) = 1 if A053669(n) [the smallest prime not dividing n] is of the form 4m+3, otherwise a(n) = 0.
 * @author Georg Fischer
 */
public class A353529 extends LambdaSequence {

  private static final DirectSequence A053669 = new A053669();

  /** Construct the sequence. */
  public A353529() {
    super(1, n -> A053669.a(n).mod(4) == 3 ? Z.ONE : Z.ZERO);
  }
}
