package irvine.oeis.a125;
// Generated by gen_seq4.pl prilist at 2022-05-22 22:44

import irvine.oeis.prime.PrimeConditionListSequence;

/**
 * A125113 Numbers n such that 2n-1, 4n-1, 8n-1, 16n-1, 32n-1 and 64n-1 are primes.
 * @author Georg Fischer
 */
public class A125113 extends PrimeConditionListSequence {

  /** Construct the sequence */
  public A125113() {
    super(1, 2, -1, 4, -1, 8, -1, 16, -1, 32, -1, 64, -1);
  }
}
