package irvine.oeis.a125;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a051.A051674;

/**
 * A125137 a(n) = p^p + 1, where p = prime(n).
 * @author Georg Fischer
 */
public class A125137 implements Sequence {

  final Sequence mA051674 = new A051674();
  /** Construct the sequence. */
  public A125137() {
  }
  
  @Override
  public Z next() {
    return mA051674.next().add(Z.ONE);
  }

}
