package irvine.oeis.a116;
// Generated by gen_seq4.pl 2026-06-27.ack/multia at 2026-06-27 22:51

import irvine.oeis.transform.MultiTransformSequence;

/**
 * A116552 a(2*n+1) = 3*a(n), a(2*n+2) = 4*a(n) + a(n-1).
 * @author Georg Fischer
 */
public class A116552 extends MultiTransformSequence {

  /** Construct the sequence. */
  public A116552() {
    super(0, (self, n) -> {
      if ((n & 1) == 1) {
        final long m = n / 2;
        return self.a(m).multiply(3);
      } else {
        final long m = (n - 2) / 2;
        return self.a(m).multiply(4).add(self.a(m - 1));
      }
    }, "1,3,4");
  }
}
