package irvine.oeis.a116;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A116471 Values <code>2*(n -+ 1)^2</code> sorted.
 * @author Georg Fischer
 */
public class A116471 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A116471() {
    super(1, new long[] {0, 0, -2, -6, 4, 2, -2},
      new long[] {-1, 1, 2, -2, -1, 1});
  }
}
