package irvine.oeis.a067;
// Generated by gen_seq4.pl engelex at 2020-11-22 22:05
// DO NOT EDIT here!

import irvine.math.cr.CR;
import irvine.oeis.EngelExpansionSequence;


/**
 * A067916 Engel expansion of zeta(8)=sum(i&gt;0,1/i^8).
 * @author Georg Fischer
 */
public class A067916 extends EngelExpansionSequence {

  /** Construct the sequence */
  public A067916() {
    super();
  }

  @Override
  protected CR getN() {
    return CR.EIGHT.multiply(CR.PI.log()).exp().divide(CR.valueOf(9450));
  }
}
