package irvine.oeis.a067;
// Generated by gen_seq4.pl build/parmof2 at 2022-07-15 23:04

/**
 * A067449 Smallest n-th power starting with 8.
 * @author Georg Fischer
 */
public class A067449 extends A067443 {

  /** Construct the sequence. */
  public A067449() {
    super(1, 8);
  }
}
