package irvine.oeis.a303;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.math.q.Q;
import irvine.math.z.Z;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A303153 Expansion of Product_{n&gt;=1} (1 - (16*x)^n)^(1/4).
 * @author Georg Fischer
 */
public class A303153 extends RationalProductTransform {

  /** Construct the sequence. */
  public A303153() {
    super(0, new Builder().fq(k -> new Q(-1, 4)).g(k -> Z.valueOf(16).pow(k)));
  }
}
