package irvine.oeis.a303;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A303958 Number of nX5 0..1 arrays with every element unequal to 0, 1, 2 or 5 king-move adjacent elements, with upper left element zero.
 * @author Georg Fischer
 */
public class A303958 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A303958() {
    super(1, "[0,0,0,0,0,0,0,1,-1,1,2,-7,13,3,-8,9,-23,-6,11,0,2,2,-1]", "16,22,49,159,480,1431,4137,12066,35589,104863,307928,904119,2658091,7815860,22972429,67514241,198445406,583320819,1714573733,5039601468,14812938483", 0, 0);
  }
}
