package irvine.oeis.a349;
// Generated by gen_seq4.pl 2025-04-01.ack/multraf at 2025-04-01 22:10

import irvine.math.z.Z;
import irvine.oeis.a133.A133342;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A349304 Terms of sequence A133342 interpreted as numbers written in base 2 and converted here to base 10.
 * @author Georg Fischer
 */
public class A349304 extends MultiTransformSequence {

  /** Construct the sequence. */
  public A349304() {
    super(0, (self, n) -> new Z(self.s(0).toString(), 2), "", new A133342());
  }
}
