package irvine.oeis.a257;
// Generated by gen_seq4.pl negpos 1 0 dk 2 2 at 2019-07-25 19:56

import irvine.oeis.NegativePositiveSequence;

/**
 * A257918 Sequence <code>(d(n))</code> generated by Rule <code>1</code> (in Comments) with <code>a(1) = 2</code> and <code>d(1) = 2</code>.
 * @author Georg Fischer
 */
public class A257918 extends NegativePositiveSequence {

  /** Construct the sequence. */
  public A257918() {
    super(1, 0, "dk", 2, 2);
  }
}
