package irvine.oeis.a098;
// Generated by gen_seq4.pl caelem/ca1stageb at 2021-12-16 21:00

import irvine.math.z.Z;
import irvine.oeis.ca.Cellular1DAutomaton;

/**
 * A098608 a(n) = 100^n.
 * @author Georg Fischer
 */
public class A098608 extends Cellular1DAutomaton {

  /** Construct the sequence. */
  public A098608() {
    super(2);
  }

  @Override
  public Z next() {
    return super.nextStageB();
  }
}
