package irvine.oeis.a098;
// Generated by gen_seq4.pl eulerper 1 24 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A098693 G.f.: <code>q*Product_{k&gt;0} (1-q^(12k))(1+q^(12k-1))(1+q^(12k-11))/(1-q^k)</code>.
 * @author Georg Fischer
 */
public class A098693 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A098693() {
    super(new PeriodicSequence(2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 2, 0, 2, 1, 1, 1, 1, 1, 1, 1, 1, 0, 2, 0), 0);
  }
}
