package irvine.oeis.a071;
// Generated by gen_seq4.pl 2024-08-16.ack/lambdan at 2024-08-16 19:15

import irvine.math.function.Functions;
import irvine.math.z.Binomial;
import irvine.oeis.LambdaSequence;

/**
 * A071938 Binomial(max(n,R(n)),min(n,R(n))) where R(n) is the reversal of n.
 * @author Georg Fischer
 */
public class A071938 extends LambdaSequence {

  /** Construct the sequence. */
  public A071938() {
    super(1, n -> {
      final long r = Functions.REVERSE.l(n);
      return Binomial.binomial(Functions.MAX.l(n, r), Functions.MIN.l(n, r));
    });
  }
}
