package irvine.oeis.a071;
// Generated by gen_seq4.pl nest at 2020-12-29 12:34
// DO NOT EDIT here!

import irvine.oeis.NestedSequence;
import irvine.oeis.a007.A007947;
import irvine.oeis.a008.A008833;


/**
 * A071773 a(n) = gcd(rad(n), n/rad(n)), where rad(n) = A007947(n) is the squarefree kernel of n.
 * Formula: <code>a(n) = A007947(A008833(n)).</code>
 * @author Georg Fischer
 */
public class A071773 extends NestedSequence {

  /** Construct the sequence. */
  public A071773() {
    super(1, new A007947(), new A008833(), 1, 1); 
  }

}
