package irvine.oeis.a268;
// Generated by gen_seq4.pl holos [[0],[108,-504,528,-160],[126,-668,1012,-440],[0,0,-13,10]] [1,10,246,7540] 0 at 2020-03-14 22:45
// Recurrence: n^2*(10*n-13)*a[n+0]+2*(-220*n^3+506*n^2-334*n+63)*a[n-1]-4*(10*n-3)*(-3+2*n)^2*a[n-2]=0
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A268545 From the diagonal of <code>1/(1 - (y + z + x w + x z w + x y w))</code>.
 * @author Georg Fischer
 */
public class A268545 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A268545() {
    super(0, "[[0],[108,-504,528,-160],[126,-668,1012,-440],[0,0,-13,10]]", "[1,10,246,7540]", 0);
  }
}
