package irvine.oeis.a268;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A268965 Number of <code>n X 2 0..2</code> arrays with some element plus some horizontally or antidiagonally adjacent neighbor totalling two not more than once.
 * @author Georg Fischer
 */
public class A268965 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A268965() {
    super(1, new long[] {0, 9, -12},
      new long[] {1, -8, 16});
  }
}
