package irvine.oeis.a362;
// Generated by gen_seq4.pl 2024-11-22.ack/lambdan at 2024-11-22 22:47

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A362700 Expansion of e.g.f. 1/(1 + LambertW(-x * exp(x^2/2))).
 * @author Georg Fischer
 */
public class A362700 extends LambdaSequence {

  /** Construct the sequence. */
  public A362700() {
    super(0, n -> new Q(Functions.FACTORIAL.z(n)).multiply(Rationals.SINGLETON.sum(0, n / 2, k -> new Q(n - 2L * k).pow(n - k).divide(new Q(Z.TWO.pow(k)).multiply(Functions.FACTORIAL.z(k)).multiply(Functions.FACTORIAL.z(n - 2 * k))))).num());
  }
}
