package irvine.oeis.a343;
// Generated by gen_seq4.pl holink/holos at 2021-12-08 22:07

import irvine.oeis.HolonomicRecurrence;

/**
 * A343374 Number of sets in the geometry determined by the Hausdorff metric at each location between two sets defined by a complete bipartite graph K(5,n) (with n at least 4) missing three edges, where exactly two removed edges are incident to the same vertex in the 5-point set and exactly two removed edges are incident to the same vertex in the other set.
 * @author Georg Fischer
 */
public class A343374 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A343374() {
    super(4, "[[0],[9765],[-15381],[6562],[-1002],[57],[-1]]", "58984, 2445394, 86336272, 2843754442, 90733504504", 0);
  }
}
