package irvine.oeis.a343;
// Generated by gen_seq4.pl deris/moebiusix at 2022-10-26 15:17
// DO NOT EDIT here!

import irvine.oeis.a056.A056671;
import irvine.oeis.transform.InverseMobiusTransformSequence;

/**
 * A343443 If n = Product (p_j^k_j) then a(n) = Product (k_j + 2), with a(1) = 1.
 * @author Georg Fischer
 */
public class A343443 extends InverseMobiusTransformSequence {

  /** Construct the sequence. */
  public A343443() {
    super(new A056671(), 0);
    next();
  }
}
