package irvine.oeis.a343;
// Generated by gen_seq4.pl sumdiv3/sumdiv at 2023-04-11 14:46

import irvine.math.predicate.Predicates;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;

/**
 * A343407 Number of proper divisors of n that are triangular numbers.
 * @author Georg Fischer
 */
public class A343407 extends AbstractSequence {

  private int mN = 0;

  /** Construct the sequence. */
  public A343407() {
    super(1);
  }

  @Override
  public Z next() {
    ++mN;
    return Integers.SINGLETON.sumdiv(mN, d -> (d < mN && Predicates.TRIANGULAR.is(d)) ? Z.ONE : Z.ZERO);
  }
}
