package irvine.oeis.a364;
// Generated by gen_seq4.pl 2024-03-12/lambdan at 2024-03-12 20:32

import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A364045 Expansion of Sum_{k&gt;0} x^(3*k) / (1 + x^(5*k)).
 * @author Georg Fischer
 */
public class A364045 extends LambdaSequence {

  /** Construct the sequence. */
  public A364045() {
    super(1, n -> Integers.SINGLETON.sumdiv(n, d -> Z.valueOf(d % 5 == 3 ? 1 : 0).multiply(Z.NEG_ONE.pow(d))).negate());
  }
}
