package irvine.oeis.a357;
// Generated by gen_seq4.pl anopan 0,0

import irvine.math.z.Z;
import irvine.oeis.AbstractSequence;
import irvine.oeis.a002.A002894;
import irvine.oeis.a005.A005260;

/**
 * A357603 a(n) is the number of different pairs of shortest paths in an n X n lattice going between opposite corners in opposite directions and not meeting at their middle point.
 * @author Georg Fischer
 */
public class A357603 extends AbstractSequence {

  private final A002894 mSeq1 = new A002894();
  private final A005260 mSeq2 = new A005260();

  /** Construct the sequence. */
  public A357603() {
    super(0);
  }

  @Override
  public Z next() {
    return mSeq1.next().subtract(mSeq2.next());
  }
}
