package irvine.oeis.a076;
// Generated by gen_seq4.pl dfinite/holos at 2022-07-30 21:33

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A076540 Number of branches in all ordered trees with n edges.
 * @author Georg Fischer
 */
public class A076540 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A076540() {
    super(1, "[[0],[28,-8],[-24, 14],[1,-7],[1, 1]]", "1, 3, 11, 41", 0);
  }
}
