package irvine.oeis.a076;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-09-13 11:40

import irvine.factor.factor.Jaguar;
import irvine.math.z.Euler;
import irvine.oeis.LambdaSequence;

/**
 * A076685 a(n) = max(core(n),phi(n)) where core(n) is the squarefree part of n.
 * a(n) = max(core(n),eulerphi(n))
 * @author Georg Fischer
 */
public class A076685 extends LambdaSequence {

  /** Construct the sequence. */
  public A076685() {
    super(1, n -> Jaguar.factor(n).core().max(Euler.phiAsLong(n)));
  }
}
