package irvine.oeis.a352;
// Generated by gen_seq4.pl 2025-01-25.ack/poly at 2025-01-25 22:44

import irvine.oeis.PolynomialFieldSequence;

/**
 * A352066 a(0) = 1; a(n) = Sum_{k=0..floor((n-1)/4)} binomial(n-1,4*k) * a(k).
 * G.f.A(x) satisfies: A(x) = 1 + x * A(x^4/(1 - x)^4) / (1 - x).
 * @author Georg Fischer
 */
public class A352066 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A352066() {
    super(0, "[[1],[1,-1]]", ",p0,x,^4,p1,^4,/,sub,p1,/,<1,+");
  }
}
