package irvine.oeis.a352;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-25 11:10

import irvine.math.z.Integers;
import irvine.math.z.Stirling;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A352113 Expansion of e.g.f. (1 - log(1 - 3*x))^(1/3).
 * a(n) = sum(k=0,n,(-3)^(n-k)*prod(j=0,k-1,-3*j+1)*stirl(n,k,1));
 * @author Georg Fischer
 */
public class A352113 extends LambdaSequence {

  /** Construct the sequence. */
  public A352113() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Z.valueOf(-3).pow(n - k).multiply(Integers.SINGLETON.product(0, k - 1, j -> Z.ZERO.subtract(Z.THREE.multiply(j)).add(Z.ONE))).multiply(Stirling.firstKind(n, k))));
  }
}
