package irvine.oeis.a352;
// Generated by gen_seq4.pl genet/geneth at 2023-05-08 19:40

import irvine.math.z.Z;
import irvine.oeis.a061.A061345;
import irvine.oeis.transform.GeneralizedEulerTransform;

/**
 * A352165 Number of partitions of n into odd prime powers (1 included).
 * G.f.: <code>Product_{k&gt;=0} (1/(1-x^A061345(k)))</code>
 * @author Georg Fischer
 */
public class A352165 extends GeneralizedEulerTransform {

  /** Construct the sequence. */
  public A352165() {
    super(0, 0);
    mSeqH = new A061345();
    mNextH = advanceH(mKh);
  }

  @Override
  protected Z advanceH(final long k) {
    return mSeqH.next();
  }

}
