package irvine.oeis.a352;
// Generated by gen_seq4.pl manch4/insect2 at 2024-03-12 13:36

import irvine.oeis.IntersectionSequence;
import irvine.oeis.a000.A000290;
import irvine.oeis.a066.A066207;

/**
 * A352141 Numbers whose prime factorization has all even indices and all even exponents.
 * @author Georg Fischer
 */
public class A352141 extends IntersectionSequence {

  /** Construct the sequence. */
  public A352141() {
    super(new A000290(), new A066207());
  }
}
