package irvine.oeis.a352;
// Generated by gen_seq4.pl 2025-06-09.ack/polyex

import irvine.oeis.PolynomialFieldSequence;

/**
 * A352648 Expansion of e.g.f. 1/(1 - 2 * x * cosh(x)).
 * E.g.f.: <code>1/(1-2*x*cosh(x))</code>.
 * @author Georg Fischer
 */
public class A352648 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A352648() {
    super(0, "[1]", "1,1,2,x,*,x,cosh,*,-,/", 0, 1);
  }
}
