package irvine.oeis.a115;
// Generated by gen_seq4.pl holos [[0],[-12,4],[108,-48],[-225,151],[27,-42],[0,3]] [1,6,44,336,2600] 0 at 2020-02-15 22:07
// Recurrence: 3*n*a[n+0]+3*(9-14*n)*a[n-1]+(151*n-225)*a[n-2]+12*(9-4*n)*a[n-3]+4*(n-3)*a[n-4]=0
// DO NOT EDIT here!

import irvine.oeis.HolonomicRecurrence;

/**
 * A115969 Expansion of 1/(2*sqrt(1-6*x+x^2) - 1).
 * @author Georg Fischer
 */
public class A115969 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A115969() {
    super(0, "[[0],[-12,4],[108,-48],[-225,151],[27,-42],[0,3]]", "[1,6,44,336,2600]", 0);
  }
}
