package irvine.util.string;

import junit.framework.TestCase;

/**
 * Tests the corresponding class.
 * @author Sean A. Irvine
 */
public class EnglishTest extends TestCase {

  public void testIntToEnglishText() {
    assertEquals("zero", English.SINGLETON.toText(0));
    assertEquals("one", English.SINGLETON.toText(1));
    assertEquals("two", English.SINGLETON.toText(2));
    assertEquals("three", English.SINGLETON.toText(3));
    assertEquals("four", English.SINGLETON.toText(4));
    assertEquals("five", English.SINGLETON.toText(5));
    assertEquals("six", English.SINGLETON.toText(6));
    assertEquals("seven", English.SINGLETON.toText(7));
    assertEquals("eight", English.SINGLETON.toText(8));
    assertEquals("nine", English.SINGLETON.toText(9));
    assertEquals("ten", English.SINGLETON.toText(10));
    assertEquals("eleven", English.SINGLETON.toText(11));
    assertEquals("twelve", English.SINGLETON.toText(12));
    assertEquals("thirteen", English.SINGLETON.toText(13));
    assertEquals("fourteen", English.SINGLETON.toText(14));
    assertEquals("fifteen", English.SINGLETON.toText(15));
    assertEquals("sixteen", English.SINGLETON.toText(16));
    assertEquals("seventeen", English.SINGLETON.toText(17));
    assertEquals("eighteen", English.SINGLETON.toText(18));
    assertEquals("nineteen", English.SINGLETON.toText(19));
    assertEquals("twenty", English.SINGLETON.toText(20));
    assertEquals("twenty-one", English.SINGLETON.toText(21));
    assertEquals("twenty-two", English.SINGLETON.toText(22));
    assertEquals("twenty-three", English.SINGLETON.toText(23));
    assertEquals("twenty-four", English.SINGLETON.toText(24));
    assertEquals("twenty-five", English.SINGLETON.toText(25));
    assertEquals("twenty-six", English.SINGLETON.toText(26));
    assertEquals("twenty-seven", English.SINGLETON.toText(27));
    assertEquals("twenty-eight", English.SINGLETON.toText(28));
    assertEquals("twenty-nine", English.SINGLETON.toText(29));
    assertEquals("thirty", English.SINGLETON.toText(30));
    assertEquals("thirty-one", English.SINGLETON.toText(31));
    assertEquals("thirty-two", English.SINGLETON.toText(32));
    assertEquals("thirty-three", English.SINGLETON.toText(33));
    assertEquals("thirty-four", English.SINGLETON.toText(34));
    assertEquals("thirty-five", English.SINGLETON.toText(35));
    assertEquals("thirty-six", English.SINGLETON.toText(36));
    assertEquals("thirty-seven", English.SINGLETON.toText(37));
    assertEquals("thirty-eight", English.SINGLETON.toText(38));
    assertEquals("thirty-nine", English.SINGLETON.toText(39));
    assertEquals("forty", English.SINGLETON.toText(40));
    assertEquals("forty-one", English.SINGLETON.toText(41));
    assertEquals("forty-two", English.SINGLETON.toText(42));
    assertEquals("forty-three", English.SINGLETON.toText(43));
    assertEquals("forty-four", English.SINGLETON.toText(44));
    assertEquals("forty-five", English.SINGLETON.toText(45));
    assertEquals("forty-six", English.SINGLETON.toText(46));
    assertEquals("forty-seven", English.SINGLETON.toText(47));
    assertEquals("forty-eight", English.SINGLETON.toText(48));
    assertEquals("forty-nine", English.SINGLETON.toText(49));
    assertEquals("fifty", English.SINGLETON.toText(50));
    assertEquals("fifty-one", English.SINGLETON.toText(51));
    assertEquals("fifty-two", English.SINGLETON.toText(52));
    assertEquals("fifty-three", English.SINGLETON.toText(53));
    assertEquals("fifty-four", English.SINGLETON.toText(54));
    assertEquals("fifty-five", English.SINGLETON.toText(55));
    assertEquals("fifty-six", English.SINGLETON.toText(56));
    assertEquals("fifty-seven", English.SINGLETON.toText(57));
    assertEquals("fifty-eight", English.SINGLETON.toText(58));
    assertEquals("fifty-nine", English.SINGLETON.toText(59));
    assertEquals("sixty", English.SINGLETON.toText(60));
    assertEquals("sixty-one", English.SINGLETON.toText(61));
    assertEquals("sixty-two", English.SINGLETON.toText(62));
    assertEquals("sixty-three", English.SINGLETON.toText(63));
    assertEquals("sixty-four", English.SINGLETON.toText(64));
    assertEquals("sixty-five", English.SINGLETON.toText(65));
    assertEquals("sixty-six", English.SINGLETON.toText(66));
    assertEquals("sixty-seven", English.SINGLETON.toText(67));
    assertEquals("sixty-eight", English.SINGLETON.toText(68));
    assertEquals("sixty-nine", English.SINGLETON.toText(69));
    assertEquals("seventy", English.SINGLETON.toText(70));
    assertEquals("seventy-one", English.SINGLETON.toText(71));
    assertEquals("seventy-two", English.SINGLETON.toText(72));
    assertEquals("seventy-three", English.SINGLETON.toText(73));
    assertEquals("seventy-four", English.SINGLETON.toText(74));
    assertEquals("seventy-five", English.SINGLETON.toText(75));
    assertEquals("seventy-six", English.SINGLETON.toText(76));
    assertEquals("seventy-seven", English.SINGLETON.toText(77));
    assertEquals("seventy-eight", English.SINGLETON.toText(78));
    assertEquals("seventy-nine", English.SINGLETON.toText(79));
    assertEquals("eighty", English.SINGLETON.toText(80));
    assertEquals("eighty-one", English.SINGLETON.toText(81));
    assertEquals("eighty-two", English.SINGLETON.toText(82));
    assertEquals("eighty-three", English.SINGLETON.toText(83));
    assertEquals("eighty-four", English.SINGLETON.toText(84));
    assertEquals("eighty-five", English.SINGLETON.toText(85));
    assertEquals("eighty-six", English.SINGLETON.toText(86));
    assertEquals("eighty-seven", English.SINGLETON.toText(87));
    assertEquals("eighty-eight", English.SINGLETON.toText(88));
    assertEquals("eighty-nine", English.SINGLETON.toText(89));
    assertEquals("ninety", English.SINGLETON.toText(90));
    assertEquals("ninety-one", English.SINGLETON.toText(91));
    assertEquals("ninety-two", English.SINGLETON.toText(92));
    assertEquals("ninety-three", English.SINGLETON.toText(93));
    assertEquals("ninety-four", English.SINGLETON.toText(94));
    assertEquals("ninety-five", English.SINGLETON.toText(95));
    assertEquals("ninety-six", English.SINGLETON.toText(96));
    assertEquals("ninety-seven", English.SINGLETON.toText(97));
    assertEquals("ninety-eight", English.SINGLETON.toText(98));
    assertEquals("ninety-nine", English.SINGLETON.toText(99));
    assertEquals("one hundred", English.SINGLETON.toText(100));
    assertEquals("one thousand", English.SINGLETON.toText(1000));
    assertEquals("twenty thousand", English.SINGLETON.toText(20000));
    assertEquals("twenty thousand two hundred and two", English.SINGLETON.toText(20202));
    assertEquals("forty thousand", English.SINGLETON.toText(40000));
    assertEquals("forty thousand and fourteen", English.SINGLETON.toText(40014));
    assertEquals("one million", English.SINGLETON.toText(1000000));
    assertEquals("thirty-one thousand four hundred and fifteen", English.SINGLETON.toText(31415));
    assertEquals("thirty thousand two hundred", English.SINGLETON.toText(30200));
    assertEquals("two hundred thousand", English.SINGLETON.toText(200000));
    assertEquals("two hundred and one thousand", English.SINGLETON.toText(201000));
    assertEquals("two hundred thousand two hundred and two", English.SINGLETON.toText(200202));
    assertEquals("one million one hundred", English.SINGLETON.toText(1000100));
    assertEquals("one million one thousand", English.SINGLETON.toText(1001000));
    assertEquals("one million one thousand and thirty", English.SINGLETON.toText(1001030));
    assertEquals("one million two hundred and seventeen thousand three hundred and fourteen", English.SINGLETON.toText(1217314));
    assertEquals("nineteen million nine hundred and ninety-nine thousand nine hundred and ninety-nine", English.SINGLETON.toText(19999999));
    assertEquals("twenty-one million one hundred and twenty-one thousand one hundred and twenty-one", English.SINGLETON.toText(21121121));

    for (int i = 1; i < 1000; ++i) {
      assertEquals("negative " + English.SINGLETON.toText(i), English.SINGLETON.toText(-i));
    }
  }

  public void testIntToRawEnglishText() {
    assertEquals("zero", English.SINGLETON.toRawText(0));
    assertEquals("one", English.SINGLETON.toRawText(1));
    assertEquals("two", English.SINGLETON.toRawText(2));
    assertEquals("three", English.SINGLETON.toRawText(3));
    assertEquals("four", English.SINGLETON.toRawText(4));
    assertEquals("five", English.SINGLETON.toRawText(5));
    assertEquals("six", English.SINGLETON.toRawText(6));
    assertEquals("seven", English.SINGLETON.toRawText(7));
    assertEquals("eight", English.SINGLETON.toRawText(8));
    assertEquals("nine", English.SINGLETON.toRawText(9));
    assertEquals("ten", English.SINGLETON.toRawText(10));
    assertEquals("eleven", English.SINGLETON.toRawText(11));
    assertEquals("twelve", English.SINGLETON.toRawText(12));
    assertEquals("thirteen", English.SINGLETON.toRawText(13));
    assertEquals("fourteen", English.SINGLETON.toRawText(14));
    assertEquals("fifteen", English.SINGLETON.toRawText(15));
    assertEquals("sixteen", English.SINGLETON.toRawText(16));
    assertEquals("seventeen", English.SINGLETON.toRawText(17));
    assertEquals("eighteen", English.SINGLETON.toRawText(18));
    assertEquals("nineteen", English.SINGLETON.toRawText(19));
    assertEquals("twenty", English.SINGLETON.toRawText(20));
    assertEquals("twentyone", English.SINGLETON.toRawText(21));
    assertEquals("twentytwo", English.SINGLETON.toRawText(22));
    assertEquals("twentythree", English.SINGLETON.toRawText(23));
    assertEquals("twentyfour", English.SINGLETON.toRawText(24));
    assertEquals("twentyfive", English.SINGLETON.toRawText(25));
    assertEquals("twentysix", English.SINGLETON.toRawText(26));
    assertEquals("twentyseven", English.SINGLETON.toRawText(27));
    assertEquals("twentyeight", English.SINGLETON.toRawText(28));
    assertEquals("twentynine", English.SINGLETON.toRawText(29));
    assertEquals("thirty", English.SINGLETON.toRawText(30));
    assertEquals("thirtyone", English.SINGLETON.toRawText(31));
    assertEquals("thirtytwo", English.SINGLETON.toRawText(32));
    assertEquals("thirtythree", English.SINGLETON.toRawText(33));
    assertEquals("thirtyfour", English.SINGLETON.toRawText(34));
    assertEquals("thirtyfive", English.SINGLETON.toRawText(35));
    assertEquals("thirtysix", English.SINGLETON.toRawText(36));
    assertEquals("thirtyseven", English.SINGLETON.toRawText(37));
    assertEquals("thirtyeight", English.SINGLETON.toRawText(38));
    assertEquals("thirtynine", English.SINGLETON.toRawText(39));
    assertEquals("forty", English.SINGLETON.toRawText(40));
    assertEquals("fortyone", English.SINGLETON.toRawText(41));
    assertEquals("fortytwo", English.SINGLETON.toRawText(42));
    assertEquals("fortythree", English.SINGLETON.toRawText(43));
    assertEquals("fortyfour", English.SINGLETON.toRawText(44));
    assertEquals("fortyfive", English.SINGLETON.toRawText(45));
    assertEquals("fortysix", English.SINGLETON.toRawText(46));
    assertEquals("fortyseven", English.SINGLETON.toRawText(47));
    assertEquals("fortyeight", English.SINGLETON.toRawText(48));
    assertEquals("fortynine", English.SINGLETON.toRawText(49));
    assertEquals("fifty", English.SINGLETON.toRawText(50));
    assertEquals("fiftyone", English.SINGLETON.toRawText(51));
    assertEquals("fiftytwo", English.SINGLETON.toRawText(52));
    assertEquals("fiftythree", English.SINGLETON.toRawText(53));
    assertEquals("fiftyfour", English.SINGLETON.toRawText(54));
    assertEquals("fiftyfive", English.SINGLETON.toRawText(55));
    assertEquals("fiftysix", English.SINGLETON.toRawText(56));
    assertEquals("fiftyseven", English.SINGLETON.toRawText(57));
    assertEquals("fiftyeight", English.SINGLETON.toRawText(58));
    assertEquals("fiftynine", English.SINGLETON.toRawText(59));
    assertEquals("sixty", English.SINGLETON.toRawText(60));
    assertEquals("sixtyone", English.SINGLETON.toRawText(61));
    assertEquals("sixtytwo", English.SINGLETON.toRawText(62));
    assertEquals("sixtythree", English.SINGLETON.toRawText(63));
    assertEquals("sixtyfour", English.SINGLETON.toRawText(64));
    assertEquals("sixtyfive", English.SINGLETON.toRawText(65));
    assertEquals("sixtysix", English.SINGLETON.toRawText(66));
    assertEquals("sixtyseven", English.SINGLETON.toRawText(67));
    assertEquals("sixtyeight", English.SINGLETON.toRawText(68));
    assertEquals("sixtynine", English.SINGLETON.toRawText(69));
    assertEquals("seventy", English.SINGLETON.toRawText(70));
    assertEquals("seventyone", English.SINGLETON.toRawText(71));
    assertEquals("seventytwo", English.SINGLETON.toRawText(72));
    assertEquals("seventythree", English.SINGLETON.toRawText(73));
    assertEquals("seventyfour", English.SINGLETON.toRawText(74));
    assertEquals("seventyfive", English.SINGLETON.toRawText(75));
    assertEquals("seventysix", English.SINGLETON.toRawText(76));
    assertEquals("seventyseven", English.SINGLETON.toRawText(77));
    assertEquals("seventyeight", English.SINGLETON.toRawText(78));
    assertEquals("seventynine", English.SINGLETON.toRawText(79));
    assertEquals("eighty", English.SINGLETON.toRawText(80));
    assertEquals("eightyone", English.SINGLETON.toRawText(81));
    assertEquals("eightytwo", English.SINGLETON.toRawText(82));
    assertEquals("eightythree", English.SINGLETON.toRawText(83));
    assertEquals("eightyfour", English.SINGLETON.toRawText(84));
    assertEquals("eightyfive", English.SINGLETON.toRawText(85));
    assertEquals("eightysix", English.SINGLETON.toRawText(86));
    assertEquals("eightyseven", English.SINGLETON.toRawText(87));
    assertEquals("eightyeight", English.SINGLETON.toRawText(88));
    assertEquals("eightynine", English.SINGLETON.toRawText(89));
    assertEquals("ninety", English.SINGLETON.toRawText(90));
    assertEquals("ninetyone", English.SINGLETON.toRawText(91));
    assertEquals("ninetytwo", English.SINGLETON.toRawText(92));
    assertEquals("ninetythree", English.SINGLETON.toRawText(93));
    assertEquals("ninetyfour", English.SINGLETON.toRawText(94));
    assertEquals("ninetyfive", English.SINGLETON.toRawText(95));
    assertEquals("ninetysix", English.SINGLETON.toRawText(96));
    assertEquals("ninetyseven", English.SINGLETON.toRawText(97));
    assertEquals("ninetyeight", English.SINGLETON.toRawText(98));
    assertEquals("ninetynine", English.SINGLETON.toRawText(99));
    assertEquals("onehundred", English.SINGLETON.toRawText(100));
    assertEquals("onethousand", English.SINGLETON.toRawText(1000));
    assertEquals("twentythousand", English.SINGLETON.toRawText(20000));
    assertEquals("twentythousandtwohundredtwo", English.SINGLETON.toRawText(20202));
    assertEquals("fortythousand", English.SINGLETON.toRawText(40000));
    assertEquals("fortythousandfourteen", English.SINGLETON.toRawText(40014));
    assertEquals("onemillion", English.SINGLETON.toRawText(1000000));
    assertEquals("thirtyonethousandfourhundredfifteen", English.SINGLETON.toRawText(31415));
    assertEquals("thirtythousandtwohundred", English.SINGLETON.toRawText(30200));
    assertEquals("twohundredthousand", English.SINGLETON.toRawText(200000));
    assertEquals("twohundredonethousand", English.SINGLETON.toRawText(201000));
    assertEquals("twohundredthousandtwohundredtwo", English.SINGLETON.toRawText(200202));
    assertEquals("onemilliononehundred", English.SINGLETON.toRawText(1000100));
    assertEquals("onemilliononethousand", English.SINGLETON.toRawText(1001000));
    assertEquals("onemilliononethousandthirty", English.SINGLETON.toRawText(1001030));
    assertEquals("onemilliontwohundredseventeenthousandthreehundredfourteen", English.SINGLETON.toRawText(1217314));
    assertEquals("nineteenmillionninehundredninetyninethousandninehundredninetynine", English.SINGLETON.toRawText(19999999));
    try {
      English.SINGLETON.toRawText(20000000);
      fail();
    } catch (final UnsupportedOperationException e) {
      //ok
    }
    try {
      English.SINGLETON.toRawText(-1);
      fail();
    } catch (final UnsupportedOperationException e) {
      //ok
    }
  }
}
