package irvine.oeis.a126;
// Generated by gen_seq4.pl 2024-07-24.ack/sintrif at 2024-07-24 22:30

import irvine.math.function.Functions;
import irvine.oeis.a052.A052126;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A126289 a(1) = 1, a(2) = 1, a(n) = n * LargestPrimeFactor(n-1) / LargestPrimeFactor(n).
 * @author Georg Fischer
 */
public class A126289 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A126289() {
    super(1, (term, n) -> Functions.GPF.z(n - 1).multiply(term), "1, 1, 2", new A052126());
  }
}
