package irvine.oeis.a126;
// Generated by gen_seq4.pl decsolv at 2021-08-10 22:10

import irvine.math.cr.CR;
import irvine.math.cr.UnaryCrFunction;
import irvine.oeis.cons.DecimalExpansionSequence;

/**
 * A126583 Decimal expansion of solution to exp(-x) = x^2.
 * Equation; exp(-x)-(x^2)
 * @author Georg Fischer
 */
public class A126583 extends DecimalExpansionSequence {

  /** Construct the sequence. */
  public A126583() {
    super(0, new UnaryCrFunction() {
      @Override 
      public CR execute(final CR x) {
        return x.negate().exp().subtract(x.square());
      }
    }.inverseMonotone(CR.valueOf(0.689), CR.valueOf(0.717)).execute(CR.ZERO));
  }
}
