package irvine.oeis.a265;
// Generated by gen_seq4.pl egfsi at 2021-12-01 15:37

import irvine.math.group.PolynomialRingField;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.Sequence;

/**
 * A265325 Number of n-digit decimal numbers with leading zeros allowed where no digit appears exactly twice.
 * E.g.f.: (exp(x)-x^2/2)^10
 * @author Georg Fischer
 */
public class A265325 implements Sequence {

  private static final PolynomialRingField<Q> RING = new PolynomialRingField<>(Rationals.SINGLETON);
  private int mN = 0;
  private Z mF = Z.ONE;

  @Override
  public Z next() {
    if (++mN != 0) {
      mF = mF.multiply(mN);
    }
    return RING.pow(RING.subtract(RING.exp(RING.x(), mN), RING.series(RING.pow(RING.x(), 2, mN), RING.monomial(new Q(2), 0), mN)), 10, mN).coeff(mN).multiply(mF).toZ();
  }
}
