package irvine.oeis.a265;
// Generated by gen_seq4.pl 2025-10-07.ack/rpt at 2025-10-07 23:30

import irvine.oeis.transform.RationalProductTransform;

/**
 * A265832 Expansion of Product_{k&gt;=1} 1/(1 - (5*k-2)*x^(5*k-2)).
 * @author Georg Fischer
 */
public class A265832 extends RationalProductTransform {

  /** Construct the sequence. */
  public A265832() {
    super(0, new Builder().gl(k -> k % 5 == 3 ? k : 0L));
  }
}
