package irvine.oeis.a285;
// Generated by gen_seq4.pl posins at 2020-06-21 23:01
// DO NOT EDIT here!

import irvine.oeis.PositionSequence;


/**
 * A285402 Positions of 1 in A285177; complement of A285401.
 * @author Georg Fischer
 */
public class A285402 extends PositionSequence {

  /** Construct the sequence. */
  public A285402() {
    super(1, new A285177(), 1);
  }
}
