package irvine.oeis.a285;
// Generated by gen_seq4.pl 2025-10-06.ack/rpt at 2025-10-06 19:06

import irvine.oeis.a000.A000009;
import irvine.oeis.transform.RationalProductTransform;

/**
 * A285230 Number of multisets of exactly n partitions of positive integers into distinct parts with total sum of parts equal to 2n.
 * @author Georg Fischer
 */
public class A285230 extends RationalProductTransform {

  /** Construct the sequence. */
  public A285230() {
    super(0, new Builder().f(new A000009().skip(1)));
  }
}
