package irvine.oeis.a285;
// Generated by gen_seq4.pl posins at 2020-06-21 23:01
// DO NOT EDIT here!

import irvine.oeis.PositionSequence;


/**
 * A285412 Positions of 0 in A285411; complement of A285413.
 * @author Georg Fischer
 */
public class A285412 extends PositionSequence {

  /** Construct the sequence. */
  public A285412() {
    super(1, new A285411(), 0);
  }
}
