package irvine.oeis.a285;
// Generated by gen_seq4.pl 2023-12-02/holos at 2023-12-03 21:34

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A285232 Number of entries in the fourth cycles of all permutations of [n].
 * @author Georg Fischer
 */
public class A285232 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A285232() {
    super(4, "[[0],[0, 81,-108, 54,-12, 1],[-16, 81,-76, 26,-3],[-12, 32,-19, 3],[-4, 5,-1]]", "1, 12, 119", 0);
  }
}
