package irvine.oeis.a285;
// Generated by gen_seq4.pl posins at 2021-09-24 13:55

import irvine.oeis.FilterPositionSequence;

/**
 * A285964 Positions of 0 in A285963; complement of A285965.
 * @author Georg Fischer
 */
public class A285964 extends FilterPositionSequence {

  /** Construct the sequence. */
  public A285964() {
    super(1, new A285963(), 0);
  }
}
