package irvine.oeis.a162;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a001.A001791;

/**
 * A162551 a(n) = 2 * C(2*n,n-1).
 * @author Georg Fischer
 */
public class A162551 implements Sequence {

  final Sequence mA001791 = new A001791();
  /** Construct the sequence. */
  public A162551() {
  }
  
  @Override
  public Z next() {
    return Z.TWO.multiply(mA001791.next());
  }

}
