package irvine.oeis.a162;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a001.A001221;

/**
 * A162641 Number of even exponents in canonical prime factorization of n.
 * @author Georg Fischer
 */
public class A162641 implements Sequence {

  final Sequence mA001221 = new A001221();
  final Sequence mA162642 = new A162642();
  @Override
  public Z next() {
    return mA001221.next().subtract(mA162642.next());
  }

}
