package irvine.oeis.a162;
// Generated by gen_seq4.pl filterm/filter at 2023-09-11 18:58

import irvine.oeis.FilterSequence;
import irvine.oeis.a005.A005448;

/**
 * A162703 Palindromes in A005448.
 * @author Georg Fischer
 */
public class A162703 extends FilterSequence {

  /** Construct the sequence. */
  public A162703() {
    super(1, new A005448(), PALINDROME);
  }
}
