package irvine.oeis.a162;
// Generated by gen_seq4.pl bref at 2020-11-27 17:17
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.BriefSequence;


/**
 * A162187 a(0)=4 and a(n+1)=a(n)!.
 *
 * @author Georg Fischer
 */
public class A162187 extends BriefSequence {

  /** Construct the sequence. */
  public A162187() {
    super(Z.FOUR, new Z("24"), new Z("620448401733239439360000"));
  }
}
