package irvine.oeis.a283;
// Generated by gen_seq4.pl 2026-02-13.ack/filnum at 2026-02-13 16:26

import irvine.math.predicate.Predicates;
import irvine.math.z.Z;
import irvine.oeis.FilterNumberSequence;

/**
 * A283809 Squarefree numbers k such that 6*k - 1 and 6*k + 1 are twin primes.
 * @author Georg Fischer
 */
public class A283809 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A283809() {
    super(1, 1, k -> {
      final Z f = Z.valueOf(6 * k);
      return Predicates.SQUARE_FREE.is(k) && Predicates.PRIME.is(f.subtract(1)) && Predicates.PRIME.is(f.add(1));
    });
  }
}
