package irvine.oeis.a283;
// Generated by gen_seq4.pl bref at 2020-11-27 17:17

import irvine.math.z.Z;
import irvine.oeis.BriefSequence;

/**
 * A283840 Number of ternary maps f : S X S X S -&gt; S on a set S of n elements which can be represented as a superposition of binary maps * : S X S -&gt; S (Version 1).
 *
 * @author Georg Fischer
 */
public class A283840 extends BriefSequence {

  /** Construct the sequence. */
  public A283840() {
    super(1, BRIEF, Z.ONE, new Z("14"), new Z("19292"));
  }
}
