package irvine.oeis.a283;
// Generated by gen_seq4.pl eulerxfm 0 0 at 2020-09-17 12:15
// DO NOT EDIT here!

import irvine.oeis.CharacteristicFunction;
import irvine.oeis.EulerTransform;
import irvine.oeis.a001.A001097;


/**
 * A283875 Number of partitions of n into twin primes (A001097).
 * @author Georg Fischer
 */
public class A283875 extends EulerTransform {

  /** Construct the sequence. */
  public A283875() {
    super(new CharacteristicFunction(new A001097()), 1);
  }
}
