package irvine.oeis.a283;
// Generated by gen_seq4.pl 2026-07-02.ack/polya at 2026-07-02 22:33

import irvine.oeis.PolynomialFieldSequence;
import irvine.oeis.a010.A010051;
import irvine.oeis.a010.A010057;

/**
 * A283760 Expansion of (Sum_{i&gt;=1} x^prime(i))*(Sum_{j&gt;=1} x^(j^3)).
 * new A010051(), new A010057()
 * @author Georg Fischer
 */
public class A283760 extends PolynomialFieldSequence {

  /** Construct the sequence. */
  public A283760() {
    super(1, "[0,1]", "x,B,x,C,1,-,*", 0, 0, 1, 1, new A010051(), new A010057());
  }
}
