package irvine.oeis.a262;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A262760 Number of (3+2)X(n+2) 0..1 arrays with each row divisible by 5 and each column divisible by 7, read as a binary number with top and left being the most significant bits.
 * @author Georg Fischer
 */
public class A262760 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A262760() {
    super(1, "[0,7046875,-1409375,0,0,-1853750,370750,0,0,96000,-19200,0,0,-1450,290,0,0,5,-1]", "5,25,49,129,709,4953,16705,73345,384485,2252185,9821425,47556225,241769125,1278440025,6106506625,30240858625,152043549125", 0, 0);
  }
}
