package irvine.oeis.a262;
// Generated by gen_seq4.pl A078847/parm2 at 2022-02-17 23:30

import irvine.oeis.a257.A257638;

/**
 * A262176 Numbers n where n-17, n-1, n+1 and n+17 are consecutive primes.
 * @author Georg Fischer
 */
public class A262176 extends A257638 {

  /** Construct the sequence. */
  public A262176() {
    super(17);
  }
}
