package irvine.oeis.a262;
// Generated by gen_seq4.pl 2024-07-13/sintraf at 2024-07-13 23:12

import irvine.math.z.Z;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A262644 Base-10 representation of the primes at A262643.
 * @author Georg Fischer
 */
public class A262644 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A262644() {
    super(1, (term, n) -> new Z(term.toString(), 5), new A262643());
  }
}
