package irvine.oeis.a262;
// Generated by gen_seq4.pl 2025-07-06.ack/rambdan at 2025-07-06 20:53

import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.math.z.Z;
import irvine.oeis.RationalLambdaSequence;

/**
 * A262856 Numerators of the Nielsen-Jacobsthal series leading to Euler&apos;s constant.
 * @author Georg Fischer
 */
public class A262856 extends RationalLambdaSequence {

  /** Construct the sequence. */
  public A262856() {
    super(1, NUM, n -> Rationals.SINGLETON.sum((1 << n) + 1, 1 << (n + 1), k -> new Q(Z.NEG_ONE.pow(k + 1), k)).multiply(n));
  }
}
