package irvine.oeis.a194;
// Generated by gen_seq4.pl 2025-02-24.ack/parmof3 at 2025-02-24 19:24

import irvine.math.cr.CR;

/**
 * A194756 Number of k such that {-k*Pi} &lt; {-n*Pi}, where { } = fractional part.
 * @author Georg Fischer
 */
public class A194756 extends A194733 {

  /** Construct the sequence. */
  public A194756() {
    super(1, CR.PI.negate(), -1);
  }
}
