package irvine.oeis.a021;
// Generated by gen_linrec.pl - DO NOT EDIT here!

import irvine.oeis.LinearRecurrence;

/**
 * A021874 Expansion of 1/((1-x)(1-4x)(1-7x)(1-10x)). 
 * @author Georg Fischer
 */
public class A021874 extends LinearRecurrence {

  /** Construct the sequence. */
  public A021874() {
    super(new long[] {-280L, 418L, -159L, 22L}, new long[] {1L, 22L, 325L, 4070L});
  } // constructor()
} // A021874
