package irvine.oeis.a033;
// Generated by gen_seq4.pl diffseq at 2020-06-21 22:58
// DO NOT EDIT here!

import irvine.oeis.DifferenceSequence;
import irvine.oeis.a026.A026012;

/**
 * A033434 Third differences of Catalan numbers <code>A000108</code>.
 * @author Georg Fischer
 */
public class A033434 extends DifferenceSequence {

  /** Construct the sequence. */
  public A033434() {
    super(new A026012());
  }
}
