package irvine.oeis.a033;
// Generated by gen_seq4.pl trajen at 2020-11-30 22:58
// DO NOT EDIT here!

/**
 * A033979 Trajectory of 1 under map n-&gt;47n+1 if n odd, n-&gt;n/2 if n even.
 * @author Georg Fischer
 */
public class A033979 extends A033962 {

  /** Construct the sequence. */
  public A033979() {
    super(1, 47);
  }
}
