package irvine.oeis.a220;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A220721 Number of ways to reciprocally link elements of an nX4 array either to themselves or to exactly two horizontal, diagonal or antidiagonal neighbors.
 * @author Georg Fischer
 */
public class A220721 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A220721() {
    super(1, "[0,-1,-1,13,21,-34,-76,-90,51,65,64,20,9,-1]", "1,21,230,2586,29310,331589,3751888,42452438,480346122,5435081884,61497557384,695840407309", 0, 0);
  }
}
