package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 684 at 2019-07-04 10:53
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040657 Continued fraction for <code>sqrt(684)</code>.
 * @author Georg Fischer
 */
public class A040657 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040657() {
    super(0, 684);
  }

  @Override
  public Z next() {
    final Z result = Z.valueOf(mB0);
    iterate();
    return result;
  }
}
