package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 210 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.cons.ContinuedFractionOfSqrtSequence;

/**
 * A040195 Continued fraction for sqrt(210).
 * @author Georg Fischer
 */
public class A040195 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040195() {
    super(0, 210);
  }
}
