package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 294 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040276 Continued fraction for sqrt(294).
 * @author Georg Fischer
 */
public class A040276 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040276() {
    super(0, 294);
  }
}
