package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 123 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.cons.ContinuedFractionOfSqrtSequence;

/**
 * A040111 Continued fraction for sqrt(123).
 * @author Georg Fischer
 */
public class A040111 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040111() {
    super(0, 123);
  }
}
