package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 839 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040810 Continued fraction for sqrt(839).
 * @author Georg Fischer
 */
public class A040810 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040810() {
    super(0, 839);
  }
}
