package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 147 at 2019-07-04 10:53
// DO NOT EDIT here!

import irvine.math.z.Z;
import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040134 Continued fraction for sqrt(147).
 * @author Georg Fischer
 */
public class A040134 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040134() {
    super(0, 147);
  }

  @Override
  public Z next() {
    final Z result = Z.valueOf(mB0);
    iterate();
    return result;
  }
}
