package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 917 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040886 Continued fraction for sqrt(917).
 * @author Georg Fischer
 */
public class A040886 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040886() {
    super(0, 917);
  }
}
