package irvine.oeis.a040;
// Generated by gen_seq4.pl cfsqrt 821 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A040792 Continued fraction for sqrt(821).
 * @author Georg Fischer
 */
public class A040792 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A040792() {
    super(0, 821);
  }
}
