package irvine.oeis.a389;
// Generated by gen_seq4.pl 2025-11-29.ack/holos at 2025-11-29 12:50

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A389582 Lower (1/2,1/3) midsequence of (n^2) and (n^3); see Comments.
 * @author Georg Fischer
 */
public class A389582 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A389582() {
    super(0, "[0,-1,3,-3,1,0,0,1,-3,3,-1]", "0,0,4,13,29,54,90,138,202,283,383", 0, 0);
  }
}
