package irvine.oeis.a389;
// Generated by gen_seq4.pl 2025-10-12.ack/filnum at 2025-10-12 22:36

import irvine.math.function.Functions;
import irvine.oeis.FilterNumberSequence;

/**
 * A389462 Numbers whose sum of proper divisors (A001065) is equal to or greater than their squarefree kernel (A007947).
 * @author Georg Fischer
 */
public class A389462 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A389462() {
    super(1, 1, k -> Functions.ALIQUOT.z(k).compareTo(Functions.RAD.z(k)) >= 0);
  }
}
