package irvine.oeis.a321;
// Generated by gen_seq4.pl prodet 0 at 2020-10-12 11:47
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.a025.A025442;


/**
 * A321448 Expansion of Product_{0 < i < j < k} 1/(1 - x^(i^2 + j^2 + k^2)).
 * @author Georg Fischer
 */
public class A321448 extends EulerTransform {

  /**
   * Construct the sequence.
   */
  public A321448() {
    super(new A025442(), 1);
    mSeq.next();
  }
}
