package irvine.oeis.a321;
// Generated by gen_seq4.pl 2025-11-03.ack/filnum at 2025-11-03 19:07

import irvine.math.function.Functions;
import irvine.oeis.FilterNumberSequence;

/**
 * A321505 Numbers k such that k and k+1 each have at least 5 distinct prime factors.
 * @author Georg Fischer
 */
public class A321505 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A321505() {
    super(1, 0, k -> Functions.OMEGA.i(k) >= 5 && Functions.OMEGA.i(k + 1) >= 5);
  }
}
