package irvine.oeis.a321;
// Generated by gen_seq4.pl prodet 0 at 2020-10-12 11:47
// DO NOT EDIT here!

import irvine.oeis.EulerTransform;
import irvine.oeis.a025.A025426;


/**
 * A321437 Expansion of Product_{1 <= i <= j} 1/(1 - x^(i^2 + j^2)).
 * @author Georg Fischer
 */
public class A321437 extends EulerTransform {

  /**
   * Construct the sequence.
   */
  public A321437() {
    super(new A025426(), 1);
    mSeq.next();
  }
}
