package irvine.oeis.a321;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A321122 a(n) = n-th row common denominator of A321121.
 * @author Georg Fischer
 */
public class A321122 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A321122() {
    super(0, "[4,2,3,8,36,96,-164,256,336,32,-36,24,0,2,-9]", "[1,0,0,0,0,0,-52,0,0,0,0,0,1]");
  }
}
