package irvine.oeis.a047;
// Generated by gen_seq4.pl holos [[0],[3,-5],[1]] [1,2] 0 at 2020-02-15 22:07
// Recurrence: a[n+0]+(-5*n+3)*a[n-1]=0
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A047055 Quintuple factorial numbers: a(n) = Product_{k=0..n-1} (5*k + 2).
 * @author Georg Fischer
 */
public class A047055 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A047055() {
    super(0, "[[0],[3,-5],[1]]", "[1,2]", 0);
  }
}
