package irvine.oeis.a287;
// Generated by gen_seq4.pl morfps at 2021-09-22 21:58

import irvine.oeis.base.MorphismFixedPointSequence;

/**
 * A287356 Start with 0 and repeatedly substitute 0-&gt;11, 1-&gt;12, 2-&gt;0.
 * @author Georg Fischer
 */
public class A287356 extends MorphismFixedPointSequence {

  /** Construct the sequence. */
  public A287356() {
    super("0", "1201", "0->11, 1->12, 2->0");
  }
}
