package irvine.oeis.a287;
// Generated by gen_seq4.pl mortra at 2021-09-23 21:42

import irvine.oeis.a080.A080764;
import irvine.oeis.base.MorphismTransform;

/**
 * A287028 {0-&gt;101, 1-&gt;010}-transform of the Sturmian word A080764.
 * @author Georg Fischer
 */
public class A287028 extends MorphismTransform {

  /** Construct the sequence. */
  public A287028() {
    super(new A080764(), "0->101, 1->010");
  }
}
