package irvine.oeis.a287;
// Generated by gen_seq4.pl posins at 2021-08-26 10:15

import irvine.oeis.PositionSequence;

/**
 * A287114 Positions of 1 in A287112.
 * @author Georg Fischer
 */
public class A287114 extends PositionSequence {

  /** Construct the sequence. */
  public A287114() {
    super(1, new A287112(), 1);
  }
}
