package irvine.oeis.a287;
// Generated by gen_seq4.pl pfprime 1 8 10 -13 0 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A287208 Numbers k such that 8*10^k - 13 is prime.
 * @author Georg Fischer
 */
public class A287208 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A287208() {
    super(1, 1, 8, 10, -13);
  }
}
