package irvine.oeis.a287;
// Generated by gen_seq4.pl posins at 2021-09-21 20:57

import irvine.oeis.PositionSequence;

/**
 * A287446 Positions of 2 in A287443.
 * @author Georg Fischer
 */
public class A287446 extends PositionSequence {

  /** Construct the sequence. */
  public A287446() {
    super(1, new A287443(), 2);
  }
}
