package irvine.oeis.a166;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A166027 a(n) = 6*a(n-2) for n &gt; 2; a(1) = 4, a(2) = 1.
 * @author Georg Fischer
 */
public class A166027 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A166027() {
    super(1, new long[] {0, 4, 1},
      new long[] {1, 0, -6});
  }
}
