package irvine.oeis.a322;
// Generated by gen_seq4.pl 2026-03-16.ack/lambdan at 2026-03-16 19:26

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.oeis.LambdaSequence;

/**
 * A322673 a(n) = numerator of Product_{d|n} (sigma(d)/d) where sigma(k) = the sum of the divisors of k (A000203).
 * @author Georg Fischer
 */
public class A322673 extends LambdaSequence {

  /** Construct the sequence. */
  public A322673() {
    super(1, n -> Rationals.SINGLETON.productdiv(n, d -> new Q(Functions.SIGMA1.z(d), d)).num());
  }
}
