package irvine.oeis.a322;
// Generated by gen_seq4.pl 2026-06-23.ack/filnum at 2026-06-23 23:37

import irvine.factor.util.FactorUtils;
import irvine.math.predicate.Predicates;
import irvine.oeis.FilterNumberSequence;

/**
 * A322448 Numbers whose prime factorization contains at least one composite exponent.
 * @author Georg Fischer
 */
public class A322448 extends FilterNumberSequence {

  /** Construct the sequence. */
  public A322448() {
    super(1, 1, k -> FactorUtils.iterate(k, 0L, (x, p, e) -> x + (e > 1 && !Predicates.PRIME.is(e) ? 1 : 0)) != 0L);
  }
}
