package irvine.oeis.a239;
// Generated by gen_seq4.pl guess2cj/holoscj at 2026-07-07 22:19

import irvine.oeis.Conjectural;
import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A239334 Number of nX2 0..3 arrays with no element equal to one plus the sum of elements to its left or three plus the sum of elements above it, modulo 4.
 * @author Georg Fischer
 */
public class A239334 extends HolonomicRecurrence implements Conjectural {

  /** Construct the sequence. */
  public A239334() {
    super(1, "[0,-16,-32,104,156,-36,-268,104,-279,200,234,-261,236,-181,74,-28,9,-1]", "5,31,172,926,5078,27861,152260,832207,4550810,24881731,136029644,743697760,4065948624,22229220072,121530709245,664428372582", 0, 0);
  }
}
