package irvine.oeis.a144;
// Generated by gen_seq4.pl egfu at 2021-12-04 17:50

import irvine.math.polynomial.Polynomial;
import irvine.math.q.Q;
import irvine.oeis.ExponentialGeneratingFunction;

/**
 * A144223 Number of ways of placing n labeled balls into n unlabeled (but 6-colored) boxes.
 * E.g.f.: exp(6*(exp(x)-1))
 * @author Georg Fischer
 */
public class A144223 extends ExponentialGeneratingFunction {

  /** Construct the sequence. */
  public A144223() {
    super(0);
  }

  @Override
  public Polynomial<Q> compute(final int mN) {
    return RING.exp(RING.multiply(RING.monomial(Q.SIX, 0), RING.subtract(RING.exp(RING.x(), mN), RING.one()), mN), mN);
  }
}
