package irvine.oeis.a144;
// Generated by ./gen_seq4.pl /diffseq0 at 2022-06-26 10:36

import irvine.oeis.DifferenceSequence;
import irvine.oeis.PrependSequence;
import irvine.oeis.a134.A134955;

/**
 * A144959 A134955(n) - A134955(n-1). Number of hyperforests spanning n unlabeled nodes without isolated vertices.
 * @author Sean A. Irvine
 */
public class A144959 extends DifferenceSequence {

  /** Construct the sequence. */
  public A144959() {
    super(new PrependSequence(new A134955(), 0));
  }
}
