package irvine.oeis.a290;
// Generated by gen_seq4.pl holos at 2021-07-07 22:50

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A290380 Analog of Motzkin sums for Coxeter type D.
 * Recurrence: -(n-3)*(n-4)*n*a(n)+(n-2)*(2*n-3)*(n-4)*a(n-1)+3*(n-2)*(n-3)^2*a(n-2)=0
 * @author Georg Fischer
 */
public class A290380 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A290380() {
    super(3, "[[0],[54,-63, 24,-3],[[24,-34, 15,-2],[0, 12,-7, 1]", "[1, 4]", 0);
  }
}
