package irvine.oeis.a290;
// Generated by gen_seq4.pl pfprime 2 2 10 -69 0 at 2019-07-30 14:36
// DO NOT EDIT here!

import irvine.oeis.PowerFactorPrimeSequence;

/**
 * A290033 Numbers k such that <code>2*10^k - 69</code> is prime.
 * @author Georg Fischer
 */
public class A290033 extends PowerFactorPrimeSequence {

  /** Construct the sequence. */
  public A290033() {
    super(1, 2, 2, 10, -69, 0);
  }
}
