package irvine.oeis.a290;
// Generated by gen_seq4.pl 2024-07-01/multrar at 2024-07-01 18:26

import irvine.oeis.DirectSequence;
import irvine.oeis.a028.A028234;
import irvine.oeis.a067.A067029;
import irvine.oeis.transform.MultiTransformSequence;

/**
 * A290109 a(1) = 1; for n &gt; 1, a(n) = x1^(x2^(x3^(x4^...))) where x1, x2, ... are the exponents of the primes present (listed from the smallest prime to the largest) in the prime factorization of n.
 * @author Georg Fischer
 */
public class A290109 extends MultiTransformSequence {

  private static final DirectSequence A028234 = new A028234();
  private static final DirectSequence A067029 = new A067029();

  /** Construct the sequence. */
  public A290109() {
    super(1, (self, n) -> A067029.a(n).pow(self.a(A028234.a(n).intValueExact())), "1");
  }
}
