package irvine.oeis.a315;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a313.A313252;

/**
 * A315716 Coordination sequence Gal.5.210.5 where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A315716 extends A313252 {

  /** Construct the sequence. */
  public A315716() {
    super();
    defineBaseSet(4);
  }
}
