package irvine.oeis.a315;
// Generated by gen_seq4.pl tile6 at 2020-05-30 23:34
// DO NOT EDIT here!

import irvine.oeis.a310.A310152;

/**
 * A315830 Coordination sequence <code>Gal.5.42.4</code> where G.u.t.v denotes the coordination sequence for a vertex of type v in tiling number t in the Galebach list of u-uniform tilings.
 * @author Georg Fischer
 */
public class A315830 extends A310152 {

  /** Construct the sequence. */
  public A315830() {
    super();
    defineBaseSet(3);
  }
}
