package irvine.oeis.a010;
// Generated by gen_seq4.pl cfsqrt 159 at 2021-01-26 11:57
// DO NOT EDIT here!

import irvine.oeis.ContinuedFractionOfSqrtSequence;

/**
 * A010208 Continued fraction for sqrt(159).
 * @author Georg Fischer
 */
public class A010208 extends ContinuedFractionOfSqrtSequence {

  /** Construct the sequence. */
  public A010208() {
    super(0, 159);
  }
}
