package irvine.oeis.a030;
// Generated by gen_seq4.pl eulerper 1 23 -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -2 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A030199 Expansion of <code>x * Product_{k&gt;=1} (1 - x^k) * (1 - x^(23*k))</code>.
 * @author Georg Fischer
 */
public class A030199 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A030199() {
    super(new PeriodicSequence(-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -2), 0);
  }
}
