package irvine.oeis.a030;
// generated by patch_offset.pl at 2022-08-16 19:10

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A030065 a(4n)=n, a(4n+2)=a(4n)+a(4n+4), a(2n+1)=a(2n)+a(2n+2).
 * @author Georg Fischer
 */
public class A030065 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A030065() {
    super(0, "[[0],[1],[0],[0],[0],[-2],[0],[0],[0],[1]]", "[0, 1, 1, 2, 1, 4, 3, 5, 2]", 0);
  }
}
