package irvine.oeis.a317;
// Generated by gen_seq4.pl morfps at 2021-05-27 23:03
// DO NOT EDIT here!

import irvine.oeis.MorphismFixedPointSequence;


/**
 * A317203 Fixed under the morphism 1 -> 132, 2 -> 1, 3 -> 3.
 * @author Georg Fischer
 */
public class A317203 extends MorphismFixedPointSequence {

  /** Construct the sequence. */
  public A317203() {
    super("31", "3132", "1->132, 2->1, 3->3");
  }
}
