package irvine.oeis.a108;
// Generated by gen_seq4.pl rectoproc/holos at 2022-08-11 18:04

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A108243 a(n) = number of 3-regular (trivalent) multi-graphs without loops on 2n vertices; a(n) = number of symmetric 2n X 2n matrices with {0,1,2,3}-entries with row sum equal to 3 for each row and trace 0.
 * @author Georg Fischer
 */
public class A108243 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A108243() {
    super(0, "[[0],[-4989600, 30135960,-75458988, 105258076,-91991460, 53358140,-21100464, 5718768,-1045440, 123200,-8448, 256],[-1270080, 7458192,-17957664, 23781140,-19424280, 10318476,-3635352, 843360,-123840, 10432,-384],[-30240, 164376,-354372, 403704,-269388, 108864,-26208, 3456,-192],[-6180, 31822,-63330, 64486,-36810, 11908,-2040, 144],[-33, 121,-132, 44],[3,-15, 27,-18],[3]]", "1, 1, 10, 760, 190050, 103050570", 0);
  }
}
