package irvine.oeis.a108;
// Generated by gen_seq4.pl triconst at 2021-10-17 19:37

import irvine.oeis.a000.A000045;
import irvine.oeis.a020.A020701;
import irvine.oeis.triangle.WrappedConstantTriangle;

/**
 * A108035 Triangle read by rows: n-th row consists of n copies of the n-th nonzero Fibonacci number.
 * @author Georg Fischer
 */
public class A108035 extends WrappedConstantTriangle {

  /** Construct the sequence. */
  public A108035() {
    super(1, new A000045(), new A000045());
    setPlus(new A020701());
    skipLeft(2);
    skipRight(2);
  }
}
