package irvine.oeis.a108;
// Generated by gen_seq4.pl prisub at 2021-01-15 23:59
// DO NOT EDIT here!

import irvine.oeis.prime.PrimePositionSubsequence;


/**
 * A108899 Numbers n such that 11*n + 2357 is prime.
 * @author Georg Fischer
 */
public class A108899 extends PrimePositionSubsequence {

  /** Construct the sequence. */
  public A108899() {
    super("[[11],[1],[-1]]", "[2357]", 0);
  }
}
