package irvine.oeis.a134;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A134888 E_8 numbers: a(n) = 2^(2*n) * 3^(3*n) * 5^n * 839^n. (Constants are prime numbers).
 * @author Georg Fischer
 */
public class A134888 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A134888() {
    super(0, new long[] {1},
      new long[] {1, -453060});
  }
}
