package irvine.oeis.a134;
// Generated by gen_seq4.pl triprod at 2023-06-05 17:58

import irvine.oeis.a097.A097806;
import irvine.oeis.triangle.Product;

/**
 * A134315 A134309 * A097806.
 * @author Georg Fischer
 */
public class A134315 extends Product {

  /** Construct the sequence. */
  public A134315() {
    super(1, new A134309(), new A097806());
  }
}
