package irvine.oeis.a134;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.a000.A000668;

/**
 * A134872 Product of n-th Mersenne prime and 2^n.
 * @author Georg Fischer
 */
public class A134872 implements Sequence {

  final Sequence mA000668 = new A000668();
  protected long mN;
  /** Construct the sequence. */
  public A134872() {
    mN = 0;
  }
  
  @Override
  public Z next() {
    ++mN;
    return mA000668.next().multiply(Z.TWO.pow(Z.valueOf(mN)));
  }

}
