package irvine.oeis.a134;
// Generated by gen_pattern.pl - DO NOT EDIT here!

import irvine.oeis.GeneratingFunctionSequence;

/**
 * A134481 Row sums of triangle <code>A134480</code>.
 * @author Georg Fischer
 */
public class A134481 extends GeneratingFunctionSequence {

  /** Construct the sequence. */
  public A134481() {
    super(0, new long[] {1, 1, 6, -4, 1},
      new long[] {1, -4, 6, -4, 1});
  }
}
