package irvine.oeis.a134;
// Generated by gen_seq4.pl eulerper 0 12 -6, 3, 4, 0, -6, -10, -6, 0, 4, 3, -6, -4 at 2020-03-06 22:01
// DO NOT EDIT here!

import irvine.oeis.EulerTransformSequence;
import irvine.oeis.PeriodicSequence;

/**
 * A134078 Expansion of <code>(phi(-q) / phi(-q^2))^3 * phi(q^3)^5 / phi(-q^6)</code> in powers of q where <code>phi()</code> is a Ramanujan theta function.
 * @author Georg Fischer
 */
public class A134078 extends EulerTransformSequence {

  /** Construct the sequence. */
  public A134078() {
    super(new PeriodicSequence(-6, 3, 4, 0, -6, -10, -6, 0, 4, 3, -6, -4), 0);
  }
}
