package irvine.oeis.a370;
// Generated by gen_seq4.pl 2024-02-13/lambdan at 2024-02-13 21:05

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.oeis.LambdaSequence;

/**
 * A370099 a(n) = Sum_{k=0..n} binomial(2*n,k) * binomial(3*n-k-1,n-k).
 * @author Georg Fischer
 */
public class A370099 extends LambdaSequence {

  /** Construct the sequence. */
  public A370099() {
    super(0, n -> Integers.SINGLETON.sum(0, n, k -> Binomial.binomial(2 * n, k).multiply(Binomial.binomial(3 * n - k - 1, n - k))));
  }
}
