package irvine.oeis.a370;
// Generated by gen_seq4.pl 2024-07-01/sintrif at 2024-07-01 18:26

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.oeis.a105.A105751;
import irvine.oeis.transform.SingleTransformSequence;

/**
 * A370550 a(n) is the denominator of the imaginary part of Product_{k=1..n} (1/k + i) where i is the imaginary unit.
 * @author Georg Fischer
 */
public class A370550 extends SingleTransformSequence {

  /** Construct the sequence. */
  public A370550() {
    super(1, (term, n) -> new Q(term, Functions.FACTORIAL.z(n)).den(), "", new A105751());
  }
}
