package irvine.oeis.a370;
// Generated by gen_seq4.pl 2025-12-20.ack/lambdan at 2025-12-20 22:55

import irvine.math.function.Functions;
import irvine.oeis.DirectSequence;
import irvine.oeis.LambdaSequence;

/**
 * A370260 a(n) = sqrt(A370259(2*n+1)).
 * @author Georg Fischer
 */
public class A370260 extends LambdaSequence {

  private static final DirectSequence A370259 = new A370259();

  /** Construct the sequence. */
  public A370260() {
    super(0, n -> Functions.SQRT.z(A370259.a(2 * n + 1)));
  }
}
