package irvine.oeis.a211;
// Generated by gen_seq4.pl 2025-03-16.ack/lambdan at 2025-03-16 17:02

import irvine.math.function.Functions;
import irvine.math.q.Q;
import irvine.math.q.Rationals;
import irvine.oeis.LambdaSequence;

/**
 * A211306 Numerator of Sum_{k=1..n} 1/lambda(k), where  lambda(k) is the Carmichael&apos;s lambda function.
 * @author Georg Fischer
 */
public class A211306 extends LambdaSequence {

  /** Construct the sequence. */
  public A211306() {
    super(1, n -> Rationals.SINGLETON.sum(1, n, k -> new Q(1, Functions.CARMICHAEL_LAMBDA.z(k))).num());
  }
}
