package irvine.oeis.a211;
// Generated by gen_seq4.pl 2024-12-27.ack/lingfcj at 2024-12-27 23:20

import irvine.oeis.Conjectural;
import irvine.oeis.recur.GeneratingFunctionSequence;

/**
 * A211722 Number of -3..3 arrays x(i) of n+1 elements i=1..n+1 with set{t,u,v in 0,1}((x[i+t]+x[j+u]+x[k+v])*(-1)^(t+u+v)) having two, three or four distinct values for every i,j,k&lt;=n.
 * @author Georg Fischer
 */
public class A211722 extends GeneratingFunctionSequence implements Conjectural {

  /** Construct the sequence. */
  public A211722() {
    super(1, "[0,48,-110,-284,726,450,-1488,-130,1068,-28,-248]", "[1,-4,-2,25,-16,-46,48,26,-36,-4,8]");
  }
}
