package irvine.oeis.a181;
// Generated by gen_seq4.pl insect/insect2 at 2022-02-22 19:20

import irvine.oeis.IntersectionSequence;
import irvine.oeis.a001.A001694;
import irvine.oeis.a025.A025487;

/**
 * A181800 Powerful numbers that are the least integer of their prime signature.
 * @author Georg Fischer
 */
public class A181800 extends IntersectionSequence {

  /** Construct the sequence. */
  public A181800() {
    super(new A001694(), new A025487());
  }
}
