package irvine.oeis.a181;
// Generated by gen_seq4.pl expr_gen/lambda at 2023-08-21 21:22

import irvine.math.z.Binomial;
import irvine.math.z.Integers;
import irvine.math.z.Z;
import irvine.oeis.LambdaSequence;

/**
 * A181077 a(n) = Sum_{k=0..n-1} C(n-1,k)^(n-k) * n/(n-k).
 * @author Georg Fischer
 */
public class A181077 extends LambdaSequence {

  /** Construct the sequence. */
  public A181077() {
    super(1, n -> Integers.SINGLETON.sum(0, n - 1, k -> Binomial.binomial(n - 1, k).pow(Z.valueOf(n - k)).multiply(n).divide(Z.valueOf(n - k))));
  }
}
