package irvine.oeis.a181;
// Generated by gen_seq4.pl padding 1 at 2020-08-22 18:36
// DO NOT EDIT here!

import irvine.oeis.PaddingSequence;


/**
 * A181405 Total number of n-digit numbers requiring 8 positive cubes in their representation as sum of cubes.
 * @author Georg Fischer
 */
public class A181405 extends PaddingSequence {

  /** Construct the sequence. */
  public A181405() {
    super(new long[] {0, 3, 12}, new long[] {0});
  }
}
