package irvine.oeis.a210;
// Generated by gen_seq4.pl holos at 2021-06-13 21:50
// DO NOT EDIT here!

import irvine.oeis.recur.HolonomicRecurrence;

/**
 * A210486 Number of paths starting at {3}^n to a border position where one component equals 0 using steps that decrement one component by 1.
 * Recurrence: -a(n)*(n-1)+((n-1)*(n-2)*(n+1)*a(n-3)-(n-1)*(3*n^2-2*n-4)*a(n-2)+(2*n+1)*(n^2-n+2)*a(n-1))
 * @author Georg Fischer
 */
public class A210486 extends HolonomicRecurrence {

  /** Construct the sequence. */
  public A210486() {
    super(0, "[[0],[2,-1,-2, 1],[-4, 2, 5,-3],[2, 3,-1, 2],[1,-1]]", "[0, 1, 20]", 0);
  }
}
