package irvine.oeis.a171;
// Generated by gen_seq4.pl deriv at 2021-06-28 18:44

import irvine.math.z.Z;
import irvine.oeis.Sequence;
import irvine.oeis.Sequence1;
import irvine.oeis.a001.A001221;

/**
 * A171157 Number of distinct primes &gt; 3 that divide n.
 * @author Georg Fischer
 */
public class A171157 extends Sequence1 {

  final Sequence mA001221 = new A001221();
  final Sequence mA171182 = new A171182();
  @Override
  public Z next() {
    return mA001221.next().subtract(mA171182.next());
  }

}
